### ISSUE TITLE
Shadowsocks用 V2Ray-Plugin大可不必吧

### ISSUE THREAD

**Issue by mooyun** [XrayR-project/XrayR#1]

**Comment by RManLuo** [comment]
我对Shadowsocks这块的研究不是很多，V2Ray-Plugin和传统的Shadowsocks有什么区别呢？

**Comment by crossfw** [comment]
> 我对Shadowsocks这块的研究不是很多，V2Ray-Plugin和传统的Shadowsocks有什么区别呢？
不用装插件，更多客户端支持。具体 sspanel 支持方式请看此处 https://github.com/Anankke/SSPanel-Uim/pull/1206

**Comment by crackair** [comment]
已切换成单端口多用户 f2baf06
