### ISSUE TITLE
node_connector and alive_ip

### ISSUE THREAD

**Issue by thebadgateway** [XrayR-project/XrayR#100]
Сould you help me?. My back-end is old and I edit it myself. I recently noticed that limiting active connections for an account stopped working. I changed the code according to this commit https://github.com/Anankke/SSPanel-Uim/compare/c9721cdc...Anankke:87961 and now limiting connections works again. But when the user has a limit of 1 connection, then it is worth trying to switch the server 2-3 times and you will see a connection error. How to solve this problem? Previously, when there was a comparison of the IP compliance, everything worked fine. But now users are constantly complaining that they cannot change the server. Each reconnection takes 20-60 seconds.

**Comment by RManLuo** [comment]
Update your XrayR > v0.7.2 and check the comments about device limit at https://crackair.gitbook.io/xrayr-project/gong-neng-shuo-ming/devicelimit.
