### ISSUE TITLE
获取用户为0

### ISSUE THREAD

**Issue by kailin98** [XrayR-project/XrayR#101]
### 此Issue目测非后端问题，只是寻求帮助

XrayR 版本：`XrayR 0.7.5 (A Xray backend that supports many panels)`
使用面板：`SSPanel-Uim 2021.11`
问题：XrayR于2022.1.14早晨重启时，发现获取用户无故变为 0

面板管理界面显示用户存在，请教如何排查问题，**想知道后端获取和更新用户的具体接口信息**

**Comment by thank243** [comment]
​func​ (​c​ ​*​APIClient​) ​GetUserList​() (​UserList​ ​*​[]api.​UserInfo​, ​err​ ​error​) { 
 ​        ​path​ ​:=​ ​"/mod_mu/users" 
 ​        ​res​, ​err​ ​:=​ ​c​.​client​.​R​(). 
 ​                ​SetQueryParam​(​"node_id"​, ​strconv​.​Itoa​(​c​.​NodeID​)).

**Comment by kailin98** [comment]
服务器发送请求，返回的json：`{"ret":1,"data":null}`
不解...请问大佬如何进一步排查

**Comment by thank243** [comment]
问你的面板咋回事。

**Comment by RManLuo** [comment]
目测是面板用户下发问题，建议对面板上下断点逐步执行排查。

**Comment by kailin98** [comment]
感谢支持，联系面板开发者了
