### ISSUE TITLE
http :TLS handshake error from xxxxxx:48225:EOF

### ISSUE THREAD

**Issue by 310034188** [XrayR-project/XrayR#102]
我使用docker部署xrayR 前端用V2Board
![image](https://user-images.githubusercontent.com/81519434/149448368-388bc88a-1b39-4b26-9fa1-e8eba3a12633.png)
部署的很多台都是无法连通 日志显示是这个

**Comment by houpi** [comment]
这不写了证书问题吗？

**Comment by 310034188** [comment]
> 这不是写了证书问题吗？

有没有什么解决思路？我也尝试了用caddy申请 但是好像还是有问题

**Comment by houpi** [comment]
你用的一键脚本安装 ？一键脚本应该没问题，如果手动安装最好用docker.并用用acme.sh申请证书。

**Comment by 310034188** [comment]
> 你用的一键脚本安装 ？一键脚本应该没问题，如果手动安装最好用docker.并用用acme.sh申请证书。
目前的话就是用docker部署，也是用config.yml内的自动申请证书，我的部分部署XrayR的后端服务器没有问题，但是当我重启后端服务器，重新运行Docker时 就无法使用了。就出现了截图的问题，
