### ISSUE TITLE
VMESS AEAD 怎么修改

### ISSUE THREAD

**Issue by sockssr** [XrayR-project/XrayR#103]
用的xrayr 对接的v2board不知道在哪修改 

VMESS AEAD 将在 2022 年 1 月 1 日强制启用 请注意更新服务端配置，设置alterId = 0。
如果希望强制禁用此特性，请在系统环境变量添加：XRAY_VMESS_AEAD_FORCED=false。

**Comment by crackair** [comment]
@sockssr 节点设置->额外id（alterId）

**Comment by thank243** [comment]
脚本安装Xr的话就这样改

1.编辑XrayR.service
vi /etc/systemd/system/XrayR.service

[Service]里添加一行：
Environment="XRAY_VMESS_AEAD_FORCED=false"

2.更新systemd服务
systemctl daemon-reload

3.重启XrayR
systemctl restart XrayR

**Comment by JusufUs** [comment]
下个版本的XrayR内置进去吧

**Comment by thank243** [comment]
> 
> 下个版本的XrayR内置进去吧

废弃的东西干嘛要内置。

**Comment by RManLuo** [comment]
已废弃，只建议使用AEAD的加密方法。
