### ISSUE TITLE
XrayR可以限制一个路由器相同ip的设备数量吗

### ISSUE THREAD

**Issue by BrunuhVille** [XrayR-project/XrayR#103]
您好
XrayR可以限制一个路由器相同ip的设备数量吗
一个路由器连接十几台设备，测试了下，限制数量似乎没有效果

**Comment by thank243** [comment]
There is no magic can sniffer devices under NAT.

**Comment by BrunuhVille** [comment]
> There is no magic can sniffer devices under NAT.

每个设备的mac地址是不同的，可以根据mac地址进行判断、检测吗

**Comment by thank243** [comment]
> > There is no magic can sniffer devices under NAT.
> 
> 每个设备的mac地址是不同的，可以根据mac地址进行判断、检测吗

So you can contact the client send this msg first?

**Comment by BrunuhVille** [comment]
> So you can contact the client send this msg first?

总体上的判定逻辑应该是类似的，细节上可能有一些改动

比如说，先连接上，如果判定达到数量限制了再断开

**Comment by thank243** [comment]
Firstly, the client must have this func. And then, The backend can only be implemented.
