### ISSUE TITLE
V2board面板重复上报多次数据流量

### ISSUE THREAD

**Issue by themojie** [XrayR-project/XrayR#106]
查看版本更新可能与0.8.3版本更新有关：汇报流量失败时不再清空流量，会一直保存直到上传成功。 

在v2board，在队列繁忙或者节点与面板通讯不佳时，再次恢复通信，会多次上报流量和用户数据，10人在线的节点会上报超过100人，并且百倍扣除流量。优化节点与面板通信后，问题仍在。

更换其他节点无此问题，问题在xrayr上可以重复复现。

**Comment by thank243** [comment]
This panel's problem. Pls goto v2b for help
