### ISSUE TITLE
关于内存自动回收机制？

### ISSUE THREAD

**Issue by moranno** [XrayR-project/XrayR#109]
使用过程中发现xrayr占用的内存越来越多，一段时间后vps的内存就爆了死机，请问xrayr是否有自动内存回收？或者增强下内存管理？
版本：最新的0.7.5

**Comment by RManLuo** [comment]
XrayR使用的是go的内存回收机制，请提供面板用户数量和协议。

**Comment by moranno** [comment]
面板使用v2b，9000用户，协议trojan，vps配置1C1G，同时在线人数一般在50人左右。

**Comment by RManLuo** [comment]
带机场，建议升级机器配置。

**Comment by lithromantic** [comment]
同样遇到内存泄露问题，用户较少，最后也会爆掉
