### ISSUE TITLE
后端对接metron面板会监听中转端口

### ISSUE THREAD

**Issue by hixiaoaitongxue** [XrayR-project/XrayR#11]
后端对接metron面板（基于sspanel-uim），中转的情况会监听中转端口12345
示例：gz.aaa.com;port=443#12345|host=hk.aaa.com
![123](https://user-images.githubusercontent.com/79915478/116806189-f7a49a00-ab5d-11eb-823d-94bb69c3b130.png)
![221](https://user-images.githubusercontent.com/79915478/116806193-fa06f400-ab5d-11eb-9c6d-a723e881b440.png)

**Comment by crossfw** [comment]
@hixiaoaitongxue 好像没有问题，不清楚所谓的“中转端口”是什么，向后端下发偏移后的端口在sspanel的config里有开关，关闭后后端将监听443端口

**Comment by hixiaoaitongxue** [comment]
![image](https://user-images.githubusercontent.com/79915478/116806550-65ea5c00-ab60-11eb-89eb-a7b4a49bf502.png)
设置确信是关闭的，刚刚新搭建了一个metron用soga测试也有这个问题。应该是我自己的问题 谢谢大佬解惑

**Comment by hixiaoaitongxue** [comment]
希望大佬百忙之中可以抽空让sspanel对接trojan的时候，像v2ray一样用 |outside_port=xxx 指定连接端口，目前只能用443#12345 指定，这个方法有不少版本的sspanel不会生效。
