### ISSUE TITLE
BUG.

### ISSUE THREAD

**Issue by sdfsdfsdf145314364** [XrayR-project/XrayR#110]
Shadowsocks TCP貌似有BUG。

具体表现，冒险岛这个游戏，改了UUID之后,或者流量耗尽之后，游戏都不会掉线，但是只要换一个频道就会掉线了，之后就无法进行游戏了。

此游戏使用TCP进行传输。

**Comment by sdfsdfsdf145314364** [comment]
不确定是XRAYR的bug还是XRAY的bug，就先发这边了。

**Comment by thank243** [comment]
这不是bug，是特性。

**Comment by RManLuo** [comment]
游戏TCP处于长连接，所以在不重新建立连接的情况下不会打断连接，自然不会掉线。更换频道或者登陆登出等行为会打断连接，再重新连接的时候会由于验证失败掉线。
