### ISSUE TITLE
Error when using GlobalLimit . function

### ISSUE THREAD

**Issue by Github-Aiko** [XrayR-project/XrayR#111]
<img width="880" alt="Screen Shot 2022-11-22 at 13 52 04" src="https://user-images.githubusercontent.com/100770712/203245022-4b7f89db-97d6-40ce-8f54-8dd7ad20226e.png">
I had an error like this when using the Global Limited function, how to fix it?

**Comment by Github-Aiko** [comment]
I had an error like this when using the Global Limited function, how to fix it?

**Comment by thank243** [comment]
It seems that is xray-core problem not xrayr.

**Comment by Github-Aiko** [comment]
It appears like that if I overcame the device, normally no.

**Comment by thank243** [comment]
I have refactored this feature and will PR a few days.

**Comment by Github-Aiko** [comment]
Thx .
