### ISSUE TITLE
能支持ss2022协议嘛？

### ISSUE THREAD

**Issue by ckaak** [XrayR-project/XrayR#113]
2022-blake3-aes-128-gcm
2022-blake3-aes-256-gcm
2022-blake3-chacha20-poly1305

XRAY内核支持，就是XRAYR没接口。报错不支持此加密。

**Comment by thank243** [comment]
Do you have any panel's API support this proto?

**Comment by ckaak** [comment]
> 你有任何面板的 API 支持这个原型吗？

https://github.com/v2board/v2board/commit/964376fa3cb7886a4f6c0edf36ef56d316957202

V2board dev支持了，sspanel也可以？

**Comment by thank243** [comment]
The xray-core's shadowsocks2022 has not implemented `proxy.UserManager`. So cannot add it.
