### ISSUE TITLE
最新的版本0.7.6 存在bug

### ISSUE THREAD

**Issue by lithromantic** [XrayR-project/XrayR#113]
作者你好，昨天推送的最新0.7.6版本存在bug，会忽略配置文件中的自定义路由和outbound配置文件，同样的配置文件在回滚到0.7.5中测试没有问题。

**Comment by thank243** [comment]
我猜和tag有关系。

**Comment by RManLuo** [comment]
请提供相关配置文件设置。

**Comment by lithromantic** [comment]
dns:
{
    "domainStrategy": "IPOnDemand",
    "rules": [
        {
            "type": "field",
            "outboundTag": "block",
            "ip": [
                "geoip:private"
            ]
        },
        {
            "type": "field",
            "outboundTag": "block",
            "protocol": [
                "bittorrent"
            ]
        },
        {
            "type": "field",
            "outboundTag": "socks_out",
            "domain": ["geosite:netflix","nflxvideo.net","nflxext.com","nflxso.net","ipinfo.io","geosite:google"]
        }
    ]
}

outbound:
[
    {
        "tag": "IPv4_out",
        "protocol": "freedom"
    },
    {
        "tag": "IPv6_out",
        "protocol": "freedom",
        "settings": {
            "domainStrategy": "UseIPv6"
        }
    },
    {
        "protocol": "blackhole",
        "tag": "block"
    },
    {
        "tag": "socks_out",
        "protocol": "socks",
        "settings": {
            "servers": [{
                "address": "10.0.0.X",
                "port": 1080,
                "users": [{
                    "user": "X",
                    "pass": "X"
                }]
            }],
            "domainStrategy": "UseIPv4"
        }
    }
]

**Comment by thank243** [comment]
试下outbound改成outbounds？

**Comment by lithromantic** [comment]
outboundTag 改 outboundsTag吗？

**Comment by RManLuo** [comment]
检查是否将geosite文件放在与配置文件同级目录，并开启debug，查看访问Netflix域名的流量是如何被路由的。

**Comment by lithromantic** [comment]
放了，netflix taking default detour 貌似是这样的日志，采用默认路由，route.json 不生效, 回滚到0.7.5什么都不改，就一切正常

**Comment by RManLuo** [comment]
采用同样配置文件测试没有问题
rayR/app/mydispatcher: taking detour [socks_out] for [tcp:push.prod.netflix.com:443]
