### ISSUE TITLE
游戏加速通，游戏语音不通

### ISSUE THREAD

**Issue by lsbjkc** [XrayR-project/XrayR#114]
V2board面板后端使用Trojan，客户端netch1.97，可正常用于游戏加速，但是游戏内语音不通；
SSPanel面板使用配套Trojan后端，客户端netch1.97，游戏语音正常。
按理说应该都是udp协议，不知道为什么游戏可以转，游戏内语音却转不了。

**Comment by lsbjkc** [comment]
测试使命召唤战区2.0游戏语音可用，但是PUBG的语音不行

**Comment by thank243** [comment]
no logs？

**Comment by lsbjkc** [comment]
日志开debug，目录里并未生成，我直接用journalctl实时查看并复制下来了；
语音不通似乎与【pubwxp.vivox.com】无法解析有关；
部分日志如下：
Nov 25 08:48:01 localhost.localdomain XrayR[249289]: 2022/11/25 08:48:01 [Info] [1191388473] proxy/trojan: tunnelling request to udp:20.249.220.62:24893
Nov 25 08:48:01 localhost.localdomain XrayR[249289]: 2022/11/25 08:48:01 [Debug] [1191388473] transport/internet/udp: dispatch request to: udp:20.249.220.62:24893
Nov 25 08:48:01 localhost.localdomain XrayR[249289]: 2022/11/25 08:48:01 [Info] [2226391216] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:pubwxp.vivox.com:443 > common/retry: [dial tcp: lookup pubwxp.vivox.com on 1.1.1.1:53: no such host] > common/retry: all retry attempts failed
Nov 25 08:48:01 localhost.localdomain XrayR[249289]: 2022/11/25 08:48:01 [Info] [2226391216] app/proxyman/inbound: connection ends > proxy/trojan: connection ends > proxy/trojan: failed to write response > io: read/write on closed pipe
Nov 25 08:48:01 localhost.localdomain XrayR[249289]: 2022/11/25 08:48:01 [Info] [1191388473] proxy/trojan: tunnelling request to udp:20.249.220.62:24893
Nov 25 08:48:01 localhost.localdomain XrayR[249289]: 2022/11/25 08:48:01 [Debug] [1191388473] transport/internet/udp: dispatch request to: udp:20.249.220.62:24893
日志附件：
[XrayR加速PUBG日志.log](https://github.com/XrayR-project/XrayR/files/10087905/XrayR.PUBG.log)

**Comment by lsbjkc** [comment]
SSPanel配套Trojan后端加速PUBG的游戏内语音却是通的；但是其NAT为2，不支持像战区2.0这类游戏；
日志附件：
[SSPanel配套Trojan后端的PUBG加速日志.log](https://github.com/XrayR-project/XrayR/files/10087973/SSPanel.Trojan.PUBG.log)

**Comment by thank243** [comment]
try
 `dig pubwxp.vivox.com`
`dig @1.1.1.1 pubwxp.vivox.com`

**Comment by lsbjkc** [comment]
> try `dig pubwxp.vivox.com` `dig @1.1.1.1 pubwxp.vivox.com`

[root@localhost ~]# dig pubwxp.vivox.com

; <<>> DiG 9.11.36-RedHat-9.11.36-5.el8 <<>> pubwxp.vivox.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 22630
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pubwxp.vivox.com.		IN	A

;; AUTHORITY SECTION:
vivox.com.		3600	IN	SOA	ns-vx-010101-2.vivox.com. root.vivox.com. 2022112303 10800 3600 604800 3600

;; Query time: 208 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Nov 25 10:45:47 CST 2022
;; MSG SIZE  rcvd: 101
——————————————————————————————————————————————————————
[root@localhost ~]# dig @1.1.1.1 pubwxp.vivox.com

; <<>> DiG 9.11.36-RedHat-9.11.36-5.el8 <<>> @1.1.1.1 pubwxp.vivox.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 11421
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pubwxp.vivox.com.		IN	A

;; AUTHORITY SECTION:
vivox.com.		3600	IN	SOA	ns-vx-010101-2.vivox.com. root.vivox.com. 2022112303 10800 3600 604800 3600

;; Query time: 207 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Fri Nov 25 10:46:24 CST 2022
;; MSG SIZE  rcvd: 101

**Comment by thank243** [comment]
change your dns server `8.8.8.8 8.8.4.4`

**Comment by lsbjkc** [comment]
> change your dns server `8.8.8.8 8.8.4.4`

结果还是一样：
Nov 25 18:58:57 localhost.localdomain XrayR[254827]: 2022/11/25 18:58:57 [Info] [2010643052] proxy/trojan: tunnelling request to udp:20.249.216.84:25424
Nov 25 18:58:57 localhost.localdomain XrayR[254827]: 2022/11/25 18:58:57 [Debug] [2010643052] transport/internet/udp: dispatch request to: udp:20.249.216.84:25424
Nov 25 18:58:57 localhost.localdomain XrayR[254827]: 2022/11/25 18:58:57 [Info] [4263840190] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: failed to open connection to tcp:pubwxp.vivox.com:443 > common/retry: [dial tcp: lookup pubwxp.vivox.com on 8.8.8.8:53: no such host] > common/retry: all retry attempts failed
Nov 25 18:58:57 localhost.localdomain XrayR[254827]: 2022/11/25 18:58:57 [Info] [4263840190] app/proxyman/inbound: connection ends > proxy/trojan: connection ends > proxy/trojan: failed to write response > io: read/write on closed pipe
Nov 25 18:58:57 localhost.localdomain XrayR[254827]: 2022/11/25 18:58:57 [Info] [2010643052] proxy/trojan: tunnelling request to udp:20.249.216.84:25424
Nov 25 18:58:57 localhost.localdomain XrayR[254827]: 2022/11/25 18:58:57 [Debug] [2010643052] transport/internet/udp: dispatch request to: udp:20.249.216.84:25424
DNS设置：
[root@localhost ~]# cat /etc/resolv.conf
# Generated by NetworkManager
nameserver 8.8.8.8
nameserver 8.8.4.4
日志附件：
[PUBG加速日志.log](https://github.com/XrayR-project/XrayR/files/10092332/PUBG.log)

**Comment by thank243** [comment]
this domain is deprecated

**Comment by lsbjkc** [comment]
> this domain is deprecated

但为什么SSPanel的配套Trojan又可以呢？

**Comment by thank243** [comment]
check your config and logs

**Comment by lsbjkc** [comment]
> check your config and logs

当我开启【DisableSniffing】的时候，游戏语音短暂的连通了，但是十几秒后又失联了

**Comment by lsbjkc** [comment]
> > check your config and logs
> 
> 当我开启【DisableSniffing】的时候，游戏语音短暂的连通了，但是十几秒后又失联了

这个问题似乎和这个issue类似：
https://github.com/XTLS/Xray-core/discussions/364#discussioncomment-474438

**Comment by thank243** [comment]
Pls go to xray-core for help.

**Comment by lsbjkc** [comment]
> Pls go to xray-core for help.

thanks for your patience！
