### ISSUE TITLE
API Timeout problem

### ISSUE THREAD

**Issue by skrittdev** [XrayR-project/XrayR#115]
If I change the api Timeout in config.yml it will not affect the timeout between requests.
![image](https://user-images.githubusercontent.com/25477504/153715907-be55accb-27a6-4def-b667-d25f74f3311a.png)
![image](https://user-images.githubusercontent.com/25477504/153715932-9e3a8c76-4698-4d95-8ded-6e8654777d80.png)

**Comment by thank243** [comment]
timeout is not the internal time.

**Comment by RManLuo** [comment]
The time gap between request is controlled by the`UpdatePeriodic`.
