### ISSUE TITLE
0.8.6版限制设备

### ISSUE THREAD

**Issue by tristesky** [XrayR-project/XrayR#116]
可不可以每个后端都安装一个本地的redis服务？然后添加配置文件：

GlobalDeviceLimitConfig:
    Limit: 0 # The global device limit of a user, 0 means disable
    RedisAddr: 127.0.0.1:6379 # The redis server address
    RedisPassword: YOUR PASSWORD # Redis password
    RedisDB: 0 # Redis DB
    Timeout: 5 # Timeout for redis request
    Expiry: 60 # Expiry time (second)

这样可以达到全局限制设备吗，因为都是在本地的redis它们之间怎么通信，

**Comment by thank243** [comment]
Goolgle: how to setup a redis cluster

**Comment by tristesky** [comment]
> 

谢谢
