### ISSUE TITLE
two nodes with two subdomains on single port

### ISSUE THREAD

**Issue by Raminkash** [XrayR-project/XrayR#117]
hi everyone

how can i setup two node with to subdomain on port 443

everytime i set it up , xratyr didnt start

**Comment by amin550** [comment]
Use fallback feature

https://xrayr-project.github.io/XrayR-doc/gong-neng-shuo-ming/fallback.html

**Comment by thank243** [comment]
Consider use nginx stream proxy

**Comment by Raminkash** [comment]
> Consider use nginx stream proxy

you mean i should reverse it like bottom ? 

stream {  

  map $ssl_preread_server_name $targetBackend {
    ab.mydomain.com  upstream1.example.com:443;
    xy.mydomain.com  upstream2.example.com:443;
  }   
 
  server {
    listen 443; 
        
    proxy_connect_timeout 1s;
    proxy_timeout 3s;
    resolver 1.1.1.1;
    
    proxy_pass $targetBackend;       
    ssl_preread on;
  }
}

?
