### ISSUE TITLE
Global Limit Not Works !!!

### ISSUE THREAD

**Issue by Github-Aiko** [XrayR-project/XrayR#123]
I am testing it and doesn't work !!!

_Originally posted by @Github-Aiko in https://github.com/XrayR-project/XrayR/issues/121#issuecomment-1328220412_

**Comment by Github-Aiko** [comment]
@thank243 
<img width="879" alt="Screen Shot 2022-11-27 at 18 40 38" src="https://user-images.githubusercontent.com/100770712/204133299-ae58398a-153f-4caf-bac9-a64d2b2c40d6.png">

here

**Comment by Github-Aiko** [comment]
I have 1 device limit, but when Connect 2 node both use normally. There is no problem.

**Comment by thank243** [comment]
v2ray is working properly. Pls delete the pic

**Comment by Github-Aiko** [comment]
> v2ray is working properly. Pls delete the pic

okay ,I deleted the picture.

**Comment by thank243** [comment]
You should use different IP on same account to test.

**Comment by Github-Aiko** [comment]
i know it , i test it before testing and the 2 devices are 2 completely different IPs .

**Comment by Github-Aiko** [comment]
And both devices work normally.

**Comment by thank243** [comment]
You can start 2 node, and use one of it. the other node should log `Report 1 online users`

**Comment by thank243** [comment]
@pocketW The local online user map's flush time should refactor.

**Comment by thank243** [comment]
Try set `UpdatePeriodic: 300`

**Comment by Github-Aiko** [comment]
Okay :D

**Comment by thank243** [comment]
> 

revert your config and try the lastest version

**Comment by Github-Aiko** [comment]
> revert your config and try the lastest version

Same Old Ver , Not Works . You Have test it

**Comment by Github-Aiko** [comment]
@thank243 | I deployed the docker. And do not save anything in DB Redis. and not works

**Comment by thank243** [comment]
Its difficult to recall this bug. Can you debug it?

**Comment by thank243** [comment]
Hello @AikoCute-Offical , Try this version
https://github.com/XrayR-project/XrayR/suites/9584088355/artifacts/456712702

**Comment by thank243** [comment]
Are you kidding me? You use 086 to test 087's feat?

**Comment by Github-Aiko** [comment]
> Are you kidding me? You use 086 to test 087's feat?

The link you sent me is 0.8.6 Not 0.8.7

**Comment by Github-Aiko** [comment]
> Are you kidding me? You use 086 to test 087's feat?

Link from Action 0.8.6 not 0.8.7 - You need Check it

**Comment by Github-Aiko** [comment]
#129 I have Commit Fix it ( 🎉 ) @thank243
