### ISSUE TITLE
rejected  proxy/vless/encoding: invalid request version

### ISSUE THREAD

**Issue by dekinsq** [XrayR-project/XrayR#128]
请问该怎么解决：

rejected  proxy/vless/encoding: invalid request version

XrayR 版本：XrayR 0.8.6

使用sslpanel uim
版本： https://github.com/Anankke/SSPanel-Uim/releases/tag/2022.11

mac 客户端：
v2rayN 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/48954045/204596978-fb8cc1d7-8ef4-49d0-b1a5-80d609d79e9b.png">

报错：

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/48954045/204597174-31cb9ade-1133-4776-a3d2-9d51de67a58d.png">

**Comment by thank243** [comment]
Direct to xray-core for help.
