### ISSUE TITLE
 XrayR[6392]

### ISSUE THREAD

**Issue by a937983423** [XrayR-project/XrayR#133]
3月 04 18:04:01 C20220303187187 XrayR[6392]: 2022/03/04 18:04:01 Start the panel..
3月 04 18:04:01 C20220303187187 XrayR[6392]: 2022/03/04 18:04:01 Xray Core Version: 1.5.2
3月 04 18:04:01 C20220303187187 XrayR[6392]: 2022/03/04 18:04:01 [Warning] core: Xray 1.5.2 started
3月 04 18:04:01 C20220303187187 XrayR[6392]: 2022/03/04 18:04:01 custom_config is empty! take config from address now.
3月 04 18:04:01 C20220303187187 XrayR[6392]: 2022/03/04 18:04:01 [INFO] [node1.test.com] acme: Obtaining bundled SAN certificate
3月 04 18:04:02 C20220303187187 XrayR[6392]: 2022/03/04 18:04:02 [INFO] [node1.test.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/84220439670
3月 04 18:04:02 C20220303187187 XrayR[6392]: 2022/03/04 18:04:02 [INFO] [node1.test.com] acme: Could not find solver for: tls-alpn-01
3月 04 18:04:02 C20220303187187 XrayR[6392]: 2022/03/04 18:04:02 [INFO] [node1.test.com] acme: Could not find solver for: http-01
3月 04 18:04:02 C20220303187187 XrayR[6392]: 2022/03/04 18:04:02 [INFO] [node1.test.com] acme: use dns-01 solver
3月 04 18:04:02 C20220303187187 XrayR[6392]: 2022/03/04 18:04:02 [INFO] [node1.test.com] acme: Preparing to solve DNS-01
3月 04 18:04:02 C20220303187187 XrayR[6392]: 2022/03/04 18:04:02 [INFO] [node1.test.com] acme: Cleaning DNS-01 challenge
3月 04 18:04:03 C20220303187187 XrayR[6392]: 2022/03/04 18:04:03 [WARN] [node1.test.com] acme: cleaning up failed: alicloud: API call failed: SDK.ServerError
3月 04 18:04:03 C20220303187187 XrayR[6392]: ErrorCode: InvalidAccessKeyId.NotFound
3月 04 18:04:03 C20220303187187 XrayR[6392]: Recommend: https://error-center.aliyun.com/status/search?Keyword=InvalidAccessKeyId.NotFound&source=PopGw
3月 04 18:04:03 C20220303187187 XrayR[6392]: RequestId: 103A877F-C844-5744-A49D-0AB0FCB32E26
3月 04 18:04:03 C20220303187187 XrayR[6392]: Message: Specified access key is not found.
3月 04 18:04:03 C20220303187187 XrayR[6392]: RespHeaders: map[Access-Control-Allow-Headers:[X-Requested-With, X-Sequence, _aop_secret, _aop_signature, x-acs-action, x-acs-version, x-acs-date, Content-Type] Access-Control-Allow-Methods:[POST, GET, OPTIONS, PUT, DELETE] Access-Control-Allow-Origin:[*] Access-Control-Max-Age:[172800] Connection:[keep-alive] Content-Length:[276] Content-Type:[application/json;charset=utf-8] Date:[Fri, 04 Mar 2022 10:04:03 GMT] X-Acs-Request-Id:[103A877F-C844-5744-A49D-0AB0FCB32E26] X-Acs-Trace-Id:[825e99ad6c195568ffc6bf9299b9b939]]
3月 04 18:04:03 C20220303187187 XrayR[6392]: 2022/03/04 18:04:03 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/84220439670
3月 04 18:04:03 C20220303187187 XrayR[6392]: 2022/03/04 18:04:03 Could not obtain certificates:

**Comment by RManLuo** [comment]
查看文档，正确配置申请证书相关选项。https://crackair.gitbook.io/xrayr-project/gong-neng-shuo-ming/cert
