### ISSUE TITLE
Environment "xray.vmess.aead.forced=false" does not work.

### ISSUE THREAD

**Issue by uf1y** [XrayR-project/XrayR#135]
[希望增加vmess向下兼容的支持 #134](https://github.com/XrayR-project/XrayR/issues/134)

You guys please reopen this ticket.

Is this a bug?

**Comment by thank243** [comment]
you can try `xray_vmess_aead_forced=false`

**Comment by uf1y** [comment]
> 

Itried "V2RAY_VMESS_AEAD_FORCED=false", failed.

Well, thank you very much. I'll try this command.

**Comment by uf1y** [comment]
> you can try `xray_vmess_aead_forced=false`

Does not work :(

**Comment by thank243** [comment]
use Upper on key

**Comment by MrVb0** [comment]
> [Hope to add vmess backward compatibility support #134](https://github.com/XrayR-project/XrayR/issues/134)
> 
> You guys please reopen this ticket.
> 
> Is this a bug?

I have this problem too, please help me [#240](https://github.com/XrayR-project/XrayR/issues/240)

**Comment by sakzri** [comment]
> > [Hope to add vmess backward compatibility support #134](https://github.com/XrayR-project/XrayR/issues/134)
> > You guys please reopen this ticket.
> > Is this a bug?
> 
> I have this problem too, please help me [#240](https://github.com/XrayR-project/XrayR/issues/240)

firstly run `export XRAY_VMESS_AEAD_FORCED=false `
then, run `./XrayR -config config.yml` works
