### ISSUE TITLE
XrayR启动失败

### ISSUE THREAD

**Issue by fangaso** [XrayR-project/XrayR#138]
`Log:
  Level: warning # Log level: none, error, warning, info, debug
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:                                                                           Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB                         Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
            ApiHost: "https://xxx.xxx.com"
      ApiKey: "a6f92n8d03nd6c8k"
      NodeID: 1
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Limit: 0 # The global device limit of a user, 0 means disable
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb`

`Dec 03 16:59:47 MiddleEast systemd[1]: XrayR.service: Unit entered failed state.
Dec 03 16:59:47 MiddleEast systemd[1]: XrayR.service: Failed with result 'exit-code'.
Dec 03 16:59:58 MiddleEast systemd[1]: XrayR.service: Service hold-off time over, scheduling restart.
Dec 03 16:59:58 MiddleEast systemd[1]: Stopped XrayR Service.
Dec 03 16:59:58 MiddleEast systemd[1]: Started XrayR Service.
Dec 03 16:59:58 MiddleEast XrayR[4475]: XrayR 0.8.6 (A Xray backend that supports many panels)
Dec 03 16:59:58 MiddleEast XrayR[4475]: 2022/12/03 16:59:58 Config file error: While parsing config: yaml: line 16: did not find expected key
Dec 03 16:59:58 MiddleEast XrayR[4475]: panic: Config file error: While parsing config: yaml: line 16: did not find expected key
Dec 03 16:59:58 MiddleEast XrayR[4475]: goroutine 1 [running]:
Dec 03 16:59:58 MiddleEast XrayR[4475]: log.Panicf({0x2f5ed23?, 0x7ffe26bccf13?}, {0xc0006c1e88?, 0xc000012020?, 0x2f45265?})
Dec 03 16:59:58 MiddleEast XrayR[4475]:         log/log.go:395 +0x67
Dec 03 16:59:58 MiddleEast XrayR[4475]: main.getConfig()
Dec 03 16:59:58 MiddleEast XrayR[4475]:         github.com/XrayR-project/XrayR/main/main.go:60 +0x11e
Dec 03 16:59:58 MiddleEast XrayR[4475]: main.main()
Dec 03 16:59:58 MiddleEast XrayR[4475]:         github.com/XrayR-project/XrayR/main/main.go:75 +0x9f
Dec 03 16:59:58 MiddleEast systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 03 16:59:58 MiddleEast systemd[1]: XrayR.service: Unit entered failed state.
Dec 03 16:59:58 MiddleEast systemd[1]: XrayR.service: Failed with result 'exit-code'.`

不知道哪里出了问题

**Comment by thank243** [comment]
check your config file.
