### ISSUE TITLE
V2Board一直黄点 用户客户端无法科学

### ISSUE THREAD

**Issue by binad2022** [XrayR-project/XrayR#139]
后端是0.86版 V2Board是最新版

Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "http://nf.******.xyz/"
      ApiKey: "1***11"
      NodeID: 6
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      EnableXTLS: true # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Limit: 0 # The global device limit of a user, 0 means disable
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "n**1.****.xyz" # Domain to cert
        CertFile: /etc/XrayR/cert/n**1.****.xyz.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/n**1.****.xyz.key
        Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: h****@gmail.com
        DNSEnv: # DNS ENV option used by DNS provider
         CLOUDFLARE_EMAIL: h****@gmail.com
         CLOUDFLARE_API_KEY: deae464b*******36ff2cc4ee`

日志里启动也没异常
`12月 03 17:30:29 VM-741W9P0WB6AE.local XrayR[31417]: XrayR 0.8.6 (A Xray backend that supports many panels) 

12月 03 17:30:29 VM-741W9P0WB6AE.local XrayR[31417]: 2022/12/03 17:30:29 Start the panel..
12月 03 17:30:29 VM-741W9P0WB6AE.local XrayR[31417]: 2022/12/03 17:30:29 Xray Core Version: 1.6.3
12月 03 17:30:29 VM-741W9P0WB6AE.local XrayR[31417]: 2022/12/03 17:30:29 [Warning] core: Xray 1.6.3 started
12月 03 17:30:30 VM-741W9P0WB6AE.local XrayR[31417]: 2022/12/03 17:30:30 [V2ray: 6] Added 2 new users
12月 03 17:30:30 VM-741W9P0WB6AE.local XrayR[31417]: 2022/12/03 17:30:30 [V2ray: 6] Start monitor node status
12月 03 17:30:30 VM-741W9P0WB6AE.local XrayR[31417]: 2022/12/03 17:30:30 [V2ray: 6] Start report node status
`

**Comment by thank243** [comment]
check you turn off the firewall
