### ISSUE TITLE
交叉测试很多遍，不知道是v2board还是XrayR的问题

### ISSUE THREAD

**Issue by blackshot-zard** [XrayR-project/XrayR#140]
ss tojan 会导致ssh频繁掉线，只要不操作 撑不过2 3分钟
已经完成以下测试
1：确保线路不丢包（ucloud 的IEPL
2：已经用L2TP连接IEPL 测试7台服务器 不掉线 且隔段时间会去每个ssh按空格确保可操作性
3：手搓xray的ss同样可以做到不掉线 且同样间隔时间按空格确保可操作性
4：v2board+XrayR+trojan或者ss 都会导致ssh频繁掉线

**Comment by thank243** [comment]
Google it. What's ssh timeout.

**Comment by blackshot-zard** [comment]
> Google it. What's ssh timeout.

是的 我查过 且按操作执行过 并不影响我掉线 刚刚手滑按到发送了 现在更新了问题

**Comment by blackshot-zard** [comment]
而且我尝试修改这部分配置 得到的结果是 ssh不显示掉线，
但是一旦操作就会掉线 所以我上述会详细写明 测试时会间断的给每个ssh按空格 
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 10 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB

**Comment by thank243** [comment]
I cannot recall this problems. Check your network and terminal config.

**Comment by blackshot-zard** [comment]
> I cannot recall this problems. Check your network and terminal config.

已经交叉测试了整晚，确定网络没问题，且确定只要不使用v2board+xrayr生成的节点就不会出现ssh频繁掉线

**Comment by thank243** [comment]
```
2022/12/04 00:44:32 [Warning] core: Xray 1.6.1 started
2022/12/04 00:44:44 [Info] [4041157421] proxy/socks: TCP Connect request to tcp:1.2.3.4:22
2022/12/04 00:44:45 [Info] [4041157421] app/dispatcher: default route for tcp:1.2.3.4:22
2022/12/04 00:44:45 [Info] [4041157421] transport/internet/tcp: dialing TCP to tcp:1.1.1.1:10000
2022/12/04 00:44:45 tcp:127.0.0.1:57841 accepted tcp:1.2.3.4:22 [socks >> proxy]
2022/12/04 00:44:45 [Debug] transport/internet: dialing to tcp:1.1.1.1:10000
2022/12/04 00:44:45 [Info] [4041157421] proxy/trojan: tunneling request to tcp:1.2.3.4:22 via 1.1.1.1:10000
2022/12/04 00:56:12 [Info] [4041157421] app/proxyman/inbound: connection ends > proxy/socks: connection ends > context canceled
```
Cannot recall check your network and terminal config.

**Comment by blackshot-zard** [comment]
> 

没事 这个问题是百分之百可以复现的 具体是那端的原因就不知道了，看有没有其他人遇到这个问题吧

**Comment by ishkong** [comment]
I can reproduce the issue as I've been plagued by this. It's definitely not an ssh configuration issue, as ssh doesn't get interrupted when I connect through another VPS, or when I'm on a good local network not connected through a proxy. I think it's a proxy configuration issue, but I haven't pinpointed where the configuration is wrong.

我能复现该问题，因为我一直被这个困扰。这绝对不是ssh配置问题，因为当我通过别的VPS连接时，或在本地网络良好不通过代理连接时，SSH不会被中断。我认为是代理配置的问题，但是我并没有定位到是哪里配置出现了问题。

**Comment by ggfvictor** [comment]
> ss tojan 会导致ssh频繁掉线，只要不操作 撑不过2 3分钟 已经完成以下测试 1：确保线路不丢包（ucloud 的IEPL 2：已经用L2TP连接IEPL 测试7台服务器 不掉线 且隔段时间会去每个ssh按空格确保可操作性 3：手搓xray的ss同样可以做到不掉线 且同样间隔时间按空格确保可操作性 4：v2board+XrayR+trojan或者ss 都会导致ssh频繁掉线

我也有此问题，会断线 我是v2ray vmess

**Comment by blackshot-zard** [comment]
> I can reproduce the issue as I've been plagued by this. It's definitely not an ssh configuration issue, as ssh doesn't get interrupted when I connect through another VPS, or when I'm on a good local network not connected through a proxy. I think it's a proxy configuration issue, but I haven't pinpointed where the configuration is wrong.
> 
> 我能复现该问题，因为我一直被这个困扰。这绝对不是ssh配置问题，因为当我通过别的VPS连接时，或在本地网络良好不通过代理连接时，SSH不会被中断。我认为是代理配置的问题，但是我并没有定位到是哪里配置出现了问题。

我也被这个问题困扰了将近一年 买了各种线路都不行，目前算是临时解决了，v2b只下发 后端手搓

**Comment by thank243** [comment]
Try to set
 '''
ConnectionConfig:    ConnIdle: 300 # Connection idle time limit, Second
'''

**Comment by ggfvictor** [comment]
> > I can reproduce the issue as I've been plagued by this. It's definitely not an ssh configuration issue, as ssh doesn't get interrupted when I connect through another VPS, or when I'm on a good local network not connected through a proxy. I think it's a proxy configuration issue, but I haven't pinpointed where the configuration is wrong.
> > 我能复现该问题，因为我一直被这个困扰。这绝对不是ssh配置问题，因为当我通过别的VPS连接时，或在本地网络良好不通过代理连接时，SSH不会被中断。我认为是代理配置的问题，但是我并没有定位到是哪里配置出现了问题。
> 
> 我也被这个问题困扰了将近一年 买了各种线路都不行，目前算是临时解决了，v2b只下发 后端手搓

后端手搓是什么意思

**Comment by ggfvictor** [comment]
> Try to set
> 
> ```
> ConnectionConfig:    ConnIdle: 300 # Connection idle time limit, Second
> ```

still not work
我来详细说明下如何复现，比如我有一台server的ssh需要通过代理中转来连接，此时代理后端是xrayR就会出现在ssh连接成功后若干分钟自动断开的情况。尝试过后端使用其他程序实现并未出现上述自动断开现象。更改了onnectionConfig:    ConnIdle:也没有缓解这个问题。

**Comment by ggfvictor** [comment]
ssh →proxy→XrayR        it will disconnect when no action in several mins 
ssh →proxy→other apps（like soga）it always keep connect

**Comment by ggfvictor** [comment]
> > I can reproduce the issue as I've been plagued by this. It's definitely not an ssh configuration issue, as ssh doesn't get interrupted when I connect through another VPS, or when I'm on a good local network not connected through a proxy. I think it's a proxy configuration issue, but I haven't pinpointed where the configuration is wrong.
> > 我能复现该问题，因为我一直被这个困扰。这绝对不是ssh配置问题，因为当我通过别的VPS连接时，或在本地网络良好不通过代理连接时，SSH不会被中断。我认为是代理配置的问题，但是我并没有定位到是哪里配置出现了问题。
> 
> 我也被这个问题困扰了将近一年 买了各种线路都不行，目前算是临时解决了，v2b只下发 后端手搓

v2b似乎只有下发吧   不然应该是什么呢   麻烦解释的通俗一点 感谢

**Comment by thank243** [comment]
> ssh →proxy→XrayR        it will disconnect when no action in several mins 
> ssh →proxy→other apps（like soga）it always keep connect 
> 

no logs?

**Comment by thank243** [comment]
> > > ssh →proxy→XrayR        it will disconnect when no action in several mins
> > > ssh →proxy→other apps（like soga）it always keep connect
> > 
> > 
> > no logs?
> 
> Dec 07 07:00:14 GreenCloud.1669385429 XrayR[884]: 2022/12/07 07:00:14 [Info] [1167397658] common/mux: received request for tcp:154.3.32.243:22 Dec 07 07:00:14 GreenCloud.1669385429 XrayR[884]: 2022/12/07 07:00:14 [Info] [1167397658] rayR/app/mydispatcher: default route for tcp:154.3.32.243:22 Dec 07 07:00:14 GreenCloud.1669385429 XrayR[884]: 2022/12/07 07:00:14 [Info] [1167397658] proxy/freedom: opening connection to tcp:154.3.32.243:22 Dec 07 07:00:14 GreenCloud.1669385429 XrayR[884]: 2022/12/07 07:00:14 [Info] [1167397658] transport/internet/tcp: dialing TCP to tcp:154.3.32.243:22 Dec 07 07:00:14 GreenCloud.1669385429 XrayR[884]: 2022/12/07 07:00:14 [Debug] transport/internet: dialing to tcp:154.3.32.243:22

Do you have completed logs? Combine server and client.

**Comment by blackshot-zard** [comment]
> 

就是在v2b上面添加节点，但是不用xrayr做后端，直接用xray手搓，密码就用v2b下发的哪个密码，类型那些也一样，订阅就能用

**Comment by blackshot-zard** [comment]
> ssh →proxy→XrayR it will disconnect when no action in several mins ssh →proxy→other apps（like soga）it always keep connect

原来soga可以，好久没用了 这个交叉测试我没做

**Comment by blackshot-zard** [comment]
> > > I can reproduce the issue as I've been plagued by this. It's definitely not an ssh configuration issue, as ssh doesn't get interrupted when I connect through another VPS, or when I'm on a good local network not connected through a proxy. I think it's a proxy configuration issue, but I haven't pinpointed where the configuration is wrong.
> > > 我能复现该问题，因为我一直被这个困扰。这绝对不是ssh配置问题，因为当我通过别的VPS连接时，或在本地网络良好不通过代理连接时，SSH不会被中断。我认为是代理配置的问题，但是我并没有定位到是哪里配置出现了问题。
> > 
> > 
> > 我也被这个问题困扰了将近一年 买了各种线路都不行，目前算是临时解决了，v2b只下发 后端手搓
> 
> v2b似乎只有下发吧 不然应该是什么呢 麻烦解释的通俗一点 感谢

我朋友用docker部署没这个问题

**Comment by ggfvictor** [comment]
> > ssh →proxy→XrayR it will disconnect when no action in several mins ssh →proxy→other apps（like soga）it always keep connect
> 
> 原来soga可以，好久没用了 这个交叉测试我没做

我昨晚测试过docker  仍然有问题

**Comment by blackshot-zard** [comment]
> > > ssh →proxy→XrayR it will disconnect when no action in several mins ssh →proxy→other apps（like soga）it always keep connect
> > 
> > 
> > 原来soga可以，好久没用了 这个交叉测试我没做
> 
> 我昨晚测试过docker 仍然有问题

新的交叉测试
同一个ssh服务器 同样的网络环境 同样的梯子 用XrayRdocker部署的
电脑A不会断线 电脑B会断线
电脑B换同同一个梯子用xray手搓部署，不会断
见鬼了我日

**Comment by ggfvictor** [comment]
> > > > ssh →proxy→XrayR it will disconnect when no action in several mins ssh →proxy→other apps（like soga）it always keep connect
> > > 
> > > 
> > > 原来soga可以，好久没用了 这个交叉测试我没做
> > 
> > 
> > 我昨晚测试过docker 仍然有问题
> 
> 新的交叉测试 同一个ssh服务器 同样的网络环境一台pc一台笔记本 同样的梯子 用XrayRdocker部署的 电脑A不会断线 电脑B会断线 电脑B换同同一个梯子用xray手搓部署，不会断 见鬼了我日 都是Termius且都设置了超时60s

别纠结了 我已经用soga替代了，soga没有这个问题，我没有这么多精力浪费在这种事情上。作者能解决这个问题更好，不能解决也随意吧。

**Comment by blackshot-zard** [comment]
> > > > > ssh →proxy→XrayR it will disconnect when no action in several mins ssh →proxy→other apps（like soga）it always keep connect
> > > > 
> > > > 
> > > > 原来soga可以，好久没用了 这个交叉测试我没做
> > > 
> > > 
> > > 我昨晚测试过docker 仍然有问题
> > 
> > 
> > 新的交叉测试 同一个ssh服务器 同样的网络环境一台pc一台笔记本 同样的梯子 用XrayRdocker部署的 电脑A不会断线 电脑B会断线 电脑B换同同一个梯子用xray手搓部署，不会断 见鬼了我日 都是Termius且都设置了超时60s
> 
> 别纠结了 我已经用soga替代了，soga没有这个问题，我没有这么多精力浪费在这种事情上。作者能解决这个问题更好，不能解决也随意吧。

是的 我也是这么想的 有解决方案

**Comment by thank243** [comment]
> > > > > ssh →proxy→XrayR it will disconnect when no action in several mins ssh →proxy→other apps（like soga）it always keep connect
> > > > 
> > > > 
> > > > 原来soga可以，好久没用了 这个交叉测试我没做
> > > 
> > > 
> > > 我昨晚测试过docker 仍然有问题
> > 
> > 新的交叉测试 同一个ssh服务器 同样的网络环境一台pc一台笔记本 同样的梯子 用XrayRdocker部署的 电脑A不会断线 电脑B会断线 电脑B换同同一个梯子用xray手搓部署，不会断 见鬼了我日 都是Termius且都设置了超时60s
> 
> 别纠结了 我已经用soga替代了，soga没有这个问题，我没有这么多精力浪费在这种事情上。作者能解决这个问题更好，不能解决也随意吧。

I cannot recall this problems. Can you provide server and client debug logs？

**Comment by blackshot-zard** [comment]
破案了
服务端源码是ConnectionConfig:
默认的配置文是件ConnetionConfig:
少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30

**Comment by ggfvictor** [comment]
> 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30

怪不得我怎么改这个参数不都不生效。。。

**Comment by thank243** [comment]
> 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30

Before submit issue, Please read release document. 
https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6

**Comment by blackshot-zard** [comment]
> > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> 
> Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6

好的 不过配置文件一般来说是不会去动 所以没发现这个也正常

**Comment by ggfvictor** [comment]
> > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > 
> > 
> > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> 
> 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常

什么意思 需要手动纠正？

**Comment by blackshot-zard** [comment]
> > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > 
> > > 
> > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > 
> > 
> > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> 
> 什么意思 需要手动纠正？

是的 你把配置文件哪里的c补全就行了 这个bug就解决了

**Comment by ggfvictor** [comment]
> > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > 
> > > > 
> > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > 
> > > 
> > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > 
> > 
> > 什么意思 需要手动纠正？
> 
> 是的 你把配置文件哪里的c补全就行了 这个bug就解决了

我以为这是他修复的bug，还在想为什么修复了还存在这个bug。。。

**Comment by ggfvictor** [comment]
> > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > 
> > > > 
> > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > 
> > > 
> > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > 
> > 
> > 什么意思 需要手动纠正？
> 
> 是的 你把配置文件哪里的c补全就行了 这个bug就解决了

所以需要设置成0就可以永不断开吗？

**Comment by blackshot-zard** [comment]
> > > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > > 
> > > > > 
> > > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > > 
> > > > 
> > > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > > 
> > > 
> > > 什么意思 需要手动纠正？
> > 
> > 
> > 是的 你把配置文件哪里的c补全就行了 这个bug就解决了
> 
> 所以需要设置成0就可以永不断开吗？

是咧

**Comment by ggfvictor** [comment]
> > > > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > > > 
> > > > > > 
> > > > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > > > 
> > > > > 
> > > > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > > > 
> > > > 
> > > > 什么意思 需要手动纠正？
> > > 
> > > 
> > > 是的 你把配置文件哪里的c补全就行了 这个bug就解决了
> > 
> > 
> > 所以需要设置成0就可以永不断开吗？
> 
> 是咧

我实在不明白他为什么要把已经知道的bug写在fix里面，让人误以为是他修复的bug。

**Comment by ggfvictor** [comment]
> > > > > > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > > > > > 
> > > > > > > 
> > > > > > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > > > > > 
> > > > > > 
> > > > > > 什么意思 需要手动纠正？
> > > > > 
> > > > > 
> > > > > 是的 你把配置文件哪里的c补全就行了 这个bug就解决了
> > > > 
> > > > 
> > > > 所以需要设置成0就可以永不断开吗？
> > > 
> > > 
> > > 是咧
> > 
> > 
> > 我实在不明白他为什么要把已经知道的bug写在fix里面，让人误以为是他修复的bug。
> 
> 好啦好啦 只是我们不看版本更新才会这样 他在上面也说了，只不过我们没发现少了个c 而是直接去改后面的数字 我还找人看了源码捣鼓半天 果然使用说明是没啥人看的 哈哈

可是我用最新版本还是有断线这个问题

**Comment by ggfvictor** [comment]
> > > > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > > > 
> > > > > > 
> > > > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > > > 
> > > > > 
> > > > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > > > 
> > > > 
> > > > 什么意思 需要手动纠正？
> > > 
> > > 
> > > 是的 你把配置文件哪里的c补全就行了 这个bug就解决了
> > 
> > 
> > 所以需要设置成0就可以永不断开吗？
> 
> 是咧

@blackshot-zard  你误人子弟啊  ConnIdle: 0 # Connection idle time limit, Second   这样永远连不上了

**Comment by blackshot-zard** [comment]
> > > > > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > > > > 
> > > > > > > 
> > > > > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > > > > 
> > > > > > 
> > > > > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > > > > 
> > > > > 
> > > > > 什么意思 需要手动纠正？
> > > > 
> > > > 
> > > > 是的 你把配置文件哪里的c补全就行了 这个bug就解决了
> > > 
> > > 
> > > 所以需要设置成0就可以永不断开吗？
> > 
> > 
> > 是咧
> 
> @blackshot-zard 你误人子弟啊 ConnIdle: 0 # Connection idle time limit, Second 这样永远连不上了

...是吗 那设置成300

**Comment by ggfvictor** [comment]
> > > > > > > > > 破案了 服务端源码是ConnectionConfig: 默认生成的配置文是件ConnetionConfig: 少了个c导致这一块配置变成了默认值所以ConnIdle: 一直是30
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Before submit issue, Please read release document. https://github.com/XrayR-project/XrayR/releases/tag/v0.8.6
> > > > > > > 
> > > > > > > 
> > > > > > > 好的 不过配置文件一般来说是不会去动 所以没发现这个也正常
> > > > > > 
> > > > > > 
> > > > > > 什么意思 需要手动纠正？
> > > > > 
> > > > > 
> > > > > 是的 你把配置文件哪里的c补全就行了 这个bug就解决了
> > > > 
> > > > 
> > > > 所以需要设置成0就可以永不断开吗？
> > > 
> > > 
> > > 是咧
> > 
> > 
> > @blackshot-zard 你误人子弟啊 ConnIdle: 0 # Connection idle time limit, Second 这样永远连不上了
> 
> ...是吗 那设置成300

同样配置下soga内存比xrayr占用少  而且有些配置还可以写的更简单
