### ISSUE TITLE
V2brod面板对接 trojan 协议时服务端日志出现rejected  proxy/trojan: not trojan protocol

### ISSUE THREAD

**Issue by chouchjel** [XrayR-project/XrayR#143]
求大佬帮忙
这个问题困扰好久了，改端口、重装系统、或者改域名可以联通，但是到第二天百分百就连接失败了超时，IP没被墙 端口正常 防火墙没开，换成V2ray+tls协议也是这样子的问题，我的其他机器就没这个问题，佛了这台机器是dedipath 买的
Dec 07 00:40:20 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:20 [Warning] core: Xray 1.6.3 started
Dec 07 00:40:22 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:22 [Trojan: 2] Added 12 new users
Dec 07 00:40:22 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:22 [Trojan: 2] Start monitor node status
Dec 07 00:40:22 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:22 [Trojan: 2] Start report node status
Dec 07 00:40:38 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:38 192.241.212.53:43862 rejected  proxy/trojan: not trojan protocol
Dec 07 00:41:24 linux.c74e25.com XrayR[128567]: 2022/12/07 00:41:24 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal.
Dec 07 00:41:24 linux.c74e25.com XrayR[128567]: 2022/12/07 00:41:24 [Trojan: 2] 0 user deleted, 0 user added
Dec 07 00:42:26 linux.c74e25.com XrayR[128567]: 2022/12/07 00:42:26 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal.
Dec 07 00:42:26 linux.c74e25.com XrayR[128567]: 2022/12/07 00:42:26 [Trojan: 2] 0 user deleted, 0 user added
Dec 07 00:43:27 linux.c74e25.com XrayR[128567]: 2022/12/07 00:43:27 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal.
Dec 07 00:43:27 linux.c74e25.com XrayR[128567]: 2022/12/07 00:43:27 [Trojan: 2] 0 user deleted, 0 user added
Dec 07 00:44:07 linux.c74e25.com XrayR[128567]: 2022/12/07 00:44:07 192.241.192.251:41918 rejected  proxy/trojan: not trojan protocol
Dec 07 00:44:29 linux.c74e25.com XrayR[128567]: 2022/12/07 00:44:29 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal.
Dec 07 00:44:29 linux.c74e25.com XrayR[128567]: 2022/12/07 00:44:29 [Trojan: 2] 0 user deleted, 0 user added

![image](https://user-images.githubusercontent.com/63604074/206099053-8897f193-d646-4150-ac31-f305ea18491f.png)
![image](https://user-images.githubusercontent.com/63604074/206098958-c0dc6305-c562-4b9e-9561-a4debe4bf6b3.png)

**Comment by thank243** [comment]
The IP have been aduited. Change IDC.

**Comment by chouchjel** [comment]
> 求大佬帮忙 这个问题困扰好久了，改端口、重装系统、或者改域名可以联通，但是到第二天百分百就连接失败了超时，IP没被墙 端口正常 防火墙没开，换成V2ray+tls协议也是这样子的问题，我的其他机器就没这个问题，佛了这台机器是dedipath 买的 Dec 07 00:40:20 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:20 [Warning] core: Xray 1.6.3 started Dec 07 00:40:22 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:22 [Trojan: 2] Added 12 new users Dec 07 00:40:22 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:22 [Trojan: 2] Start monitor node status Dec 07 00:40:22 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:22 [Trojan: 2] Start report node status Dec 07 00:40:38 linux.c74e25.com XrayR[128567]: 2022/12/07 00:40:38 192.241.212.53:43862 rejected proxy/trojan: not trojan protocol Dec 07 00:41:24 linux.c74e25.com XrayR[128567]: 2022/12/07 00:41:24 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal. Dec 07 00:41:24 linux.c74e25.com XrayR[128567]: 2022/12/07 00:41:24 [Trojan: 2] 0 user deleted, 0 user added Dec 07 00:42:26 linux.c74e25.com XrayR[128567]: 2022/12/07 00:42:26 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal. Dec 07 00:42:26 linux.c74e25.com XrayR[128567]: 2022/12/07 00:42:26 [Trojan: 2] 0 user deleted, 0 user added Dec 07 00:43:27 linux.c74e25.com XrayR[128567]: 2022/12/07 00:43:27 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal. Dec 07 00:43:27 linux.c74e25.com XrayR[128567]: 2022/12/07 00:43:27 [Trojan: 2] 0 user deleted, 0 user added Dec 07 00:44:07 linux.c74e25.com XrayR[128567]: 2022/12/07 00:44:07 192.241.192.251:41918 rejected proxy/trojan: not trojan protocol Dec 07 00:44:29 linux.c74e25.com XrayR[128567]: 2022/12/07 00:44:29 [us2-yr5hf2juvnsjp.jel.pw] The certificate expires in 89 days, the number of days defined to perform the renewal is 30: no renewal. Dec 07 00:44:29 linux.c74e25.com XrayR[128567]: 2022/12/07 00:44:29 [Trojan: 2] 0 user deleted, 0 user added
> 
已解决，佛了 就22端口没事，能登vps上去以为其他都没事，没想到其他端口全世界的网都访问不了太秀了
