### ISSUE TITLE
dns文件无法正确理解

### ISSUE THREAD

**Issue by camghaitan** [XrayR-project/XrayR#144]
Mar 20 09:49:42 VM21514 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 12335.
Mar 20 09:49:42 VM21514 systemd[1]: Stopped XrayR Service.
Mar 20 09:49:42 VM21514 systemd[1]: Started XrayR Service.
Mar 20 09:49:42 VM21514 XrayR[431337]: XrayR 0.7.6 (A Xray backend that supports many panels)
Mar 20 09:49:42 VM21514 XrayR[431337]: 2022/03/20 09:49:42 Start the panel..
Mar 20 09:49:42 VM21514 XrayR[431337]: 2022/03/20 09:49:42 Failed to understand dns.json, Please check: https://xtls.github.io/config/base/outbounds/ for help: infra/conf: 0 Trojan server configured.
Mar 20 09:49:42 VM21514 XrayR[431337]: panic: Failed to understand dns.json, Please check: https://xtls.github.io/config/base/outbounds/ for help: infra/conf: 0 Trojan server configured.
Mar 20 09:49:42 VM21514 XrayR[431337]: goroutine 1 [running]:
Mar 20 09:49:42 VM21514 XrayR[431337]: log.Panicf({0x20ef314, 0xc000f39b28}, {0xc000f39c18, 0x1aa5760, 0xc00067f140})
Mar 20 09:49:42 VM21514 XrayR[431337]:         log/log.go:361 +0x67
Mar 20 09:49:42 VM21514 XrayR[431337]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc000547ea0, 0xc000179d50)
Mar 20 09:49:42 VM21514 XrayR[431337]:         github.com/XrayR-project/XrayR/panel/panel.go:118 +0xb3b
Mar 20 09:49:42 VM21514 XrayR[431337]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0000b6b00)
Mar 20 09:49:42 VM21514 XrayR[431337]:         github.com/XrayR-project/XrayR/panel/panel.go:157 +0xe9
Mar 20 09:49:42 VM21514 XrayR[431337]: main.main()
Mar 20 09:49:42 VM21514 XrayR[431337]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Mar 20 09:49:42 VM21514 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 20 09:49:42 VM21514 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by camghaitan** [comment]
这是log信息，我的dns文件我看了一下文档，但是不知道哪里出了问题

**Comment by camghaitan** [comment]
{
    "servers": [
        "localhost",
        "114.114.114.114",
        "8.8.8.8"
    ],
    "tag": "dns_inbound"
}

**Comment by RManLuo** [comment]
这里的提升信息存在bug，有可能是custom_outbound存在问题，下个版本会修复此提升的bug。

**Comment by camghaitan** [comment]
好的，谢谢
