### ISSUE TITLE
端口占用问题

### ISSUE THREAD

**Issue by camghaitan** [XrayR-project/XrayR#145]
Mar 21 20:56:38 VM21514 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 24669.
Mar 21 20:56:38 VM21514 systemd[1]: Stopped XrayR Service.
Mar 21 20:56:38 VM21514 systemd[1]: Started XrayR Service.
Mar 21 20:56:38 VM21514 XrayR[860507]: XrayR 0.7.6 (A Xray backend that supports many panels)
Mar 21 20:56:38 VM21514 XrayR[860507]: 2022/03/21 20:56:38 Start the panel..
Mar 21 20:56:38 VM21514 XrayR[860507]: 2022/03/21 20:56:38 Xray Core Version: 1.5.2
Mar 21 20:56:38 VM21514 XrayR[860507]: 2022/03/21 20:56:38 app/proxyman/inbound: failed to listen TCP on 443 > transport/internet: failed to listen on address: 127.0.0.1:443 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:443 > listen tcp 127.0.0.1:443: bind: address already in use
Mar 21 20:56:38 VM21514 XrayR[860507]: panic: app/proxyman/inbound: failed to listen TCP on 443 > transport/internet: failed to listen on address: 127.0.0.1:443 > transport/internet/tcp: failed to listen TCP on 127.0.0.1:443 > listen tcp 127.0.0.1:443: bind: address already in use
Mar 21 20:56:38 VM21514 XrayR[860507]: goroutine 1 [running]:
Mar 21 20:56:38 VM21514 XrayR[860507]: log.Panic({0xc000547d98, 0xc00029d2b0, 0x10})
Mar 21 20:56:38 VM21514 XrayR[860507]:         log/log.go:354 +0x65
Mar 21 20:56:38 VM21514 XrayR[860507]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0002006c0)
Mar 21 20:56:38 VM21514 XrayR[860507]:         github.com/XrayR-project/XrayR/service/controller/controller.go:53 +0x18e
Mar 21 20:56:38 VM21514 XrayR[860507]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0004fef80)
Mar 21 20:56:38 VM21514 XrayR[860507]:         github.com/XrayR-project/XrayR/panel/panel.go:192 +0x543
Mar 21 20:56:38 VM21514 XrayR[860507]: main.main()
Mar 21 20:56:38 VM21514 XrayR[860507]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Mar 21 20:56:38 VM21514 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 21 20:56:38 VM21514 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by camghaitan** [comment]
这是输出日志，问题是端口被占用了，因为我是按照教程配合Nginx一起使用的，443端口被Nginx拿去监听了，但是配置文件上我也设置代理了，不太理解这个端口占用是怎么回事
![image](https://user-images.githubusercontent.com/23808071/159267717-47fc81df-5132-49a2-9283-3cfde07de6d5.png)
![image](https://user-images.githubusercontent.com/23808071/159267799-ff5054ac-2e53-48d4-a609-a4fcb00878bc.png)

**Comment by camghaitan** [comment]
![image](https://user-images.githubusercontent.com/23808071/159268769-788cfcdf-5fc3-4433-ae82-7c6d126880d4.png)
还有请问一下这个网站前端监听端口一致是什么意思呢，是指类似于80端口那种监听端口吗

**Comment by camghaitan** [comment]
> 

知道怎么去修正，但是不太清楚是怎么和Nginx的SSL端口产生了冲突

**Comment by thank243** [comment]
不如curl下config下发地址看看到底咋回事。

**Comment by camghaitan** [comment]
> 不如curl下config下发地址看看到底咋自己。

好的感谢
