### ISSUE TITLE
关于设备数限制的一个建议

### ISSUE THREAD

**Issue by sleeeeeeepa** [XrayR-project/XrayR#146]
目前设备数限制是可用的，因为一些原因国内大多使用者需要通过中转连接到落地机，导致redis获取的ip为中转的ip无法透传真正的源ip

目前所知Realm等一些中转方式可以透传源IP，但开启透传以后无法使用XrayR，原因未知。（需要适配解析？）

如果有获取源IP方式希望作者答疑！谢谢！

**Comment by sleeeeeeepa** [comment]
以Realm为例再加上send-proxy

**Comment by sleeeeeeepa** [comment]
以Realm为例
在加上send-proxy后Xray日志报错
[4215949620] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > EOF

**Comment by thank243** [comment]
ref: XTLS acceptProxyProtocol
