### ISSUE TITLE
20 day ago we had a dns api change

### ISSUE THREAD

**Issue by hadi-dindar** [XrayR-project/XrayR#147]
20 day agoi we had dns api change
and lego dns updated that. 
arvancloud.com domain and dns changed to arvancloud.ir
lego updated that in this link
https://github.com/go-acme/lego/pull/1771/commits/a2ce846a7d4b0e67380a604fd2843fc059934f9b
but not work in xrayR yet. 
it show me https://napi.arvancloud.com" acme erorr 
 check it

**Comment by thank243** [comment]
Waiting for version 0.8.7 a few days later.
