### ISSUE TITLE
无法启动xrayr

### ISSUE THREAD

**Issue by harrison-guo-chn** [XrayR-project/XrayR#148]
修改config.yml之后无法启动，
安装最后一行疑似报错的内容
![image](https://user-images.githubusercontent.com/58265745/159852292-02c8a2b3-8408-442c-a663-b61c12b8d57c.png)
状态里面疑似错误的报错
![image](https://user-images.githubusercontent.com/58265745/159852362-9f8a70f9-2c6d-43a8-a0fb-19c1e9f75490.png)

**Comment by borislee0227** [comment]
@harrison-guo-chn
