### ISSUE TITLE
0.8.7 when use newv2board it shows some bug

### ISSUE THREAD

**Issue by ggfvictor** [XrayR-project/XrayR#149]
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: 2022/12/08 07:19:28 Panel Start fialed: request https://v2.hicat.net/api/v1/server/UniProxy/config failed: {
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: }, %!s(<nil>)
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: panic: Panel Start fialed: request https://v2.hicat.net/api/v1/server/UniProxy/config failed: {
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: }, %!s(<nil>)
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: goroutine 1 [running]:
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: log.Panicf({0x317d042?, 0x0?}, {0xc000861e80?, 0xc00011d780?, 0xc00022fc10?})
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: log/log.go:395 +0x67
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00033bf80)
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: github.com/XrayR-project/XrayR/panel/panel.go:204 +0x5bc
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: main.main()
Dec 08 07:19:28 GreenCloud.1669385429 XrayR[510]: github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Dec 08 07:19:28 GreenCloud.1669385429 systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 08 07:19:28 GreenCloud.1669385429 systemd[1]: Unit XrayR.service entered failed state.
Dec 08 07:19:28 GreenCloud.1669385429 systemd[1]: XrayR.service failed.
^C

**Comment by ggfvictor** [comment]
my v2board version is 1.6.1 the latest

**Comment by ggfvictor** [comment]
@blackshot-zard 来测试一下

**Comment by blackshot-zard** [comment]
> @blackshot-zard 来测试一下

我找人看了xrayr的源代码 他说有可能出在限速模块，因为限速模块一直在重启，虽然时间很短，不过对shh是致命打击
如果大佬把限速模块设置为不限速就不重启的话就没这个毛病

**Comment by ggfvictor** [comment]
> 

有没有tg，交流一下

**Comment by blackshot-zard** [comment]
> > @blackshot-zard
> 
> 有没有tg，交流一下

托人找到bug了 就是那个 ConnIdle: 30 # Connection idle time limit, Second
这个值在30以下的时候甚至是0的时候也会被改成30
导致的断线

**Comment by ggfvictor** [comment]
> > > @blackshot-zard
> > 
> > 
> > 有没有tg，交流一下
> 
> 托人找到bug了 就是那个 ConnIdle: 30 # Connection idle time limit, Second 这个值在30以下的时候甚至是0的时候也会被改成30 导致的断线

我这个bug反馈的是0.8.7 newv2board 起不来问题。。。

**Comment by blackshot-zard** [comment]
> > > > @blackshot-zard
> > > 
> > > 
> > > 有没有tg，交流一下
> > 
> > 
> > 托人找到bug了 就是那个 ConnIdle: 30 # Connection idle time limit, Second 这个值在30以下的时候甚至是0的时候也会被改成30 导致的断线
> 
> 我这个bug反馈的是0.8.7 newv2board 起不来问题。。。

哦哦 你这个要大佬才看得懂 我不懂代码 只会发现bug 哈哈

**Comment by ggfvictor** [comment]
> > > > > @blackshot-zard
> > > > 
> > > > 
> > > > 有没有tg，交流一下
> > > 
> > > 
> > > 托人找到bug了 就是那个 ConnIdle: 30 # Connection idle time limit, Second 这个值在30以下的时候甚至是0的时候也会被改成30 导致的断线
> > 
> > 
> > 我这个bug反馈的是0.8.7 newv2board 起不来问题。。。
> 
> 哦哦 你这个要大佬才看得懂 我不懂代码 只会发现bug 哈哈

你测试一下0.8.7  newv2board能起来吗

**Comment by thank243** [comment]
The newV2board support v2board verison >= 1.6.2

**Comment by ggfvictor** [comment]
> The newV2board support v2board verison >= 1.6.2

XrayR v0.8.7 [Latest](https://github.com/XrayR-project/XrayR/releases/latest)
@[pocketW](https://github.com/pocketW) pocketW released this 4 hours ago
[ v0.8.7](https://github.com/XrayR-project/XrayR/tree/v0.8.7)
https://github.com/XrayR-project/XrayR/commit/0bea22e1454ae489ae03865c9dbca0a588700115
XrayR v0.8.7
Feat
重构全局设备限制功能，现在能直接读取远程面板下发的设备限制数量，并且采用缓存机制，降低延迟。请查看[配置文档](https://xrayr-project.github.io/XrayR-doc/gong-neng-shuo-ming/devicelimit.html)修改配置 @thank243 @pocketW
支持V2board最新API。
v2board 版本 >= [1.6.1](https://github.com/v2board/v2board/releases/tag/1.6.1)请选择 PanelType: "NewV2board"。其他旧版本选择 PanelType: "V2board"，注意老版本API将于 2023.6.1后移除。

**Comment by ggfvictor** [comment]
> Its a typo. v1.6.2 add the uniporxy feat.

got it!

**Comment by ggfvictor** [comment]
> Its a typo. v1.6.2 add the uniporxy feat.

btw where is 1.6.2  only see 1.6.1  https://github.com/v2board/v2board/releases

**Comment by ggfvictor** [comment]
> Its a typo. v1.6.2 add the uniporxy feat.

do u mean dev branch?
