### ISSUE TITLE
对接v2board不上报流量

### ISSUE THREAD

**Issue by Timolop233** [XrayR-project/XrayR#149]
xrayr对接v2board后xrayr不会对面板上报流量使用情况

**Comment by thank243** [comment]
debug日志。

**Comment by Timolop233** [comment]
debug显示这个是出现最多的

**Comment by Timolop233** [comment]
debug模式下查看日志，显示最多的是这个
无法处理出站流量

**Comment by ysir66** [comment]
> debug模式下查看日志，显示最多的是这个
> 无法处理出站流量

这个怎么解决呢

**Comment by Timolop233** [comment]
啊，经过两天排查
我才发现是我v2b面板的队列没完全启动
是我的问题对不起

**Comment by olperson** [comment]
@Timolop233 好，很有精神
