### ISSUE TITLE
添加强制关闭ssl证书的建议

### ISSUE THREAD

**Issue by pudding1111** [XrayR-project/XrayR#15]
ws tls nginx中，后端端口非443，建议添加soga参数https://soga.vaxilu.com/docker/soga-config中的force_close_ssl参数，用来支持ws tls nginx

**Comment by AnniBear** [comment]
https://crackair.gitbook.io/xrayr-project/gong-neng-shuo-ming/cert
CertMode中选择“none”即可强制关闭tls设置，交由nginx或者caddy处理。

**Comment by pudding1111** [comment]
谢老哥指点，惯性思维，缺乏思考了
