### ISSUE TITLE
dns解析优先问题

### ISSUE THREAD

**Issue by ggfvictor** [XrayR-project/XrayR#150]
在打开了自定义dns解析并正确配置后
并启用ipv6优先出口后
在dns配置中使用Ipv4 dns解锁流媒体不起作用（将优先出口改为0.0.0.0 可以正常解锁）
通过访问网站发现优先通过ipv6访问没有问题，但是流媒体解锁却不使用设定的dns了

请问能否让流媒体走预先设定的dns进行解锁，同时不影响其他网页默认通过ipv6访问呢

**Comment by thank243** [comment]
There is no magic can use ipv6 address to connect ipv4 address.

**Comment by ggfvictor** [comment]
> There is no magic can use ipv6 address to connect ipv4 address.

in fact  open custom_outbound & route could deal with it  just thinking
