### ISSUE TITLE
V2B面板还是用不了ss2022

### ISSUE THREAD

**Issue by ckaak** [XrayR-project/XrayR#151]
XrayR 1.8.7 最新的版本
Xray 1.6.5
v2board 1.6.2 dev ，用的NewV2board对接的，找不到proxy.UserManager模块。

需要手动合并这个代码吗？ https://github.com/v2board/v2board/pull/549

XrayR[3969]:  Panel Start fialed: handler Shadowsocks_0.0.0.0_443 has not implemented proxy.UserManager
XrayR[3969]: panic: Panel Start fialed: handler Shadowsocks_0.0.0.0_443 has not implemented proxy.UserManager
XrayR[3969]: goroutine 1 [running]:
XrayR[3969]: log.Panicf({0x317d042?, 0x0?}, {0xc000cfbe80?, 0xc0002e8580?, 0xc0004c5bd0?})
XrayR[3969]:         log/log.go:395 +0x67
XrayR[3969]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000940540)
XrayR[3969]:         github.com/XrayR-project/XrayR/panel/panel.go:204 +0x5bc
XrayR[3969]: main.main()
XrayR[3969]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: XrayR.service: Failed with result 'exit-code'.
 systemd[1]: XrayR.service: Service hold-off time over, scheduling restart.
systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 25.

**Comment by thank243** [comment]
Xray-core didn't release the patch of ss2022. You can build xrayr as yourself. And there is no panels support send ss2022 configuration to client, you must setting it at your client.

**Comment by ckaak** [comment]
> Xray-core didn't release the patch of ss2022. You can use go work to build xrayr as yourself. And there is no panels support send ss2022 configuration to client, you must setting it at your client.

我看https://github.com/XrayR-project/XrayR/releases/tag/v0.8.7 这个昨天发布的版本，下面写了完成ss2022适配。

**Comment by ckaak** [comment]
好像明白了，看了xray内核的代码没有同步最新的修改。我去编译看看
