### ISSUE TITLE
arvanclou api

### ISSUE THREAD

**Issue by hadi-dindar** [XrayR-project/XrayR#152]
arvancloud dns provider changed to arvancloud.ir
and this is updated in lego
but not work yet in xrayr
error message :  
dns-records": dial tcp: lookup napi.arvancloud.com on 8.8.8.8:53: no such host

dns looking for arvancloud.com. but it is arvancloud.ir

**Comment by thank243** [comment]
Change domain provider or wait lego release the latest version.

**Comment by hadi-dindar** [comment]
https://github.com/go-acme/lego/pull/1771/commits/a2ce846a7d4b0e67380a604fd2843fc059934f9b
they fix it, but not work yet
