### ISSUE TITLE
打开本地审计文件报错

### ISSUE THREAD

**Issue by kn-z** [XrayR-project/XrayR#154]
![image](https://user-images.githubusercontent.com/59436232/160554572-24eb6f9f-c9b3-47bc-bdb9-2dbdd69e0ade.png)
启动时报错本地审计文件不存在，cat了一下文件的确是存在的，尝试过相对路径也是同样的报错

**Comment by crackair** [comment]
@kn-z 填写docker内文件路径

**Comment by kn-z** [comment]
谢谢，知道错误在哪了
