### ISSUE TITLE
启动报错 配置文件已经修改好了还是这样

### ISSUE THREAD

**Issue by xkatld** [XrayR-project/XrayR#157]
2022/04/02 05:22:15.514684 ERROR RESTY Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused, Attempt 1
2022/04/02 05:22:15.615439 ERROR RESTY Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused, Attempt 2
2022/04/02 05:22:15.811632 ERROR RESTY Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused, Attempt 3
2022/04/02 05:22:16.135349 ERROR RESTY Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused, Attempt 4
2022/04/02 05:22:16 Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused
2022/04/02 05:22:16 Panel Start fialed: request http://127.0.0.1:667/mod_mu/nodes/41/info failed: Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused
panic: Panel Start fialed: request http://127.0.0.1:667/mod_mu/nodes/41/info failed: Get "http://127.0.0.1:667/mod_mu/nodes/41/info?key=123&muKey=123": dial tcp 127.0.0.1:667: connect: connection refused

**Comment by thank243** [comment]
如果脱敏了，去找面板问题。如果没有脱敏，请关闭issue
