### ISSUE TITLE
部署后端的时候不能直接使用docker run指定参数？ 

### ISSUE THREAD

**Issue by JusufUs** [XrayR-project/XrayR#16]
部署后端的时候不能直接使用docker run指定参数？ 必须使用config.yml来配置吗

例如这样
docker run --restart=on-failure --name soga -d \
-v /etc/soga/:/etc/soga/ --network host \
-e type=sspanel-uim \
-e server_type=v2ray \
-e api=webapi \
-e webapi_url=https://xxx.com/ \
-e webapi_key=asdasd \
-e node_id=1 \
-e cert_domain=aaaa.com \
-e cert_mode=http \
sprov065/soga

感谢开发者的无私奉献

**Comment by crackair** [comment]
暂不支持此功能
