### ISSUE TITLE
升级V2board到1.71后，无法使用xrayr

### ISSUE THREAD

**Issue by Amone0012** [XrayR-project/XrayR#165]
升级V2board到1.71后
0.82版本xrayr无法启动，
0.88版本状态为
Dec 16 19:37:48 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:48 172.104.39.90:62700 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62700: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:49 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:49 172.104.39.90:62782 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:49 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:49 172.104.39.90:62714 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62714: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:49 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:49 172.104.39.90:62716 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62716: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:49 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:49 172.104.39.90:62720 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62720: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:49 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:49 172.104.39.90:62728 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62728: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:50 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:50 172.104.39.90:62730 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62730: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:50 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:50 172.104.39.90:62814 rejected  common/drain: common/drain: unable to drain connection > EOF > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:50 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:50 172.104.39.90:62740 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62740: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found
Dec 16 19:37:51 139-162-25-118.ip.linodeusercontent.com XrayR[24670]: 2022/12/16 19:37:51 172.104.39.90:62754 rejected  common/drain: common/drain: unable to drain connection > read tcp 139.162.25.118:443->172.104.39.90:62754: i/o timeout > proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found

与更新面板前设置无区别，面板节点指示变黄，但不通测试

**Comment by thank243** [comment]
Panel type use NewV2board

**Comment by Amone0012** [comment]
使用NewV2board后得到日志，还是不通


Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: XrayR 0.8.8 (A Xray backend that supports many panels)
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 Start the panel..
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 Xray Core Version: 1.6.6
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 [Debug] app/log: Logger started
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 [Info] app/dns: DNS: created localhost client
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 [Warning] core: Xray 1.6.6 started
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:443
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:443
Dec 17 03:26:39 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:39 [Info] transport/internet/udp: listening UDP on 0.0.0.0:443
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: 2022/12/17 03:26:40 Panel Start fialed: request https://dddd.lol/api/v1/server/UniProxy/user failed: {
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: }, %!s(<nil>)
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: panic: Panel Start fialed: request https://xxxx.xx/api/v1/server/UniProxy/user failed: {
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: }, %!s(<nil>)
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: goroutine 1 [running]:
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: log.Panicf({0x31829b3?, 0x0?}, {0xc000e51e80?, 0xc00099ab80?, 0xc0004c5bb0?})
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]:         log/log.go:395 +0x67
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000940580)
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]:         github.com/XrayR-project/XrayR/panel/panel.go:204 +0x5bc
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]: main.main()
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com XrayR[449175]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 17 03:26:40 139-162-25-118.ip.linodeusercontent.com systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by thank243** [comment]
Confirm the config is properly setting in your panel.
