### ISSUE TITLE
Nginx Proxy Reverse Not Working With XrayR?

### ISSUE THREAD

**Issue by alirezashahrokhi** [XrayR-project/XrayR#166]
Hello to all dear professors, I am almost an amateur in the network and I thank you in advance for your guidance

I am considering, using a reverse proxy, to send requests from the primary server to a second server behind the cloudflare CDN
This is because Cloud Flare is not directly available to us

My questions:
1_ Both servers need to install NGINX? Or is it enough to install only on the primary server?
2_ Is TLS mandatory or not?
3_Is it a problem to use two subdomains for my two servers?
4_What port should I enter for the client to use in v2board? My guess is 443
And what port should I configure in the reverse proxy?

MY NGINX CONFIG IS:

user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile            on;
    tcp_nopush          on;
    tcp_nodelay         on;
    keepalive_timeout   65;
    types_hash_max_size 4096;
    include             /etc/nginx/mime.types;
    default_type        application/octet-stream;

    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80;
        listen [::]:80 default_server;
        server_name  _;
        root         /usr/share/nginx/html;

        include /etc/nginx/default.d/*.conf;

        error_page 404 /404.html;
        location = /404.html {
        }

        error_page 500 502 503 504 /50x.html;
        location = /50x.html {
        }
    }

# Settings for a TLS enabled server.

    server {
        listen       443 ssl http2;
        listen       [::]:443 ssl http2;
        server_name SUB.MYDOMAIN.COM www.SUB.MYDOMAIN.COM;
        root         /usr/share/nginx/html;

        ssl_certificate "/etc/letsencrypt/live/SUB.MYDOMAIN.COM/fullchain.pem";
        ssl_certificate_key "/etc/letsencrypt/live/SUB.MYDOMAIN.COM/privkey.pem";
        ssl_session_cache shared:SSL:1m;
        ssl_session_timeout  10m;
        ssl_ciphers HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
location /1378 {
                 proxy_redirect off;
                 proxy_pass http://SUB2.MYDOMAIN.COM;
                 proxy_http_version 1.1;
                 proxy_set_header Upgrade $http_upgrade;
                 proxy_set_header Connection "upgrade";
                 proxy_set_header Host $http_host;
                 proxy_set_header X-Real-IP $remote_addr;
                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}

`

**Comment by thank243** [comment]
You should confirm without nginx, The XR can work normally.
Ref: https://xrayr-project.github.io/XrayR-doc/dui-jie-v2board/v2board.html
