### ISSUE TITLE
how to add stream settings for custom inbounds?

### ISSUE THREAD

**Issue by alirezashahrokhi** [XrayR-project/XrayR#170]
hi dear freinds
i try to add my stream settings to config :
[
  {
    "listen": "0.0.0.0",
    "port": 1234,
    "protocol": "vmess",
    "settings": {
      "auth": "noauth",
      "accounts": [
        {
          "user": "my-username",
          "pass": "my-password"
        }
      ],
      "udp": false,
      "ip": "127.0.0.1",
      "userLevel": 0
    }
	"streamSettings": {
  "network": "ws",
  "wsSettings": {
    "path": "/1378"
  }
}
  }
]

but i get error when try to start xrayr
Dec 19 02:42:12 d13jhplu.vm systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 44.
Dec 19 02:42:12 d13jhplu.vm systemd[1]: Stopped XrayR Service.
Dec 19 02:42:12 d13jhplu.vm systemd[1]: Started XrayR Service.
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: XrayR 0.8.8 (A Xray backend that supports many panels)
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: 2022/12/19 02:42:12 Start the panel..
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: 2022/12/19 02:42:12 Failed to unmarshal Custom Inbound config: /etc/XrayR/custom_outbound.json
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: panic: Failed to unmarshal Custom Inbound config: /etc/XrayR/custom_outbound.json
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: goroutine 1 [running]:
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: log.Panicf({0x31cfbd3?, 0x1f?}, {0xc000933bf8?, 0x268bce0?, 0xc000011da0?})
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]:         log/log.go:395 +0x67
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc000933e80?, 0xc000182ee0)
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]:         github.com/XrayR-project/XrayR/panel/panel.go:95 +0x50e
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000952540)
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]:         github.com/XrayR-project/XrayR/panel/panel.go:161 +0xe9
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]: main.main()
Dec 19 02:42:12 d13jhplu.vm XrayR[2220]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Dec 19 02:42:12 d13jhplu.vm systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 19 02:42:12 d13jhplu.vm systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by thank243** [comment]
https://xtls.github.io/config/inbound.html
