### ISSUE TITLE
Xray启动后报unknown cipher method

### ISSUE THREAD

**Issue by jxjeff** [XrayR-project/XrayR#178]
Ubuntu20.04
V2board 1.6.0
v2b上加密方式设置为aes-128-gcm
启动Xray后报unknown cipher method

### log如下：

>Dec 24 21:30:19 muran XrayR[8930]: XrayR 0.8.8 (A Xray backend that supports many panels)
Dec 24 21:30:19 muran XrayR[8930]: 2022/12/24 21:30:19 Start the panel..
Dec 24 21:30:19 muran XrayR[8930]: 2022/12/24 21:30:19 Xray Core Version: 1.6.6
Dec 24 21:30:22 muran XrayR[8930]: 2022/12/24 21:30:22 infra/conf: unknown cipher method:
Dec 24 21:30:22 muran XrayR[8930]: panic: infra/conf: unknown cipher method:
Dec 24 21:30:22 muran XrayR[8930]: goroutine 1 [running]:
Dec 24 21:30:22 muran XrayR[8930]: log.Panic({0xc000951d28?, 0xc000bf5a40?, 0xc000951d58?})
Dec 24 21:30:22 muran XrayR[8930]:         log/log.go:388 +0x65
Dec 24 21:30:22 muran XrayR[8930]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000969000)
Dec 24 21:30:22 muran XrayR[8930]:         github.com/XrayR-project/XrayR/service/controller/controller.go:83 +0x27f
Dec 24 21:30:22 muran XrayR[8930]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0007ecc00)
Dec 24 21:30:22 muran XrayR[8930]:         github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
Dec 24 21:30:22 muran XrayR[8930]: main.main()
Dec 24 21:30:22 muran XrayR[8930]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Dec 24 21:30:22 muran systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Dec 24 21:30:22 muran systemd[1]: XrayR.service: Failed with result 'exit-code'.

### config.yml如下
>
Log:
  Level: error # Log level: none, error, warning, info, debug 
  AccessPath: /etc/XrayR/access.Log
  ErrorPath: /etc/XrayR/error.log
DnsConfigPath: #/etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: #/etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: #/etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: #/etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnetionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB 
Nodes:

>

    PanelType: "V2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: "https://xxx.com"
      ApiKey: "xxxxx"
      NodeID: 50
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 60 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings
      DeviceLimit: 0 # Local settings will replace remote settings
      RuleListPath: /etc/XrayR/rulelist # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 10 # Time to update the nodeinfo, how many sec.
      EnableDNS: true # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: UseIP

求大佬解决

**Comment by thank243** [comment]
I cannot recall this problems.

**Comment by jxjeff** [comment]
我想我找到了问题的答案，是因为机器所属的v2b权限组没有用户而导致的
