### ISSUE TITLE
Outbound doesn`t work

### ISSUE THREAD

**Issue by 411R324** [XrayR-project/XrayR#182]
i try 
`[
  {
    "sendThrough": "123.123.123.123",
    "protocol": "socks",
    "settings": {
      "servers": [
        {
          "ota": false,
          "port": 19354,
          "users": [
            {
              "user": "1234",
              "pass": "1234",
              "level": 1
            }
          ]
        }
      ]
    },
    "tag": "proxy",
    "streamSettings": {
      "network": "tcp"
    },
    "proxySettings": {
      "tag": "proxy"
    },
  }
]
`
and
`[
  {
    "tag": "proxy",
    "protocol": "vmess",
    "settings": {
      "vnext": [
        {
          "address": "123.123.123.123",
          "port": 444,
          "users": [
            {
              "id": "2fd3b3bd-c71d-41b3-fec9-3a52c73a57a7",
              "alterId": 0  
            }
        ]
      }
    ]
  },
  "streamSettings": {
    "network": "ws"
  },
  "mux": {
    "enabled": true
  }
}
]`
but none of them work in custom_outbound.json for proxy mode tunneling...
Can someone help me fix it?

**Comment by thank243** [comment]
ref: https://github.com/XTLS/Xray-examples
`route.json` should be setted at the same time.

**Comment by 411R324** [comment]
i know this examples and all of them work on x-ui xray
but in xrayr doesn`t work

**Comment by thank243** [comment]
It can work. Check your config.

**Comment by 411R324** [comment]
![image](https://user-images.githubusercontent.com/68432020/209667628-84b114fe-10d0-4a19-aef2-5b02e654b009.png) config file

![image](https://user-images.githubusercontent.com/68432020/209667699-8194247f-eeec-4443-b99f-05c542cdeeae.png)
custom_outbound.json

please check my config

**Comment by thank243** [comment]
> ref: https://github.com/XTLS/Xray-examples `route.json` should be setted at the same time.
