### ISSUE TITLE
对接ProxyPanel的master分支报错

### ISSUE THREAD

**Issue by Ivaneus** [XrayR-project/XrayR#185]
Xrayr error log：
panic: Panel Start fialed: request http://域名/api/trojan/v1/node/1 failed: <!DOCTYPE html>

<html lang="zh_CN">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description"
          content="An account management Panel based on Laravel7 framework. Include multiple payment, account management, system caching, admin notification, products models, and more.">
    <meta name="keywords" content="ProxyPanel Laravel Shadowsocks ShadowsocksR V2Ray Trojan VNET VPN">
    <meta name="author" content="ZBrettonYe">
    <meta name="copyright" content="2017-2022©ProxyPanel">
    <title>ProxyPanel - ⚠️错误触发</title>
    <link href="http://域名/favicon.ico" rel="shortcut icon apple-touch-icon">
    
    <link href="/assets/bundle/app.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.loli.net/ajax/libs/flag-icon-css/6.6.4/css/flag-icons.min.css" integrity="sha512-uvXdJud8WaOlQFjlz9B15Yy2Au/bMAvz79F7Xa6OakCl2jvQPdHD0hb3dEqZRdSwG4/sknePXlE7GiarwA/9Wg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="/assets/css/errors.min.css" rel="stylesheet">

    <link href="/assets/global/fonts/web-icons/web-icons.min.css" rel="stylesheet">
    <link href="https://fonts.loli.net/css?family=Roboto:300,400,500,300italic" rel="stylesheet">
    
    
    
    <script src="/assets/global/vendor/breakpoints/breakpoints.min.js"></script>
    <script>
        Breakpoints();
    </script>
    </head>

<body class="animsition page-error layout-full">
    <div class="page vertical-align text-center" data-animsition-in="fade-in" data-animsition-out="fade-out">
        <div class="page-content vertical-align-middle">
            <header>
                <h1 class="animation-slide-top">哎呦！</h1>
            </header>
            <h3>错❌误携带了报告：</h3>
            <code class="error-advise">找不到网页</code>
        </div>
    </div>

经过和旧版本proxypanel比对，可以和旧版proxypanel兼容，但是对于master最新版本无法获取节点信息进行对接。

**Comment by thank243** [comment]
Could you provide complete api address and response？

**Comment by Ivaneus** [comment]
usr: test@test.com
pwd: 123456
https://demo.proxypanel.cf/admin
you can add nodes and get nodes api key for a test through this proxypanel demo website

**Comment by thank243** [comment]
The demo you provide is working normally. 
`https://demo.proxypanel.cf/api/trojan/v1/node/1`
I use browser to visit it and recv this respone
`{"status":"fail","code":400,"data":null,"message":"Your key is null!"}`
You should provide other demo server for testing.

**Comment by Ivaneus** [comment]
http://45.154.214.153/admin/
usr: [test@test.com](mailto:test@test.com)
pwd: 123456

**Comment by thank243** [comment]
Your panel is not install properly. Please fix it and reopen this issue. You can also use `php artisan route:list` to print api routes
