### ISSUE TITLE
handshake erorr

### ISSUE THREAD

**Issue by emanam05** [XrayR-project/XrayR#189]
![Screenshot (14)](https://user-images.githubusercontent.com/121748299/210165850-e3eaf06f-d58e-476e-b797-4338fb6b66a8.jpg)
Hi, I keep getting this message.
some networks connect perfectly fine but on some networks, I keep getting this
Guess how to fix it?

**Comment by emanam05** [comment]
and somtimes keep getting this
```
failed to process outbound traffic > proxy/freedom: failed to open 
unexpected EOF > common/mux: failed to read metadata > io: read/write on closed pipe
connection ends > proxy/vmess/inbound: connection ends > context canceled

```

**Comment by thank243** [comment]
This is not xrayR's problem, you should goto xray-core group to ask.
