### ISSUE TITLE
提个莫名的问题，关于APP登录

### ISSUE THREAD

**Issue by nauya** [XrayR-project/XrayR#19]
使用场景是iPhone XR ios 14   软件shadowrocket   部署协议 trojan  

在使用XrayR后端部署  登录虾皮app  无法登录 总是正在读取中始终无法正常登录

复现同样使用场景，

使用soga后端部署  登录虾皮app，就可以正常登录  

不知道是哪里问题，以上是亲自测试得出的结果

**Comment by crackair** [comment]
检查dns配置问题
