### ISSUE TITLE
@abstract in fallbacks

### ISSUE THREAD

**Issue by kontorol** [XrayR-project/XrayR#198]
Hello , How i can using @abstract in fallbacks dest to other node like xray example ?
thanlks

"fallbacks": [
          {
            // if the path was `/vlessws`, pass it to vless-ws listener
            "path": "/vlessws",
            "dest": "@vless-ws",
            "xver": 2 //Enable the sending of the PROXY protocol, and send the real source IP and port to the following vmess+ws application. 1 or 2 indicates the PROXY protocol version. Consistent with the following, it is recommended to configure 2.
          }

[https://github.com/XTLS/Xray-examples/blob/main/All-in-One-fallbacks-Nginx/server.json]

**Comment by thank243** [comment]
xrayr supports all feat of xray-core.

**Comment by kontorol** [comment]
thanks to replay . may please tell me how pass dist to other node in same config file without port and with @abstract , how i can add tag to node in config file ?
example: fallback to @vless-ws  node (how to tag 'vless-ws' node ?)
FallBackConfigs: 
        -
          SNI: 
          Alpn: 
          Path: /vlessws 
          Dest: @vless-ws 
          ProxyProtocolVer: 2

**Comment by thank243** [comment]
Ref: https://github.com/XTLS/Xray-examples/tree/main/All-in-One-fallbacks-Nginx
