### ISSUE TITLE
纯ws报错

### ISSUE THREAD

**Issue by xieruan** [XrayR-project/XrayR#2]
使用纯ws报错
 app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from ip:42557 > proxy/vmess/encoding: failed to read request header > read tcp ip:10088->ip:42557: read: connection reset by peer

tcp示例
ip;12345;2;;tcp;server=域名  这个在sspanel节点列表不能显示传输协议
ip;12345;2;tcp;;server=域名   这个在sspanel节点列表正常显示传输协议，但启动xrayr失败

soga的tcp是这样的ip;12345;2;tcp;;server=域名

以上报错不知道是不是我的问题，还请大佬多多指教。谢谢

**Comment by RManLuo** [comment]
配置文件设置错误，请阅读readme，XrayR的配置是tls设置项在前。

**Comment by RManLuo** [comment]
经检查，tcp协议在前时ssp好像的确会报错，下一个版本修复。

**Comment by RManLuo** [comment]
fixed here # 703393d

**Comment by xieruan** [comment]
多谢大佬，单ws能用但上报流量失败
我用的ws    ip;10088;2;ws;;path=/xxx|host=xxx.ml
2021/03/17 14:03:16 [Info] [2584685636] app/proxyman/inbound: connection ends > proxy/vmess/inbound: invalid request from ip:45567 > proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2021/03/17 14:03:16 [Info] [2584685636] app/proxyman/inbound: failed to close connection > transport/internet/websocket: failed to close connection > transport/internet/websocket: websocket: close sent
2021/03/17 14:03:16 ip:45567 rejected  proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2021/03/17 14:03:20 [Info] [1718149161] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/03/17 14:03:20 [Info] [1718149161] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled

**Comment by RManLuo** [comment]
此信息系Xray-core核心的Info，并未发现与上报流量有关。

**Comment by xieruan** [comment]
大佬，应该是这个，还有post的也不行，我测试站点套了cf，是不是跟这个有关系啊
2021/03/17 14:49:21 request http://xxxx.coml/mod_mu/users/aliveip failed: <!DOCTYPE HTML>
<html lang="zh-cn">
<head>
    <title>您的访问方式不正确 - xx加速器 </title>

**Comment by RManLuo** [comment]
此处为上报在线ip的接口，请提供ssp版本进行进一步问题确认。

**Comment by xieruan** [comment]
最新的dev版

**Comment by xieruan** [comment]
大佬，还有这个错误
 request http://xxxx.com/mod_mu/nodes/3/info failed: Post "http://xxx.com/mod_mu/nodes/3/info?key=11111111": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by RManLuo** [comment]
请在运行后端的服务器上执行：
`curl -H "Content-Type:application/json" -X POST -d '{"data":[{"user_id":1,"ip":"1.1 .1 .1"}]}' https://xxxx.coml/mod_mu/users/aliveip\?key\=xx\&node_id\=xx`
请自行替换url地址和webapi连接key以及节点ip，并提供返回值进行问题判断。

**Comment by RManLuo** [comment]
请在运行后端的服务器上执行：
`curl -H "Content-Type:application/json" -X POST -d '{"data":[{"user_id":1,"ip":"1.1 .1 .1"}]}' https://xxxx.coml/mod_mu/users/aliveip\?key\=xx\&node_id\=xx`
请自行替换url地址和webapi连接key以及节点ip，并提供返回值进行问题判断。

**Comment by RManLuo** [comment]
> 大佬，还有这个错误
> request http://xxxx.com/mod_mu/nodes/3/info failed: Post "http://xxx.com/mod_mu/nodes/3/info?key=11111111": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

此问题为服务器访问超时，请判断面板服务器连接可用性。

**Comment by xieruan** [comment]
> 请在运行后端的服务器上执行：
> `curl -H "Content-Type:application/json" -X POST -d '{"data":[{"user_id":1,"ip":"1.1 .1 .1"}]}' https://xxxx.coml/mod_mu/users/aliveip\?key\=xx\&node_id\=xx`
> 请自行替换url地址和webapi连接key以及节点ip，并提供返回值进行问题判断。

返回这个{"ret":1,"data":"ok"}

**Comment by RManLuo** [comment]
看下这个版本是否解决问题：
https://github.com/XrayR-project/XrayR/releases/tag/v0.2.3
如果还不行建议先关闭cf再尝试。

**Comment by xieruan** [comment]
> 看下这个版本是否解决问题：
> https://github.com/XrayR-project/XrayR/releases/tag/v0.2.3
> 如果还不行建议先关闭cf再尝试。

大佬，刚测完这个，套的cf，报错如下。我关cf再测试一波
2021/03/17 16:30:50 request http://xx.com/mod_mu/users/traffic failed: <!DOCTYPE HTML>
<html lang="zh-cn">
<head>
    <title>您的访问方式不正确 - xx加速器 </title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <meta charset="utf-8"/>


</html>, %!s(<nil>)
2021/03/17 16:30:51 request http://xx.com/mod_mu/users/aliveip failed: <!DOCTYPE HTML>
<html lang="zh-cn">
<head>
    <title>您的访问方式不正确 - xx加速器 </title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>

**Comment by xieruan** [comment]
> 看下这个版本是否解决问题：
> https://github.com/XrayR-project/XrayR/releases/tag/v0.2.3
> 如果还不行建议先关闭cf再尝试。

大佬，关掉cf还是相同的报错。应该不是cf的问题

**Comment by RManLuo** [comment]
已在最ssp最新版本测试，上报没有问题，请自行确认ssp使用版本和网络问题寻求解决方法。

**Comment by xieruan** [comment]
大佬，换了台服务器测试已经OK了。多谢多谢
