### ISSUE TITLE
更改为acme.sh的验证方式

### ISSUE THREAD

**Issue by pudding1111** [XrayR-project/XrayR#20]
看了老哥的dns申请是通过  https://go-acme.github.io/lego/dns/dnspod/    申请的，go-acme的验证不太能满足国内申请ssl证书的需要，建议改成   https://github.com/acmesh-official/acme.sh/wiki/dnsapi   进行申请。
就以申请dnspod的ssl为例，go-acme要求验证DNSPOD_API_KEY，国内是没有这个参数的，国内的dnspod要求id、key两个参数，而acmesh-official的export DP_Id="1234"，export DP_Key="sADDsdasdgdsf"满足申请要求。

**Comment by crossfw** [comment]
查了下，此处的格式是  id,key

**Comment by pudding1111** [comment]
> 查了下，此处的格式是 id,key

   https://go-acme.github.io/lego/dns/dnspod/   并没有这两个参数，头秃

**Comment by crossfw** [comment]
> > 查了下，此处的格式是 id,key
> 
> https://go-acme.github.io/lego/dns/dnspod/ 并没有这两个参数，头秃

按 `id, key` 的格式填入DNSPOD_API_KEY

**Comment by pudding1111** [comment]
> > 查了下，此处的格式是 id,key
> 
> https://go-acme.github.io/lego/dns/dnspod/ 并没有这两个参数，头秃

        Provider: dnspod # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        DNSEnv: # DNS ENV option used by DNS provider
        DNSPOD_API_KEY:id,key

谢老哥。

**Comment by pudding1111** [comment]
我看到一个包被弃用，这个应该不是XrayR启动不了的原因，但是我还是没有找到启动不了的原因，以下是配置文件和log.
配置文件
Log:
  Level: none # Log level: none, error, warning, info, debug
  AccessPath: # ./access.Log
  ErrorPath: # ./error.log
DnsConfigPath: # ./dns.json Path to dns config
Nodes:
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board
    ApiConfig:
      ApiHost: "https://xxxx.xyz/"
      ApiKey: "xxxxxxxxxxx"
      NodeID: 23
      NodeType: Trojan # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type, Remote configuration first
      EnableXTLS: false # Enable XTLS for V2ray and Trojan, emote configuration first
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "xxxxxxxx.xyz" # Domain to cert
       # CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
       # KeyFile: ./cert/node1.test.com.key
        Provider: dnspod # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
       # Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          DNSPOD_API_KEY:ID,KEY

log文件
May 19 00:16:44 Act_0410131035 systemd[1]: Started XrayR Service.
May 19 00:16:44 Act_0410131035 XrayR[4277]: WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
May 19 00:16:44 Act_0410131035 XrayR[4277]:         A future release of golang/protobuf will delete this package,
May 19 00:16:44 Act_0410131035 XrayR[4277]:         which has long been excluded from the compatibility promise.
May 19 00:16:44 Act_0410131035 XrayR[4277]: XrayR 0.5.0 (A Xray backend that supports many panels)
May 19 00:16:44 Act_0410131035 XrayR[4277]: 2021/05/19 00:16:44 Start the panel..
May 19 00:16:44 Act_0410131035 XrayR[4277]: 2021/05/19 00:16:44 Xray Core Version: 1.4.2
May 19 00:16:44 Act_0410131035 XrayR[4277]: panic: runtime error: invalid memory address or nil pointer dereference
May 19 00:16:44 Act_0410131035 XrayR[4277]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1753897]
May 19 00:16:44 Act_0410131035 XrayR[4277]: goroutine 1 [running]:
May 19 00:16:44 Act_0410131035 XrayR[4277]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000492100)
May 19 00:16:44 Act_0410131035 XrayR[4277]:         github.com/XrayR-project/XrayR/panel/panel.go:99 +0x1d7
May 19 00:16:44 Act_0410131035 XrayR[4277]: main.main()
May 19 00:16:44 Act_0410131035 XrayR[4277]:         github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
May 19 00:16:44 Act_0410131035 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 19 00:16:44 Act_0410131035 systemd[1]: XrayR.service: Unit entered failed state.
May 19 00:16:44 Act_0410131035 systemd[1]: XrayR.service: Failed with result 'exit-code'.
May 19 00:16:49 Act_0410131035 systemd[1]: XrayR.service: Service hold-off time over, scheduling restart.
May 19 00:16:49 Act_0410131035 systemd[1]: Stopped XrayR Service.
May 19 00:16:49 Act_0410131035 systemd[1]: Started XrayR Service.
May 19 00:16:49 Act_0410131035 XrayR[4294]: WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
May 19 00:16:49 Act_0410131035 XrayR[4294]:         A future release of golang/protobuf will delete this package,
May 19 00:16:49 Act_0410131035 XrayR[4294]:         which has long been excluded from the compatibility promise.
May 19 00:16:49 Act_0410131035 XrayR[4294]: XrayR 0.5.0 (A Xray backend that supports many panels)
May 19 00:16:49 Act_0410131035 XrayR[4294]: 2021/05/19 00:16:49 Start the panel..
May 19 00:16:49 Act_0410131035 XrayR[4294]: 2021/05/19 00:16:49 Xray Core Version: 1.4.2
May 19 00:16:49 Act_0410131035 XrayR[4294]: panic: runtime error: invalid memory address or nil pointer dereference
May 19 00:16:49 Act_0410131035 XrayR[4294]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1753897]
May 19 00:16:49 Act_0410131035 XrayR[4294]: goroutine 1 [running]:
May 19 00:16:49 Act_0410131035 XrayR[4294]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000494100)
May 19 00:16:49 Act_0410131035 XrayR[4294]:         github.com/XrayR-project/XrayR/panel/panel.go:99 +0x1d7
May 19 00:16:49 Act_0410131035 XrayR[4294]: main.main()
May 19 00:16:49 Act_0410131035 XrayR[4294]:         github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
May 19 00:16:49 Act_0410131035 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 19 00:16:49 Act_0410131035 systemd[1]: XrayR.service: Unit entered failed state.
May 19 00:16:49 Act_0410131035 systemd[1]: XrayR.service: Failed with result 'exit-code'.
May 19 00:16:55 Act_0410131035 systemd[1]: XrayR.service: Service hold-off time over, scheduling restart.
May 19 00:16:55 Act_0410131035 systemd[1]: Stopped XrayR Service.
May 19 00:16:55 Act_0410131035 systemd[1]: Started XrayR Service.
May 19 00:16:55 Act_0410131035 XrayR[4301]: WARNING: Package "github.com/golang/protobuf/protoc-gen-go/generator" is deprecated.
May 19 00:16:55 Act_0410131035 XrayR[4301]:         A future release of golang/protobuf will delete this package,
May 19 00:16:55 Act_0410131035 XrayR[4301]:         which has long been excluded from the compatibility promise.
May 19 00:16:55 Act_0410131035 XrayR[4301]: XrayR 0.5.0 (A Xray backend that supports many panels)
May 19 00:16:55 Act_0410131035 XrayR[4301]: 2021/05/19 00:16:55 Start the panel..
May 19 00:16:55 Act_0410131035 XrayR[4301]: 2021/05/19 00:16:55 Xray Core Version: 1.4.2
May 19 00:16:55 Act_0410131035 XrayR[4301]: panic: runtime error: invalid memory address or nil pointer dereference
May 19 00:16:55 Act_0410131035 XrayR[4301]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1753897]
May 19 00:16:55 Act_0410131035 XrayR[4301]: goroutine 1 [running]:
May 19 00:16:55 Act_0410131035 XrayR[4301]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000496100)
May 19 00:16:55 Act_0410131035 XrayR[4301]:         github.com/XrayR-project/XrayR/panel/panel.go:99 +0x1d7
May 19 00:16:55 Act_0410131035 XrayR[4301]: main.main()
May 19 00:16:55 Act_0410131035 XrayR[4301]:         github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
May 19 00:16:55 Act_0410131035 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 19 00:16:55 Act_0410131035 systemd[1]: XrayR.service: Unit entered failed state.
May 19 00:16:55 Act_0410131035 systemd[1]: XrayR.service: Failed with result 'exit-code'.
May 19 00:17:00 Act_0410131035 systemd[1]: XrayR.service: Service hold-off time over, scheduling restart.
May 19 00:17:00 Act_0410131035 systemd[1]: Stopped XrayR Service.
May 19 00:17:00 Act_0410131035 systemd[1]: XrayR.service: Start request repeated too quickly.
May 19 00:17:00 Act_0410131035 systemd[1]: Failed to start XrayR Service.
May 19 00:17:00 Act_0410131035 systemd[1]: XrayR.service: Unit entered failed state.
May 19 00:17:00 Act_0410131035 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by RManLuo** [comment]
可以使用acme.sh申请证书，CertMode设为file，并手工指定证书路径。
