### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by Excalibur-osu** [XrayR-project/XrayR#207]
CertConfig:
 57         CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
 58         CertDomain: "xx.xx.com" # Domain to cert
 59         CertFile: /etc/XrayR/cert/xrayr.cert # Provided if the CertMode is file
 60         KeyFile: /etc/XrayR/cert/xrayr.key
 61         Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
 62         Email: xx@xx.com
 63         DNSEnv: # DNS ENV option used by DNS provider
 64         #ALICLOUD_ACCESS_KEY: aaa
 65         #ALICLOUD_SECRET_KEY: bbb
 66         CF_API_EMAIL: xx@xx.com
 67         CF_API_KEY: xxxx

两台机子配置相同 都使用cf的api获取证书 只是58行域名不同 第一台机子正常 第二台机子报错缺少配置?
Jan 10 16:28:25 VM-0-12-centos systemd[1]: Started XrayR Service.
Jan 10 16:28:25 VM-0-12-centos XrayR[6603]: XrayR 0.8.8 (A Xray backend that supports many panels)
Jan 10 16:28:25 VM-0-12-centos XrayR[6603]: 2023/01/10 16:28:25 Start the panel..
Jan 10 16:28:25 VM-0-12-centos XrayR[6603]: 2023/01/10 16:28:25 Xray Core Version: 1.6.6
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: 2023/01/10 16:28:26 cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: panic: cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: goroutine 1 [running]:
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: log.Panic({0xc000e67d28?, 0xc000d10000?, 0xc000e67d58?})
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]:         log/log.go:388 +0x65
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00095f300)
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]:         github.com/XrayR-project/XrayR/service/controller/controller.go:83 +0x27f
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000944540)
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]:         github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]: main.main()
Jan 10 16:28:26 VM-0-12-centos XrayR[6603]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Jan 10 16:28:26 VM-0-12-centos systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 10 16:28:26 VM-0-12-centos systemd[1]: XrayR.service: Failed with result 'exit-code'.

有数量限制吗?还是什么问题?请教一下!

**Comment by thank243** [comment]
Try to use 
`CLOUDFLARE_EMAIL
CLOUDFLARE_API_KEY`
