### ISSUE TITLE
动态限速配置后不起作用

### ISSUE THREAD

**Issue by asdjkm1234** [XrayR-project/XrayR#212]
如题，只有SpeedLimit: 0 这个配置起作用
请问动态限速是针对用户在某个节点下的限速吗？
能不能实现节点&用户双重限速？
如图：限制6-5mbps
![Snipaste_2023-01-14_20-27-23](https://user-images.githubusercontent.com/53368123/212471673-f4def2da-891d-49f4-8b86-83c0b643dcd7.jpg)
但是速度依旧还是那么快
![Snipaste_2023-01-14_20-28-20](https://user-images.githubusercontent.com/53368123/212471686-2df38f41-b6cd-4cea-9298-a5ec4fca7203.jpg)
后台日志并无报错
![Snipaste_2023-01-14_20-31-32](https://user-images.githubusercontent.com/53368123/212471693-baaac231-b72f-4356-b7ce-7a59f2952acd.jpg)

**Comment by asdjkm1234** [comment]
修改配置后已删除docker容器重新docker-compose up -d  还是不行

**Comment by asdjkm1234** [comment]
请问动态限速是针对用户在某个节点下的限速吗？
就类似java语言中的“局部变量”一样
全体用户在某个节点中的限速，而不是在v2board设置用户限速之后，全体节点都生效。
因为某些节点的宽带很小，这样设置了相当于没设置，设置小了用一些大宽带的节点又太慢。

**Comment by asdjkm1234** [comment]
使用版本：
v2board 1.7.2
xrayr 0.8.8

**Comment by thank243** [comment]
I think that before open a issue, you should read document first.
https://xrayr-project.github.io/XrayR-doc/gong-neng-shuo-ming/speedlimit.html

**Comment by asdjkm1234** [comment]
> 

我读了文档，但是我设置了限速，即使我已经取消了SpeedLimit选项，无论如何也达不到动态限速里面说的速度
可能是鄙人理解力不好
具体请看我发的配置图片

**Comment by asdjkm1234** [comment]
![Snipaste_2023-01-14_22-39-40](https://user-images.githubusercontent.com/53368123/212477387-85f6db42-2e86-4844-aa75-7dd2905bab3c.jpg)
