### ISSUE TITLE
Request for guide to forward client ip through bridge server for maintaining device_limit

### ISSUE THREAD

**Issue by zerodwide** [XrayR-project/XrayR#214]
**Greetings! Guys**

Its great, by `EnableProxyProtocol` in config, XrayR can detect real client ip from requests.
But the question is how to achieve it properly with **least impact** on Bridge Server **CPU**?

here is my network schema:

`client ---> [Bridge Server VPN] ---> [Main XrayR Server] ---> Free Internet!`

I use iptables to forward all request from Bridge Server to Main server via:

```
sysctl net.ipv4.ip_forward=1
iptables -t nat -A PREROUTING -j DNAT --to-destination MainServerIP
iptables -t nat -A POSTROUTING -j MASQUERADE
```
its clear by using iptables it wont pass real client ip address because of different layer of networking.

**Questions:**
 1. My first guess is using XrayR on Bridge Server and set CustomOutbands to forward requests to Main XrayR server.
**Does XrayR adds real clients ip to requests on outbands?**

2. Using Nginx as reverse proxy on Bridge Server
**Does XrayR supports Xtls/Tls when is behind of Nginx server?**

3. **Is there other solutions rather than iptables that can add real clients ip to request?**
I have heard Realm somewhere in comments but i have no idea what is that!

Thanks in Advance.

**Comment by thank243** [comment]
Use nginx as relay server and turn on proxyprotocol

**Comment by zerodwide** [comment]
@thank243 Thanks

**Comment by zerodwide** [comment]
Thanks @thank243

Are you aware of other 2 questions?
