### ISSUE TITLE
ipv6导致无法使用的问题

### ISSUE THREAD

**Issue by EdwardXiaoran** [XrayR-project/XrayR#22]
我没能在配置文件中找到监听端口是ipv6还是ipv4的选项。在我这边建立的节点的监听类型均为ipv6，导致无法使用
![image](https://user-images.githubusercontent.com/50768586/181903884-235b8ed0-535d-499f-b1af-4893df8274b6.png)

**Comment by EdwardXiaoran** [comment]
没事了，已解决

**Comment by endachao** [comment]
你好，请问一下是如何解决的

**Comment by EdwardXiaoran** [comment]
禁用linux的ipv6功能

**Comment by lowprofileusername** [comment]
有没有CONFIG的办法只监听IPV4.  面板上域名对应IP是IPV4 导致INVALID IP错误
