### ISSUE TITLE
Failed to start XrayR Service 作者大大就一台服务器报错，其他都正常

### ISSUE THREAD

**Issue by jay-mars** [XrayR-project/XrayR#22]
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: net/http/h2_bundle.go:7208 +0x6c5
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: goroutine 73 [syscall]:
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: os/signal.signal_recv(0x0)
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: runtime/sigqueue.go:168 +0xa5
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: os/signal.loop()
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: os/signal/signal_unix.go:23 +0x25
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: created by os/signal.Notify.func1.1
5月 23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR[4550]: os/signal/signal.go:151 +0x45
5月 23 16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: XrayR.service holdoff time over, scheduling restart.
5月 23 16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: Stopped XrayR Service.
5月 23 16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: start request repeated too quickly for XrayR.service
5月 23 16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: Failed to start XrayR Service.
5月 23 16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: Unit XrayR.service entered failed state.
5月 23 16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: XrayR.service failed.
5月 23 16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: start request repeated too quickly for XrayR.service
5月 23 16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: Failed to start XrayR Service.
5月 23 16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd[1]: XrayR.service failed.

**Comment by ak147568** [comment]
解决了吗？

**Comment by ak147568** [comment]
> 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：net / http / h2_bundle.go：7208 + 0x6c5
> 5月23日16:14： 35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：goroutine 73 [syscall]：
> 5月23 16:14:35 ip-172-26-7-56.ap -northeast-1.compute.internal XrayR [4550]：os / signal.signal_recv（0x0）
> 5月23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [ 4550]：runtime / sigqueue.go：168 + 0xa5
> 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：os / signal.loop（ ）
> 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：os / signal / signal_unix.go：23 + 0x25
> 5月23:14 ：35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：由os / signal.Notify.func1.1創建
> 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：os / signal / signal.go：151 + 0x45
> 5月23日16:14： 40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：XrayR.service釋抑超時，計劃重新啟動。
> 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：停止了XrayR服務。
> 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：對於XrayR.service重複啟動請求太快
> 5月23日16:14:40 ip -172-26-7-56.ap-northeast-1.compute.internal systemd [1]：無法啟動XrayR服務。
> 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：單元XrayR.service進入失敗狀態。
> 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：XrayR.service失敗。
> 5月23日16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：對於XrayR.service重複啟動請求太快
> 5月23日16:15:15 ip -172-26-7-56.ap-northeast-1.compute.internal systemd [1]：無法啟動XrayR服務。
> 5月23日16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：XrayR.service失敗。

解决了吗？？？

**Comment by jay-mars** [comment]
> > 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：net / http / h2_bundle.go：7208 + 0x6c5
> > 5月23日16:14： 35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：goroutine 73 [syscall]：
> > 5月23 16:14:35 ip-172-26-7-56.ap -northeast-1.compute.internal XrayR [4550]：os / signal.signal_recv（0x0）
> > 5月23 16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [ 4550]：runtime / sigqueue.go：168 + 0xa5
> > 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：os / signal.loop（ ）
> > 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：os / signal / signal_unix.go：23 + 0x25
> > 5月23:14 ：35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：由os / signal.Notify.func1.1創建
> > 5月23日16:14:35 ip-172-26-7-56.ap-northeast-1.compute.internal XrayR [4550]：os / signal / signal.go：151 + 0x45
> > 5月23日16:14： 40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：XrayR.service釋抑超時，計劃重新啟動。
> > 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：停止了XrayR服務。
> > 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：對於XrayR.service重複啟動請求太快
> > 5月23日16:14:40 ip -172-26-7-56.ap-northeast-1.compute.internal systemd [1]：無法啟動XrayR服務。
> > 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：單元XrayR.service進入失敗狀態。
> > 5月23日16:14:40 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：XrayR.service失敗。
> > 5月23日16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：對於XrayR.service重複啟動請求太快
> > 5月23日16:15:15 ip -172-26-7-56.ap-northeast-1.compute.internal systemd [1]：無法啟動XrayR服務。
> > 5月23日16:15:15 ip-172-26-7-56.ap-northeast-1.compute.internal systemd [1]：XrayR.service失敗。
> 
> 解决了吗？？？

解决了，ssl证书过期了，更新一下证书就好了
