### ISSUE TITLE
Is it possible to make certain domains open with the user's real IP ?

### ISSUE THREAD

**Issue by MrVb0** [XrayR-project/XrayR#220]
Hello
Is it possible to make certain domains open with the user's real IP by rulelist or route?
As far as I understand, the specified sites are only blocked with the default settings
thanks for your help

**Comment by mokhtarabadi** [comment]
yes but you need write rules in the client softwares not server

**Comment by MrVb0** [comment]
![Screenshot 2023-01-18 011111](https://user-images.githubusercontent.com/117315263/213018460-a42b4a74-7988-41cb-8fa8-064747f1f381.png)
![Screenshot 2023-01-18 011124](https://user-images.githubusercontent.com/117315263/213018468-8524302c-f539-4fb3-8aa2-94eab1143c3c.png)

"outboundTag": "direct-out"

Are these settings not applicable on the server?

**Comment by mokhtarabadi** [comment]
Yes, you should do this kind of routing on the client side.

**Comment by thank243** [comment]
the custom router shoule be work under custom outbound is setting properly.
