### ISSUE TITLE
XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT

### ISSUE THREAD

**Issue by uby777881** [XrayR-project/XrayR#221]
你好, 我有两台机器。一个用于网站，另一个用于节点.

我的 V2board 版本 1.7.2

我在使用 "PanelType: "NewV2board" 时遇到错误

错误日志如下

当我使用 "PanelType: "V2board"它工作正常。

我该如何解决？

Jan 18 00:20:18 vm505238 XrayR[3792]: XrayR 0.8.8 (A Xray backend that supports many panels)
Jan 18 00:20:18 vm505238 XrayR[3792]: 2023/01/18 00:20:18 Start the panel..
Jan 18 00:20:18 vm505238 XrayR[3792]: 2023/01/18 00:20:18 Xray Core Version: 1.6.6
Jan 18 00:20:18 vm505238 XrayR[3792]: 2023/01/18 00:20:18 [Warning] core: Xray 1.6.6 started
Jan 18 00:20:19 vm505238 XrayR[3792]: 2023/01/18 00:20:19 Panel Start fialed: request https://test.mydomain.com/api/v1/server/UniProxy/config failed: {
Jan 18 00:20:19 vm505238 XrayR[3792]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Jan 18 00:20:19 vm505238 XrayR[3792]: }, %!s(<nil>)
Jan 18 00:20:19 vm505238 XrayR[3792]: panic: Panel Start fialed: request https://test.mydomain.com/api/v1/server/UniProxy/config failed: {
Jan 18 00:20:19 vm505238 XrayR[3792]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
Jan 18 00:20:19 vm505238 XrayR[3792]: }, %!s(<nil>)
Jan 18 00:20:19 vm505238 XrayR[3792]: goroutine 1 [running]:
Jan 18 00:20:19 vm505238 XrayR[3792]: log.Panicf({0x31829b3?, 0x0?}, {0xc000937e80?, 0xc00027c600?, 0xc0004c5bb0?})
Jan 18 00:20:19 vm505238 XrayR[3792]:         log/log.go:395 +0x67
Jan 18 00:20:19 vm505238 XrayR[3792]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000968100)
Jan 18 00:20:19 vm505238 XrayR[3792]:         github.com/XrayR-project/XrayR/panel/panel.go:204 +0x5bc
Jan 18 00:20:19 vm505238 XrayR[3792]: main.main()
Jan 18 00:20:19 vm505238 XrayR[3792]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Jan 18 00:20:19 vm505238 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 18 00:20:19 vm505238 systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by thank243** [comment]
You should goto v2board group for helping.
