### ISSUE TITLE
infra/conf: Failed to build TCP config

### ISSUE THREAD

**Issue by 192255** [XrayR-project/XrayR#225]
infra/conf: Failed to build TCP config. > infra/conf: invalid TCP header config > json: cannot unmarshal array into Go struct field Authenticator.response of type conf.AuthenticatorResponse
xrayr_1  | panic: infra/conf: Failed to build TCP config. > infra/conf: invalid TCP header config > json: cannot unmarshal array into Go struct field Authenticator.response of type conf.AuthenticatorResponse

**Comment by thank243** [comment]
Can you provider the the json data from panel?
