### ISSUE TITLE
后端现在不支持 xtls-rprx-vision嘛？

### ISSUE THREAD

**Issue by ckaak** [XrayR-project/XrayR#230]
直接报错： 
[Warning] [1717182648] app/proxyman/inbound: connection ends > proxy/vless/inbound: xxxxxx-xxxx-xxxx-xxxx-xxxxxxis not able to use xtls-rprx-vision

客户端报错： 
proxy/vless/encoding: XtlsFilterTls found tls client hello! 176
 proxy/vless/encoding: XtlsPadding 176 764 0
app/proxyman/inbound: connection ends > proxy/http: connection ends > context canceled

**Comment by MrVb0** [comment]
What panel are you using that supports xtls-rprx-vision?

**Comment by thank243** [comment]
You can build it as yourself. Or waiting next release.
