### ISSUE TITLE
终端app vmess连接服务端时，服务端报错invalid user > proxy/vmess: Not Found

### ISSUE THREAD

**Issue by 192255** [XrayR-project/XrayR#231]
xrayr_1  | 2023/01/22 06:05:10 234.15.201.66:9430 rejected  common/drain: common/drain: unable to drain connection > read tcp 192.168.0.6:10053->234.15.201.66:9430: i/o timeout > proxy/vmess/encoding: invalid user > proxy/vmess: Not Found

**Comment by thank243** [comment]
Can you provide all config.yaml?

**Comment by 192255** [comment]
config.yml
Logs:
  Level: warning # Log level: none, error, warning, info, debug           
  AccessPath: # /etc/XrayR/access.Log                                     
  ErrorPath: # /etc/XrayR/error.log                                       
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://x
tls.github.io/config/dns.html for help                                    
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check htt
ps://xtls.github.io/config/routing.html for help                          
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbou
nd config, check https://xtls.github.io/config/inbound.html for help      
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom out
bound config, check https://xtls.github.io/config/outbound.html for help  
ConnectionConfig:                                                         
  Handshake: 4 # Handshake time limit, Second                             
  ConnIdle: 30 # Connection idle time limit, Second                       
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Sec
ond                                                                       
  DownlinkOnly: 4 # Time limit when the connection is closed after the upl
ink is closed, Second                                                     
  BufferSize: 64 # The internal cache size of each connection, kB         
Nodes:                                                                    
  -                                                                       
    PanelType: "Proxypanel" # Panel type: SSpanel, V2board, NewV2board, PM
panel, Proxypanel, V2RaySocks                                             
    ApiConfig:                                                                                      
      ApiHost: "http://203.112.201.188"                               
      ApiKey: "xdiL7scY7IO1UF4A"                                          
      NodeID: 1                                                           
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks
-Plugin                                                                   
      Timeout: 30 # Timeout for the api request                           
      EnableVless: false # Enable Vless for V2ray Type                    
      EnableXTLS: false # Enable XTLS for V2ray and Trojan                
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0
 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 mean
s disable                                                                 
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file     
    ControllerConfig:                                                     
      ListenIP: 0.0.0.0 # IP address you want to listen                   
      SendIP: 0.0.0.0 # IP address you want to send pacakage              
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.     
      EnableDNS: false # Use custom DNS config, Please ensure that you set
 the dns.json well                                                        
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy         
      EnableProxyProtocol: false # Only works for WebSocket and TCP       
      AutoSpeedLimitConfig:                                               
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user wi
ll be limited. Set to 0 to punish overspeed user immediately.             
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)     
        LimitDuration: 0 # How many minutes will the limiting last (unit: 
minute)                                                                   
      GlobalDeviceLimitConfig:                                            
        Enable: false # Enable the global device limit of a user          
        RedisAddr: 127.0.0.1:6379 # The redis server address              
        RedisPassword: YOUR PASSWORD # Redis password                     
        RedisDB: 0 # Redis DB                                             
        Timeout: 5 # Timeout for redis request                            
        Expiry: 60 # Expiry time (second)                                 
      EnableFallback: false # Only support for Trojan and Vless           
      FallBackConfigs:  # Support multiple fallbacks                      
        -                                                                 
          SNI: # TLS SNI(Server Name Indication), Empty for any           
          Alpn: # Alpn, Empty for any                                     
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls
.github.io/config/features/fallback.html for details.                     
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable 
      CertConfig:                                                         
        CertMode: dns # Option about how to get certificate: none, file, h
ttp, tls, dns. Choose "none" will forcedly disable the tls config.        
        CertDomain: "node1.test.com" # Domain to cert                     
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the Ce
rtMode is file                                                            
        KeyFile: /etc/XrayR/cert/node1.test.com.key                       
        Provider: alidns # DNS cert provider, Get the full support list he
re: https://go-acme.github.io/lego/dns/                                   
        Email: test@me.com                                                
        DNSEnv: # DNS ENV option used by DNS provider                     
          ALICLOUD_ACCESS_KEY: aaa                                        
          ALICLOUD_SECRET_KEY: bbb

**Comment by thank243** [comment]
Is there any valid user on nodes?

**Comment by 192255** [comment]
yes, it have a general user on nodes

**Comment by thank243** [comment]
Cannot recall, you can provide more logs.
