### ISSUE TITLE
最新版本的后端启动时会panic

### ISSUE THREAD

**Issue by chx818** [XrayR-project/XrayR#24]
日志如下
systemd[1]: Started XrayR Service.
XrayR[15776]: XrayR 0.8.1 (A Xray backend that supports many panels)
XrayR[15776]: 2022/08/01 02:45:29 Start the panel..
XrayR[15776]: 2022/08/01 02:45:29 Xray Core Version: 1.5.9
XrayR[15776]: panic: runtime error: invalid memory address or nil pointer dereference
XrayR[15776]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19e7868]
XrayR[15776]: goroutine 1 [running]:
XrayR[15776]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0000e7e00)
XrayR[15776]: github.com/XrayR-project/XrayR/panel/panel.go:165 +0x1c8
XrayR[15776]: main.main()
XrayR[15776]: github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: Unit XrayR.service entered failed state.
systemd[1]: XrayR.service failed.
systemd[1]: XrayR.service holdoff time over, scheduling restart.
systemd[1]: Stopped XrayR Service.
网上搜了下貌似是源代码问题，也不知道是不是我的配置文件没写好

**Comment by mengxin239** [comment]
方便把config.yml放出来吗

**Comment by chx818** [comment]
用截图可以吗
![屏幕截图 2022-08-01 105257.png](https://s2.loli.net/2022/08/01/Zuq4CQ58mcstxpz.png)

**Comment by wg19pmme** [comment]
我也是这个问题，看来还是老版本吧

**Comment by cumtsd** [comment]
> 我也是这个问题，看来还是老版本吧

去哪里下载老版本 求路径 谢谢

**Comment by aooaa** [comment]
这个问题解决了吗？
