### ISSUE TITLE
xiaoming

### ISSUE THREAD

**Issue by onesyue** [XrayR-project/XrayR#242]
v2board 版本  1.7.2xrayr后端选择 "NewV2board"，不能使用，选择V2board，却可以使用，怎么办？

**Comment by onesyue** [comment]
![image](https://user-images.githubusercontent.com/47652916/216270161-40fe73ed-7e95-4827-acac-9afff8228b60.png)
![image](https://user-images.githubusercontent.com/47652916/216270179-4f3de02f-d4ac-404f-963a-5cb5be766f65.png)
这两个图片在一个配置文件里
一个可以用新的，一个只能用旧的

**Comment by thank243** [comment]
Use the latest version on actions.

**Comment by onesyue** [comment]
我是使用docker部署的，已拉取最新镜像

**Comment by thank243** [comment]
Can you provide logs?

**Comment by onesyue** [comment]
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:36 Start the panel..
2023/02/02 16:56:36 Xray Core Version: 1.6.6
2023/02/02 16:56:36 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:37 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:37 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:37 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:37 86.55.15.110:0 rejected  proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2023/02/02 16:56:37 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc00027ab40)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00095d400)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000942600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:38 Start the panel..
2023/02/02 16:56:38 Xray Core Version: 1.6.6
2023/02/02 16:56:38 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:39 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:39 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:39 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:40 86.55.15.110:0 rejected  proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2023/02/02 16:56:40 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc000048b40)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000963100)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000942600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:40 Start the panel..
2023/02/02 16:56:40 Xray Core Version: 1.6.6
2023/02/02 16:56:40 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:41 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:41 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:41 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:42 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc0009a2b40)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00095f400)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000944600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:43 Start the panel..
2023/02/02 16:56:43 Xray Core Version: 1.6.6
2023/02/02 16:56:43 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:44 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:44 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:44 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:45 86.55.15.110:0 rejected  proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2023/02/02 16:56:45 86.55.15.110:0 rejected  proxy/vmess/encoding: invalid user > proxy/vmess: Not Found
2023/02/02 16:56:45 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc00027cab0)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00095f400)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000944600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:46 Start the panel..
2023/02/02 16:56:46 Xray Core Version: 1.6.6
2023/02/02 16:56:46 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:47 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:47 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:47 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:48 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc00004cb40)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00095f400)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000944600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:50 Start the panel..
2023/02/02 16:56:50 Xray Core Version: 1.6.6
2023/02/02 16:56:50 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:51 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:51 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:51 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:52 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc000998ab0)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00095d400)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000942600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
XrayR 0.8.8 (A Xray backend that supports many panels) 
2023/02/02 16:56:55 Start the panel..
2023/02/02 16:56:55 Xray Core Version: 1.6.6
2023/02/02 16:56:55 [Warning] core: Xray 1.6.6 started
2023/02/02 16:56:56 [https://www.legeth.com] V2ray(ID=331) Added 136 new users
2023/02/02 16:56:56 [https://www.legeth.com] V2ray(ID=331) Start node monitor periodic task
2023/02/02 16:56:56 [https://www.legeth.com] V2ray(ID=331) Start user monitor periodic task
2023/02/02 16:56:57 [https://free.legeth.com] V2ray(ID=5) Added 37 new users
panic: interface conversion: interface {} is []interface {}, not string

goroutine 1 [running]:
github.com/XrayR-project/XrayR/api/newV2board.(*APIClient).GetNodeRule(0xc000282ab0)
        github.com/XrayR-project/XrayR/api/newV2board/v2board.go:266 +0x38c
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000977400)
        github.com/XrayR-project/XrayR/service/controller/controller.go:107 +0x39d
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00095c600)
        github.com/XrayR-project/XrayR/panel/panel.go:202 +0x577
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250

**Comment by onesyue** [comment]
我的面板是v1.7.2的，看日志获取是1.6.6，有点奇怪
