### ISSUE TITLE
XrayR connect to V2board Error

### ISSUE THREAD

**Issue by khikhof** [XrayR-project/XrayR#251]
HI 
I try to connect my node to v2board panel and get this error : 

Feb 06 04:53:38 france1 XrayR[388544]: 2023/02/06 04:53:38.550778 ERROR RESTY Get "https://mysubdomain/api/v1/server/UniProxy/config?node_id=1&node_type=v                                                                                                                     2ray&token=aasdasdbskabs": tls: failed to verify certificate: x509: certificate signed by unknown authority, Attempt 1

i chenge config.yml many time and test but not working

test : http , dns , file and none certmode and none of them work
pls help

my node is ubuntu

**Comment by thank243** [comment]
`curl https://mysubdomain/api/v1/server/UniProxy/config?node_id=1&node_type=v 2ray&token=aasdasdbskabs`
And goto `https://stackoverflow.com/` for help.

**Comment by johnsy616** [comment]
i have the same issue, only in bandwagon centos.  system time is correct.
