### ISSUE TITLE
Add KCP & QUIC Support

### ISSUE THREAD

**Issue by TheArshiyan** [XrayR-project/XrayR#255]
@thank243 
Hello there,
It would be great if you just add **kcp and quic** support to the list of current protocols.

best regards

**Comment by thank243** [comment]
So will any panel support that?

**Comment by TheArshiyan** [comment]
@thank243 I've forked v2board and currently creating my own panel with it. so it will be really good if you just add these protocols so i can use it with my own modifications

**Comment by thank243** [comment]
Of course. Just do it.

**Comment by alohane** [comment]
> @thank243 I've forked v2board and currently creating my own panel with it. so it will be really good if you just add these protocols so i can use it with my own modifications

can you share your QUIC config?
