### ISSUE TITLE
Proxy Protocol 某些情况下会有IP识别问题

### ISSUE THREAD

**Issue by himgoods** [XrayR-project/XrayR#256]
RT，使用nginx stream模块转发，在机器有IPV6的时候Proxy Protocol的原始地址会变为   ::ffff:123.123.123.123
所有 IPv4 地址都会以 "::ffff:" 为前缀，这时把流量转发到XrayR会出现以下报错：
proxy/vmess/encoding: failed to read request header > proxyproto: invalid address

**Comment by himgoods** [comment]
附nginx配置

> stream{
    set_real_ip_from 0.0.0.0/0;
    set_real_ip_from ::/0;
    server{
        listen 123 proxy_protocol;
        listen [::]:123 proxy_protocol;
        listen 123 udp;
        listen [::]:123 udp;
        proxy_protocol on;
        proxy_pass 123.123.123.123:12345
    }
}

**Comment by thank243** [comment]
Just use xray-core to test this problem. If it can callback on xray-core, you should open an issue on xray-core group.

**Comment by f3j43fz** [comment]
Xray has merged the request pulled by @himgoods : https://github.com/XTLS/Xray-core/commit/7daa45c5501bb9dc0b36f5c6c823d103d213ab06

Hoping for XrayR's next move. Thank you.
