### ISSUE TITLE
一個小小的issue

### ISSUE THREAD

**Issue by cchhuuaann1** [XrayR-project/XrayR#26]
https://github.com/Anankke/SSPanel-Uim/issues/1264
既然webapi會導致數據庫資源佔用過高 那就在XrayR裏面加入上傳用戶在綫IP的選項 讓機場主自己選擇是否上傳用戶IP到前端

**Comment by RManLuo** [comment]
这个思路并不合适，ssp引入alive_ip是为了全局限制设备的功能，在接下来版本XraR会考虑跟进这个功能从而实现全局设备限制。

针对占用难题，并且我已经提交了一个issue可以缓解此问题。
