### ISSUE TITLE
最新版本启动失败

### ISSUE THREAD

**Issue by endachao** [XrayR-project/XrayR#26]
Aug 04 02:50:28 Node-1 systemd[1]: Started XrayR Service.
Aug 04 02:50:28 Node-1 XrayR[948]: XrayR 0.8.1 (A Xray backend that supports many panels)
Aug 04 02:50:28 Node-1 XrayR[948]: 2022/08/04 02:50:28 Start the panel..
Aug 04 02:50:28 Node-1 XrayR[948]: 2022/08/04 02:50:28 Xray Core Version: 1.5.9
Aug 04 02:50:28 Node-1 XrayR[948]: 2022/08/04 02:50:28 Panel Start fialed: Ret {"ret":0,"data":"IP is invalid. Now, your IP address is 2001:19f0:7001:3f75:5400:4ff:fe17:b92d"} invalid
Aug 04 02:50:28 Node-1 XrayR[948]: panic: Panel Start fialed: Ret {"ret":0,"data":"IP is invalid. Now, your IP address is 2001:19f0:7001:3f75:5400:4ff:fe17:b92d"} invalid

提示是 ip 是无效的，我的是有 ipv4 和 ipv6，但是也没找到在哪可以设置的地方

**Comment by demo2099** [comment]
> Aug 04 02:50:28 Node-1 systemd[1]: Started XrayR Service. Aug 04 02:50:28 Node-1 XrayR[948]: XrayR 0.8.1 (A Xray backend that supports many panels) Aug 04 02:50:28 Node-1 XrayR[948]: 2022/08/04 02:50:28 Start the panel.. Aug 04 02:50:28 Node-1 XrayR[948]: 2022/08/04 02:50:28 Xray Core Version: 1.5.9 Aug 04 02:50:28 Node-1 XrayR[948]: 2022/08/04 02:50:28 Panel Start fialed: Ret {"ret":0,"data":"IP is invalid. Now, your IP address is 2001:19f0:7001:3f75:5400:4ff:fe17:b92d"} invalid Aug 04 02:50:28 Node-1 XrayR[948]: panic: Panel Start fialed: Ret {"ret":0,"data":"IP is invalid. Now, your IP address is 2001:19f0:7001:3f75:5400:4ff:fe17:b92d"} invalid
> 
> 提示是 ip 是无效的，我的是有 ipv4 和 ipv6，但是也没找到在哪可以设置的地方

解决了么，我也遇到了

**Comment by endachao** [comment]
解决了，禁用 ipv6

**Comment by OKmetoo** [comment]
Nov 01 04:17:33 GreenCloud.1729497447 systemd[1]: XrayR.service: Failed with result 'exit-code'.
Nov 01 04:17:43 GreenCloud.1729497447 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 18.
Nov 01 04:17:43 GreenCloud.1729497447 systemd[1]: Stopped XrayR.service - XrayR Service.
Nov 01 04:17:43 GreenCloud.1729497447 systemd[1]: Started XrayR.service - XrayR Service.
Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: XrayR 0.9.4 (A Xray backend that supports many panels)
Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:43 Start the panel..
Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:43 Xray Core Version: 24.10.31
Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:43 [Warning] core: Xray 24.10.31 started
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:44 Panel Start failed: users is null
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: panic: Panel Start failed: users is null
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: goroutine 1 [running]:
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: log.Panicf({0x44580fd?, 0x4a47520?}, {0xc002561b18?, 0xc0041d3a70?, 0x3ace920?})
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         log/log.go:439 +0x65
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/panel.(*Panel).Start(0xc00195c7c0)
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/wyx2685/XrayR/panel/panel.go:213 +0x60f
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd.run()
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/wyx2685/XrayR/cmd/root.go:106 +0x1c5
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd.init.func1(0xc00196c600?, {0x4423b5c?, 0x4?, 0x4423a4c?})
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/wyx2685/XrayR/cmd/root.go:27 +0x13
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra.(*Command).execute(0x77c8500, {0xc0000728e0, 0x2, 0x2})
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra.(*Command).ExecuteC(0x77c8500)
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra.(*Command).Execute(...)
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/spf13/cobra@v1.8.0/command.go:1039
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd.Execute(...)
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/wyx2685/XrayR/cmd/root.go:120
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: main.main()
Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]:         github.com/wyx2685/XrayR/main.go:9 +0x1a
Nov 01 04:17:44 GreenCloud.1729497447 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
大神们，帮忙看看xboard面板对接XrayR有没有遇到过

**Comment by zuanzuanshao** [comment]
> Nov 01 04:17:33 GreenCloud.1729497447 systemd[1]: XrayR.service: Failed with result 'exit-code'. Nov 01 04:17:43 GreenCloud.1729497447 systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 18. Nov 01 04:17:43 GreenCloud.1729497447 systemd[1]: Stopped XrayR.service - XrayR Service. Nov 01 04:17:43 GreenCloud.1729497447 systemd[1]: Started XrayR.service - XrayR Service. Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: XrayR 0.9.4 (A Xray backend that supports many panels) Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:43 Start the panel.. Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:43 Xray Core Version: 24.10.31 Nov 01 04:17:43 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:43 [Warning] core: Xray 24.10.31 started Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: 2024/11/01 04:17:44 Panel Start failed: users is null Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: panic: Panel Start failed: users is null Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: goroutine 1 [running]: Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: log.Panicf({0x44580fd?, 0x4a47520?}, {0xc002561b18?, 0xc0041d3a70?, 0x3ace920?}) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: log/log.go:439 +0x65 Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/panel.(*Panel).Start(0xc00195c7c0) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/panel/panel.go:213 +0x60f Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd.run() Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd/root.go:106 +0x1c5 Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd.init.func1(0xc00196c600?, {0x4423b5c?, 0x4?, 0x4423a4c?}) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd/root.go:27 +0x13 Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra.(*Command).execute(0x77c8500, {0xc0000728e0, 0x2, 0x2}) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra@v1.8.0/command.go:987 +0xa91 Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra.(*Command).ExecuteC(0x77c8500) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra.(*Command).Execute(...) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/spf13/cobra@v1.8.0/command.go:1039 Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd.Execute(...) Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/cmd/root.go:120 Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: main.main() Nov 01 04:17:44 GreenCloud.1729497447 XrayR[152565]: github.com/wyx2685/XrayR/main.go:9 +0x1a Nov 01 04:17:44 GreenCloud.1729497447 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT 大神们，帮忙看看xboard面板对接XrayR有没有遇到过

目前遇到了，在想办法解决。

**Comment by zuanzuanshao** [comment]
解决了，用户购买的套餐权限等信息，需要和管理后台里面的节点信息保持一致。
