### ISSUE TITLE
为什么xrayr对接所有的节点都会偶尔出现这种log？

### ISSUE THREAD

**Issue by redtime1213** [XrayR-project/XrayR#261]
ERROR RESTY Post "https://xxxxxx.top/api/v1/server/UniProxy/push?node_id=1&node_type=trojan&token=xxxxxxx": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
ERROR RESTY Get "https://xxxxxxx.top/api/v1/server/UniProxy/config?node_id=1&node_type=trojan&token=xxxxxx": context deadline exceeded (Client.Timeout exceeded while awaiting headers), Attempt 1
推送拉取信息时间间隔检查了很多次还是有。。。

**Comment by thank243** [comment]
Change your IDC.
