### ISSUE TITLE
配合V2B 1.72使用SS 2022时UDP不通

### ISSUE THREAD

**Issue by Rakau** [XrayR-project/XrayR#269]
RT，使用原版加密就通

**Comment by thank243** [comment]
So your client support ss2022?

**Comment by Rakau** [comment]
> So your client support ss2022?

Yes, I am using netch

**Comment by Rakau** [comment]
I'll try the Clash Meta client later

**Comment by Rakau** [comment]
> How did you solve that?
> UoT?

It didn't fix it and I've given up using

**Comment by Rakau** [comment]
> And have you checked if udp works on xray-core / sspanel?

I haven't tried checking on the server side, but I have used https://github.com/HMBSbige/NatTypeTester and the detection fails

**Comment by Rakau** [comment]
> I'm thinking if it's a problem in xray-core, but I have no instance to test

XrayR   99504 root    9u  IPv6 112677130      0t0  TCP *:9119 (LISTEN)
XrayR   99504 root   10u  IPv6 112677134      0t0  UDP *:9119

**Comment by Rakau** [comment]
> 



> Hey I found out what's wrong
> 
> Only the first package was transferred Client - Server shadowsocks2022 - server(nc -l -u 33001)
> 
> But when NC is serving on server shadowsocks2022, all following packages get transferred
> 
> I don't understand network but I know it may be a bug in xrayr?

I think it's time for me to switch to Soga
