### ISSUE TITLE
默认配置文件位置的问题

### ISSUE THREAD

**Issue by pty819** [XrayR-project/XrayR#27]
请考虑一下把默认的配置文件位置改为xrayr可执行文件下面的config.yml和dns.json。文档里面写的默认配置文件在xrayr二进制文件同文件下，但是实际上服务里面写的位置是/etc/xrayr，额外又生成一次这个文件夹实在是很让人费解。。。
此外请求更换默认geosite和geoip为 https://github.com/Loyalsoldier/v2ray-rules-dat 的加强版geosite和geoip，xray自带的geosite感觉很不全，十分感谢！

**Comment by LovelyHaochi** [comment]
@pty819 XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by LovelyHaochi** [comment]
@LovelyHaochi XrayR官方文档: https://crackair.gitbook.io/xrayr-project/
(此消息60秒后自动删除)

**Comment by RManLuo** [comment]
当不用-c 指定配置文件目录时，XrayR会使用二进制文件当前目录下的默认配置文件。/etc/XrayR目录下为一键脚本默认的配置文件安装目录，两者并不冲突。

如有需要，可自行替换geosite和geoip文件。

**Comment by LovelyHaochi** [comment]
@RManLuo XrayR一键安装脚本: bash <(curl -Ls https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh)
(此消息10秒后自动删除)
