### ISSUE TITLE
Description of the problem

### ISSUE THREAD

**Issue by lineelu** [XrayR-project/XrayR#276]
Test environment 1
panel V2Board
centOS 7.6
Nginx 1.17
mysql 5.6
php 7.4

Test environment 2
panel V2Board
centOS 8.2
Nginx 1.21
mysql 5.6
php 7.4

Error logs：
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]:   line 68: mapping key "PanelType" already defined at line 17
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]:   line 69: mapping key "ApiConfig" already defined at line 18
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]:   line 80: mapping key "ControllerConfig" already defined at line 29
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]: panic: Config file error: While parsing config: yaml: unmarshal errors:
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]:   line 68: mapping key "PanelType" already defined at line 17
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]:   line 69: mapping key "ApiConfig" already defined at line 18
2月 27 22:02:37 iZt4nj1tlhgra7zcqe3kq2Z XrayR[104458]:   line 80: mapping key "ControllerConfig" already defined at line 29

Description of the problem：
When I configure the config.yml file, XRAYR can start normally with only one node added. However, when I configure the second node or panel, XRAYR will fail to start and the above error will appear in the log. I have tried various tests to modify the config.yml file, but cannot solve the problem, and can only subscribe to one node.

**Comment by thank243** [comment]
You should learn yaml synax.

**Comment by lineelu** [comment]
> 你应该学习yaml synax。

I don't quite understand what you mean. After I copied the content of config.yml according to the official document, the same problem appeared in the log. I also learned the editing method of config.yml on youtube. According to the rules and content of the video editing method, There is no error in the video content, but the error on my log appears

**Comment by lineelu** [comment]
> ApiConfig

According to the error reported in the log, my understanding is that these three, ControllerConfig, PanelType, and ApiConfig, appear twice in the config.yml text, and only one occurrence is allowed in config.yml. I checked the official document and did not point out this problem ,
