### ISSUE TITLE
服务停止后不会自动启动

### ISSUE THREAD

**Issue by ruichengwei** [XrayR-project/XrayR#28]
有时网络中断或面板崩溃对接不到服务停止后，不会自动启动，老节点是其它的后端都能在几分钟内恢复，XRAYR我得手动去启动

**Comment by crackair** [comment]
已于此处尝试更新重启规则https://github.com/XrayR-project/XrayR-release/commit/f3ea080540b48f5b02d9d89da22c86ee2c3f5c18
如果是使用一键脚本安装的可以尝试执行XrayR update更新服务配置。如果有效请麻烦在此issue中反馈。

**Comment by ruichengwei** [comment]
已测可以了
