### ISSUE TITLE
Reality security 

### ISSUE THREAD

**Issue by saeed1024** [XrayR-project/XrayR#285]
How to use Reality security instead of TLS security in XrayR?

**Comment by Xramas** [comment]
> Not support yet

Is there a plan to support ？lol

**Comment by kontorol** [comment]
> 

REALITY 分享链接标准已出，查看最新 edit diff：https://github.com/XTLS/Xray-core/discussions/716

**Comment by thank243** [comment]
@pocketW the latest core remove all of xtls feat, Pls mind it.

**Comment by kontorol** [comment]
@pocketW The REALITY sharing link standard has been released

**Comment by MrVb0** [comment]
Please add reality

**Comment by sonce** [comment]
期待添加Reality，端口经常被封。

**Comment by MrVb0** [comment]
Please add reality

**Comment by chibinyong** [comment]
> Please update to Xray-core v1.8.1.

兄台请问下如何在xrayr下 生成公私钥 ，./xray x25519在XrayR下无法使用
