### ISSUE TITLE
自定义入口规则不能识别配置文件

### ISSUE THREAD

**Issue by qiuzi** [XrayR-project/XrayR#288]
屏蔽BT流量需要在入站里配置嗅探功能，写入配置文件导入却识别成出口配置路径，程序报错
config.yml
....
RouteConfigPath: ./route.json
InboundConfigPath: ./custom_inbound.json
OutboundConfigPath: ./custom_outbound.json
./custom_inbound.json
[
    {
      "sniffing": {
        "enabled": true,
        "destOverride": [
          "http",
          "tls"
        ]
      }
]

`XrayR 0.9.0 (A Xray backend that supports many panels)
2023/03/15 12:56:15 Start the panel..
2023/03/15 12:56:15 Failed to unmarshal Custom Inbound config: ./custom_outbound.json
panic: Failed to unmarshal Custom Inbound config: ./custom_outbound.json

goroutine 1 [running]:
log.Panicf({0x32d133e?, 0x16?}, {0xc000b0fbf8?, 0x2788160?, 0xc00021ac60?})
        log/log.go:391 +0x67
github.com/XrayR-project/XrayR/panel.(*Panel).loadCore(0xc0006c5e80?, 0xc00052cbd0)
        github.com/XrayR-project/XrayR/panel/panel.go:102 +0x50e
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005b9380)
        github.com/XrayR-project/XrayR/panel/panel.go:168 +0xe9
main.main()
        github.com/XrayR-project/XrayR/main/main.go:97 +0x250
`

**Comment by besnow** [comment]
遇到了相同的问题！

**Comment by thank243** [comment]
Cannot recall
