### ISSUE TITLE
what happend?How can I change version?

### ISSUE THREAD

**Issue by chris1678** [XrayR-project/XrayR#289]
go: finding module for package github.com/xtls/xray-core/transport/internet/xtls
github.com/XrayR-project/XrayR/main/distro/all imports
        github.com/xtls/xray-core/transport/internet/xtls: module github.com/xtls/xray-core@latest found (v1.8.0), but does not contain package github.com/xtls/xray-core/transport/internet/xtls

**Comment by Github-Aiko** [comment]
@chris1678  you can test it 👍
