### ISSUE TITLE
ProxyProtocol开启后无法直连

### ISSUE THREAD

**Issue by Liumik233** [XrayR-project/XrayR#29]
ProxyProtocol开启后无法直连，日志报错proxyproto: proxy protocol signature not present

**Comment by crackair** [comment]
@Liumik233 请确保使用了支持proxyprotocol的中转，如haproxy等。

**Comment by Liumik233** [comment]
主要是想同时使用直连和中转

**Comment by Liumik233** [comment]
@crackair  我看soga那边开启proxyprotocol的情况下可以直连，xrayr不行的话就当我没提吧
