### ISSUE TITLE
XrayR没有自己的接口标准吗？

### ISSUE THREAD

**Issue by bbi8** [XrayR-project/XrayR#294]
XrayR没有自己的标准接口吗？我自己开发的面板想对接XrayR的话要怎么进行？找了文档没有发现有相关的说明，XrayR团队没有打算让其他面板对接吗？

**Comment by bbi8** [comment]
由于我不是go语言的编程者，我的面板是基于nodejs/java开发的，所以XrayR的源码对于我是有阅读障碍的，而XrayR与前端面板对接时采用的是http协议，希望XrayR可以出一套标准的http接口文档。

**Comment by Cp0204** [comment]
标准接口这个词有歧义，你需要的是：开发文档、对接文档

**Comment by bbi8** [comment]
> 标准接口这个词是正确的，你需要的是：开发文档、对接文档

现在的XrayR都是主动对接前端面板的接口，并没有自己的一套接口标准，所有如果有其他面板要使用XrayR就很局限，而且也没有用于对接的接口文档

**Comment by thank243** [comment]
I proposal use v2board's interface for your dev.

**Comment by bbi8** [comment]
> I proposal use v2board's interface for your dev.

I also hope that the full inbound option can be opened, the interface option of v2board is simple, XrayR can do much more than that
