### ISSUE TITLE
证书模式配置为cloudflare无法获取证书

### ISSUE THREAD

**Issue by kailin98** [XrayR-project/XrayR#30]
下面是我配置文件中的相关配置

CertConfig:
        

> CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.

        CertDomain: "xxxx.xxx.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: myemail@qq.com
        DNSEnv: # DNS ENV option used by DNS provider
             CF_API_EMAIL: myemail@qq.com
             CF_API_KEY: my-cloudflare-key

当启动程序是出现以下报错：

6月 21 09:08:46 vultr.guest systemd[1]: Started XrayR Service.
6月 21 09:08:47 vultr.guest XrayR[13048]: XrayR 0.5.5 (A Xray backend that supports many panels)
6月 21 09:08:47 vultr.guest XrayR[13048]: 2021/06/21 09:08:47 Start the panel..
6月 21 09:08:47 vultr.guest XrayR[13048]: 2021/06/21 09:08:47 Xray Core Version: 1.4.2
**6月 21 09:08:47 vultr.guest XrayR[13048]: 2021/06/21 09:08:47 cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
6月 21 09:08:47 vultr.guest XrayR[13048]: 2021/06/21 09:08:47 cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
6月 21 09:08:47 vultr.guest XrayR[13048]: panic: cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN**
6月 21 09:08:47 vultr.guest XrayR[13048]: goroutine 1 [running]:
6月 21 09:08:47 vultr.guest XrayR[13048]: log.Panic(0xc0007d1d70, 0x1, 0x1)
6月 21 09:08:47 vultr.guest XrayR[13048]: log/log.go:354 +0xae
6月 21 09:08:47 vultr.guest XrayR[13048]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000469950, 0x0, 0x0)
6月 21 09:08:47 vultr.guest XrayR[13048]: github.com/XrayR-project/XrayR/service/controller/controller.go:50 +0x165
6月 21 09:08:47 vultr.guest XrayR[13048]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0003fb6c0)
6月 21 09:08:47 vultr.guest XrayR[13048]: github.com/XrayR-project/XrayR/panel/panel.go:131 +0x6af
6月 21 09:08:47 vultr.guest XrayR[13048]: main.main()
6月 21 09:08:47 vultr.guest XrayR[13048]: github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
6月 21 09:08:47 vultr.guest systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
6月 21 09:08:47 vultr.guest systemd[1]: Unit XrayR.service entered failed state.
6月 21 09:08:47 vultr.guest systemd[1]: XrayR.service failed.

会一直提示没有相应的配置项，但是配置文件中确实是存在的

**Comment by crackair** [comment]
@kailin98 是bug，今晚修复

**Comment by Xcci** [comment]
@kailin98 用CLOUDFLARE_DNS_API_TOKEN就可以

**Comment by crackair** [comment]
@Xcci 0.5.5引入了新bug，旧版本不受影响。

**Comment by crackair** [comment]
Fixed here: 30bef522252425f5e98bbc01ab90e77ac6f67b36
Please upgrade to v0.5.6
