### ISSUE TITLE
A simple Setting install without panel

### ISSUE THREAD

**Issue by DanielBlackBeard** [XrayR-project/XrayR#305]
Hi, 
if it possible please create a structure that will create a random configuration without a panel and with a script to install cli mode once? This structure is very detailed and it is very difficult for those who want to start working.

thanks.

**Comment by DanielBlackBeard** [comment]
> You can make a fake panel to trick it works

can you share more info or link for doing that ? 
thanks

**Comment by DanielBlackBeard** [comment]
its so difficult to Me for making Farsi documentation and scripts for ordinary person about it. I hope a script that autogenerate config for few people is good .

**Comment by sajjad-ser** [comment]
> Are you trying to use panels in Iran?

I do this and i write a fake panel it simulate sspanel. And it will be prefect if XrayR have a global panel with other protocols in xray.

**Comment by DanielBlackBeard** [comment]
> > Are you trying to use panels in Iran?
> 
> I do this and i write a fake panel it simulate sspanel. And it will be prefect if XrayR have a global panel with other protocols in xray.

can you share this project to us , thanks

**Comment by thank243** [comment]
Why don't you use xray-core?
