### ISSUE TITLE
V2BOARD V2RAY后端对接失败

### ISSUE THREAD

**Issue by himanhimao** [XrayR-project/XrayR#31]
对接的V2BOARD, 默认没有开启TLS 
  -
    PanelType: "V2board" # Panel type: SSpanel, V2board, PMpanel
    ApiConfig:
      ApiHost: "http://127.0.0.1:8080"
      ApiKey: "123456789123456789"
      NodeID: 1
      NodeType: "V2ray" # Node type: V2ray, Shadowsocks, Trojan
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # ./rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: true # Only works for WebSocket and TCP
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: "none" # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

错误信息
`2021/06/30 17:42:07 127.0.0.1:54894 rejected  proxy/vmess/encoding: failed to read request header > proxyproto: proxy protocol signature not present
`

服务端没有开启TLS

**Comment by himanhimao** [comment]
接口配置返回的数据
`{
api: {
services: [
"HandlerService",
"StatsService"
],
tag: "api"
},
dns: {
servers: [
{
address: "1.1.1.1",
port: 53,
domains: [ ],
expectIPs: [ ]
},
"1.1.1.1",
"localhost"
],
hosts: { }
},
stats: { },
inbound: {
port: 12229,
protocol: "vmess",
settings: {
clients: [ ]
},
sniffing: {
enabled: false,
destOverride: [
"http",
"tls"
]
},
streamSettings: {
network: "tcp"
},
tag: "proxy"
},
inboundDetour: [
{
listen: "127.0.0.1",
port: 12229,
protocol: "dokodemo-door",
settings: {
address: "0.0.0.0"
},
tag: "api"
}
],
log: {
loglevel: "none",
access: "access.log",
error: "error.log"
},
outbound: {
protocol: "freedom",
settings: {
domainStrategy: "UseIP"
}
},
outboundDetour: [
{
protocol: "blackhole",
settings: { },
tag: "block"
}
],
routing: {
rules: [
{
inboundTag: "api",
outboundTag: "api",
type: "field"
}
]
},
policy: {
levels: {
0: {
handshake: 4,
connIdle: 300,
uplinkOnly: 5,
downlinkOnly: 30,
statsUserUplink: true,
statsUserDownlink: true
}
}
}
}`

**Comment by RManLuo** [comment]
certmode 为 none意味着强制关闭后端tls，tls交由上游caddy或者nginx处理。如需后端处理tls，请自行参看文档配置。
