### ISSUE TITLE
证书出现问题无法验证！！！

### ISSUE THREAD

**Issue by vvvmao** [XrayR-project/XrayR#31]
acme: Cleaning DNS-01 challenge
一直无法验证成功，等待。请问这个问题如何解决。

**Comment by cumtsd** [comment]
好像大家都普遍遇到了这个问题啊

**Comment by Tommytalk** [comment]
help!
acme: Waiting for DNS record propagation.

**Comment by cumtsd** [comment]
> help! acme: Waiting for DNS record propagation.

应该是新脚本的问题，已经安装脚本的系统不存在这个问题

**Comment by Kaiser-DMr** [comment]
我最近也是，但是之前安装没问题。你们解决了吗

**Comment by cumtsd** [comment]
> 我最近也是，但是之前安装没问题。你们解决了吗

没解决

**Comment by Kaiser-DMr** [comment]
使用0.8.2的老版本没事，新版本问题> > 我最近也是，但是之前安装没问题。你们解决了吗
> 
> 
> 
> 没解决

**Comment by aiboboxx** [comment]
我也是
` credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
2022/09/13 19:49:48 cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
2022/09/13 19:49:48 cloudflare: some credentials information are missing: CLOUDFLARE_EMAIL,CLOUDFLARE_API_KEY or some credentials information are missing: CLOUDFLARE_DNS_API_TOKEN,CLOUDFLARE_ZONE_API_TOKEN
2022/09/13 19:49:48 [Trojan: 1] 0 user deleted, 0 user added`

**Comment by h88782481** [comment]
me too
