### ISSUE TITLE
issuses with nginx reverse inxray v0.9.0

### ISSUE THREAD

**Issue by alirezashahrokhi** [XrayR-project/XrayR#327]
can any one help to set reverse ?

my nginx.conf:
server {
    server_name  myserver name;

    location /sometimesnaive {
        proxy_pass                       http://127.0.0.1:4443;
        proxy_redirect                   off;
        proxy_http_version               1.1;
        proxy_set_header Upgrade         $http_upgrade;
        proxy_set_header Connection      "upgrade";
        proxy_set_header Host            $http_host;
        proxy_set_header X-Real-IP       $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/x/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/x/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = x) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    listen       80;
    server_name  x;
    return 404; # managed by Certbot

}

xrayr log :
Apr 22 14:05:50 117278-new21 XrayR[1544]: 2023/04/22 10:35:50 http: TLS handshake error from 127.0.0.1:50488: EOF
Apr 22 14:06:37 117278-new21 XrayR[1544]: 2023/04/22 10:36:37 http: TLS handshake error from 127.0.0.1:50676: EOF
Apr 22 14:06:41 117278-new21 XrayR[1544]: 2023/04/22 10:36:41 http: TLS handshake error from 127.0.0.1:50688: EOF

why i get this error?

**Comment by thank243** [comment]
You shouldn't use port 80 for https.
