### ISSUE TITLE
Block Ads

### ISSUE THREAD

**Issue by saeed1024** [XrayR-project/XrayR#329]
How to block ads in the XrayR?

The config for blocking Ads in the X-UI is:

[
  {
    "inboundTag": [
      "api"
    ],
    "outboundTag": "api",
    "type": "field"
  },
  {
    "type": "field",
    "outboundTag": "blocked",
    "domain": [
      "geosite:category-ads-all",
      "geosite:category-ads",
      "geosite:google-ads",
      "geosite:spotify-ads"
    ]
  }
]
(it's working! I tested!)

How to convert this for use in the XrayR?

**Comment by wuchen4588** [comment]
> 如何屏蔽 XrayR 中的广告？
> 
> 在 X-UI 中屏蔽广告的配置是：
> 
> [ { "inboundTag": [ "api" ], "outboundTag": "api", "type": "field" }, { "type": "field", "outboundTag": "blocked", "domain": [ "geosite:category-ads-all", "geosite:category-ads", "geosite:google-ads", "geosite:spotify-ads" ] } ] （有效！我测试过！）
> 
> 如何将其转换为在 XrayR 中使用？

你直接拿机场的审计规则写啊，那玩意会明文匹配然后屏蔽。或者自建Adguard home的DNS来实现DNS污染屏蔽
