### ISSUE TITLE
希望增加dns流媒体解锁

### ISSUE THREAD

**Issue by EvvySiur** [XrayR-project/XrayR#33]
直接替换dns会影响机器流量使用的  希望增加dns流媒体解锁

**Comment by RManLuo** [comment]
请详细描述需求

**Comment by EvvySiur** [comment]
按照匹配规则分流 dns 查询 分流常见流媒体域名达到解锁流媒体网站  https://www.v2ray.com/chapter_02/04_dns.html 因为了解技术有限只能提供v2ray的一些基本介绍 这样就可以用原生服务器的少量流量来解锁落地机器  如果需要进一步帮助 可以提供常见的需要流媒体域名

**Comment by EvvySiur** [comment]
{ "dns": {
  "servers": [
    "8.8.8.8",
    {
      "address": "localhost",
      "port": 53,
      "domains": [
        "domain:akadns.net",
          "domain:akam.net",
          "domain:akamai.com",
          "domain:akamai.net",
          "domain:akamaiedge.net",
          "domain:akamaihd.net",
          "domain:akamaistream.net",
          "domain:akamaitech.net",
          "domain:akamaitechnologies.com",
          "domain:akamaitechnologies.fr",
          "domain:akamaized.net",
          "domain:edgekey.net",
          "domain:edgesuite.net",
          "domain:srip.net",
          "domain:footprint.net",
          "domain:level3.net",
          "domain:llnwd.net",
          "domain:edgecastcdn.net",
          "domain:cloudfront.net",
          "domain:netflix.com",
          "domain:netflix.net",
          "domain:nflximg.net",
          "domain:nflxvideo.net",
          "domain:nflxso.net",
          "domain:nflxext.com",
          "domain:hulu.com",
          "domain:huluim.com",
          "domain:hbonow.com",
          "domain:hbogo.com",
          "domain:hbo.com",
          "domain:amazon.com",
          "domain:amazon.co.uk",
          "domain:amazonvideo.com",
          "domain:crackle.com",
          "domain:pandora.com",
          "domain:vudu.com",
          "domain:blinkbox.com",
          "domain:abc.com",
          "domain:fox.com",
          "domain:theplatform.com",
          "domain:nbc.com",
          "domain:nbcuni.com",
          "domain:ip2location.com",
          "domain:pbs.org",
          "domain:warnerbros.com",
          "domain:southpark.cc.com",
          "domain:cbs.com",
          "domain:brightcove.com",
          "domain:cwtv.com",
          "domain:spike.com",
          "domain:go.com",
          "domain:mtv.com",
          "domain:mtvnservices.com",
          "domain:playstation.net",
          "domain:uplynk.com",
          "domain:maxmind.com",
          "domain:disney.com",
          "domain:disneyjunior.com",
          "domain:xboxlive.com",
          "domain:lovefilm.com",
          "domain:turner.com",
          "domain:amctv.com",
          "domain:sho.com",
          "domain:mog.com",
          "domain:wdtvlive.com",
          "domain:beinsportsconnect.tv",
          "domain:beinsportsconnect.net",
          "domain:fig.bbc.co.uk",
          "domain:open.live.bbc.co.uk",
          "domain:sa.bbc.co.uk",
          "domain:www.bbc.co.uk",
          "domain:crunchyroll.com",
          "domain:ifconfig.co",
          "domain:omtrdc.net",
          "domain:sling.com",
          "domain:movetv.com",
          "domain:gamer2-cds.cdn.hinet.net",
          "domain:gamer-cds.cdn.hinet.net",
          "domain:gamer.com.tw",
          "domain:ani.gamer.com.tw",
          "domain:i2.bahamut.com.tw",
          "domain:app-measurement.com",
          "domain:api.gamer.com.tw",
          "domain:abema.tv" ,
          "domain:abema.io" ,
          "domain:ameba.jp",
          "domain:hayabusa.io",
          "domain:bilibili.com"
        ]
    }
  ]
},

这些都是常见的流媒体域名  希望大佬添加这个实用功能来实现低成本服务器观看流媒体

**Comment by RManLuo** [comment]
RTFM
https://crackair.gitbook.io/xrayr-project/gong-neng-shuo-ming/dns

**Comment by steamsv** [comment]
@EvvySiur 去眼科
