### ISSUE TITLE
多IP出站是怎么实现的？

### ISSUE THREAD

**Issue by newswow** [XrayR-project/XrayR#332]
请问大佬怎么实现多IP出站。

**Comment by louishot** [comment]
If there are 100 IPs on the server, multiple instances are not acceptable
https://github.com/XrayR-project/XrayR/blob/ea125e4a4fdb964487df91a6fec03476a57b20ce/service/controller/inboundbuilder.go
This must be extended to support
```
ControllerConfig:
ListenIP:
- 11.89.162.139
- 11.89.162.146
- 11.89.162.141
- 11.89.162.14
```
And use the same IP for outbound
