### ISSUE TITLE
The device limit isn't working.

### ISSUE THREAD

**Issue by sinagk2003** [XrayR-project/XrayR#333]
Hello,

I want to limit the number of devices that can connect to my server. For example, with one subscription, only two devices should be able to connect. I have set "DeviceLimit = 2", but it doesn't seem to work. When I set the limit, I can't even ping the server, websites don't open, but Telegram and Instagram work. The limit doesn't seem to be applied. Can you provide me with more guidance on this issue?

**Comment by thank243** [comment]
DeviceLimit is based on IP address. At the same IP, It couldn't effect.

**Comment by sinagk2003** [comment]
> DeviceLimit is based on IP address. At the same IP, It couldn't effect.

I want to restrict the server to only allow a maximum of 100 devices to connect. How should I configure the settings for the entire server?

**Comment by XemonDev** [comment]
Help me

**Comment by sinagk2003** [comment]
help me

**Comment by zhoushao2018** [comment]
> 设备限制基于 IP 地址。在同一个IP上，它无法生效。

之前看过解释说限制设备方式目前不现实，但是可以限制IP，那么如何限制每个用户套餐的的IP连接数量呢
