### ISSUE TITLE
各位大佬 v2board路由管理 * 出错

### ISSUE THREAD

**Issue by zhibo12** [XrayR-project/XrayR#334]
最新版的v2board 里路由管理  举例的屏蔽的*这个字符会在XrayR里报错  如 *.github.com  但是去掉这个*是正常的 并且可以正确路由

上面问题向v2board 反馈过,他们说让我这里反馈XrayR

**新手才使用不到两天 摸索都是靠搜索,其中对XrayR理解可能不透彻 有需要我的补充 可以指出来我补充  感谢**

**Comment by zhibo12** [comment]
我觉得第一二条 我可以更新xraycore 1.81版本 这个可以不用申请ssl 直接使用大厂的ssl伪装

**Comment by thank243** [comment]
Not support wildcard. The format same as local rulelist
