### ISSUE TITLE
[Feature Request] Node type hot reload & read more config from Custom Config

### ISSUE THREAD

**Issue by M1Screw** [XrayR-project/XrayR#335]
I suggest the following changes to XrayR to make it more user friendly & save operator's time:

1. XrayR should read the node type from WebAPI and hot reload if possible.

This can be a unique advantage for XrayR since it's open source & supports multiple protocols at once unlike soga you have to purchase a license for every single node type.

2. XrayR should be able to read its `ControllerConfig` part of node configuration from the custom config.

The reason behind it is pretty simple. In SSPanel's node management interface, the operator can copy & paste the custom config as a whole JSON string or duplicate the node quite easily, same can't be said for configuring the local config file on the remote node server. If the operator wants to mass change some parameter(for example change DNS provider for acme), he/she will need to login into every single node server via SSH, run `XrayR config`, and edit the file compare to just copy-paste custom config for each node.

One last thing is that XrayR should set a timeline for sunsetting the URL config method in its SSPanel connector just like the old V2Board API did. As more and more configuration has been supported, it will soon become impossible to maintain such a complex panel adapter.

**Comment by thank243** [comment]
If xr support hot reload node type from web api. It could cause this problem, the local type is still old one and it could cause some unexpected error. To support this feat, it will refactor whole startup steps.
open `ControllerConfig` is in schedule.

**Comment by M1Screw** [comment]
> the local type is still old one and it could cause some unexpected error

This issue alone can be solved by adding a "remote override" option in the configuration file, the operator can choose to prioritize remote or local config for each node, thus avoiding the conflict of config error.
