### ISSUE TITLE
Tunnel UDP over TCP

### ISSUE THREAD

**Issue by TheArshiyan** [XrayR-project/XrayR#339]
Hello there,

I've noticed that we can configure BadUDP and TCP FastOpen in xray-core but I don't see any options related to these features in XrayR,
Can you please provide more information about the ways that we can transmit udp over tcp in xrayR?

Regards

**Comment by TheArshiyan** [comment]
@thank243

**Comment by thank243** [comment]
uot is a client feat not server side.
