### ISSUE TITLE
1.6V2B面板迁移在新服务器1.73面板对接V2Bboard报错

### ISSUE THREAD

**Issue by zhoushao2018** [XrayR-project/XrayR#345]
密匙网址啥的都是对的
没迁移之前对接配置都一样不会报错
迁移后对接就这样子了
环境除了数据库5.6变成5.7 其他没变化
报错提示这字符不知道啥意思求大佬解答

May 06 16:17:33 89-40-142-253 XrayR[674773]: XrayR 0.9.0 (A Xray backend that supports many panels)
May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 Start the panel..
May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 Xray Core Version: 1.7.5
May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 [Warning] core: Xray 1.7.5 started
May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 Panel Start fialed: request https://test.xxxxxxxxx.org/api/v1/server/UniProxy/user failed: {
May 06 16:17:33 89-40-142-253 XrayR[674773]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
May 06 16:17:33 89-40-142-253 XrayR[674773]: }, <nil>
May 06 16:17:33 89-40-142-253 XrayR[674773]: panic: Panel Start fialed: request https://test.xxxxxxx.org/api/v1/server/UniProxy/user failed: {
May 06 16:17:33 89-40-142-253 XrayR[674773]:     "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"
May 06 16:17:33 89-40-142-253 XrayR[674773]: }, <nil>
May 06 16:17:33 89-40-142-253 XrayR[674773]: goroutine 1 [running]:
May 06 16:17:33 89-40-142-253 XrayR[674773]: log.Panicf({0x3283dcd?, 0x37065e0?}, {0xc000e6fe80?, 0xc000cd4200?, 0x2b3a6c0?})
May 06 16:17:33 89-40-142-253 XrayR[674773]:         log/log.go:391 +0x67
May 06 16:17:33 89-40-142-253 XrayR[674773]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005b9500)
May 06 16:17:33 89-40-142-253 XrayR[674773]:         github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b
May 06 16:17:33 89-40-142-253 XrayR[674773]: main.main()
May 06 16:17:33 89-40-142-253 XrayR[674773]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250

![image](https://user-images.githubusercontent.com/63604074/236640962-1b6275d9-6925-406e-ab15-f17fecb12115.png)

![image](https://user-images.githubusercontent.com/63604074/236640728-01331279-167e-4e8f-abd5-629c59e1b7b0.png)

**Comment by yaoyao1128** [comment]
`"message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"` -> 遇到了些问题，我们正在进行处理

https://xrayr-project.github.io/XrayR-doc/dui-jie-v2board/v2board.html

> v2board 版本 >= [1.7.0](https://github.com/v2board/v2board/releases/tag/1.7.0)请选择 "NewV2board"
> 其他版本选择 "V2board"，注意老版本API将于 2023.6.1后移除。

**Comment by zhoushao2018** [comment]
> `"message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406"`-> 遇到了些问题，我们正在进行处理
> 
> https://xrayr-project.github.io/XrayR-doc/dui-jie-v2board/v2board.html
> 
> > v2board 版本 >= [1.7.0](https://github.com/v2board/v2board/releases/tag/1.7.0)请选择 “NewV2board” 其他版本选择 “V2board”，注意老版本API将于 2023.6.1后移除。

大佬 这个提示没明白，我安装的最新版是1.7.3，写的就是NewV2board，不是符合文档上的要求嘛，为什么会报错

**Comment by thank243** [comment]
v2b 1.7.4 + xrayr 0.9.0 is working. You should confirm the node have valid user first.

**Comment by godjiu** [comment]
> 密匙网址啥的都是对的 没迁移之前对接配置都一样不会报错 迁移后对接就这样子了 环境除了数据库5.6变成5.7 其他没变化 报错提示这字符不知道啥意思求大佬解答
> 
> May 06 16:17:33 89-40-142-253 XrayR[674773]: XrayR 0.9.0 (A Xray backend that supports many panels) May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 Start the panel.. May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 Xray Core Version: 1.7.5 May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 [Warning] core: Xray 1.7.5 started May 06 16:17:33 89-40-142-253 XrayR[674773]: 2023/05/06 16:17:33 Panel Start fialed: request https://test.xxxxxxxxx.org/api/v1/server/UniProxy/user failed: { May 06 16:17:33 89-40-142-253 XrayR[674773]: "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406" May 06 16:17:33 89-40-142-253 XrayR[674773]: }, May 06 16:17:33 89-40-142-253 XrayR[674773]: panic: Panel Start fialed: request https://test.xxxxxxx.org/api/v1/server/UniProxy/user failed: { May 06 16:17:33 89-40-142-253 XrayR[674773]: "message": "\u9047\u5230\u4e86\u4e9b\u95ee\u9898\uff0c\u6211\u4eec\u6b63\u5728\u8fdb\u884c\u5904\u7406" May 06 16:17:33 89-40-142-253 XrayR[674773]: }, May 06 16:17:33 89-40-142-253 XrayR[674773]: goroutine 1 [running]: May 06 16:17:33 89-40-142-253 XrayR[674773]: log.Panicf({0x3283dcd?, 0x37065e0?}, {0xc000e6fe80?, 0xc000cd4200?, 0x2b3a6c0?}) May 06 16:17:33 89-40-142-253 XrayR[674773]: log/log.go:391 +0x67 May 06 16:17:33 89-40-142-253 XrayR[674773]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005b9500) May 06 16:17:33 89-40-142-253 XrayR[674773]: github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b May 06 16:17:33 89-40-142-253 XrayR[674773]: main.main() May 06 16:17:33 89-40-142-253 XrayR[674773]: github.com/XrayR-project/XrayR/main/main.go:97 +0x250
> 
> ![image](https://user-images.githubusercontent.com/63604074/236640962-1b6275d9-6925-406e-ab15-f17fecb12115.png)
> 
> ![image](https://user-images.githubusercontent.com/63604074/236640728-01331279-167e-4e8f-abd5-629c59e1b7b0.png)

大佬，解决了吗？遇到跟你一样的问题了。。。求教
