### ISSUE TITLE
[Bug] 关于 XrayR 适配最新版 SSpanel WebAPI 的问题

### ISSUE THREAD

**Issue by f3j43fz** [XrayR-project/XrayR#348]
SSpanel 2023.2 版本 已经[移除](https://wiki.sspanel.org/#/webapi?id=%e5%bc%83%e7%94%a8%e7%9a%84%e5%8a%9f%e8%83%bd)了部分WebAPI ，如 /nodes/{id}/info ，目前使用 xrayr 对接 sspanel 时，会报错如下：

XrayR[9135]: panic: Panel Start fialed: request https://yoursite.com/mod_mu/nodes/1/info failed: {"ret":0,"data":"Invalid request."}, %!s(<nil>)

故，希望XrayR开发者可以跟进。谢谢。

**Comment by yaoyao1128** [comment]
**NOT A BUG**
根据 sspanel 的代码看，删除是出现在 [routes.php blame](https://github.com/Anankke/SSPanel-Uim/blame/c22604cc20d618c432bd38507dfa68d849642261/app/routes.php) 但是删除的只是 `/nodes`的请求，`/mod_mu/nodes/%d/info` 在现在的 [routes.php](https://github.com/Anankke/SSPanel-Uim/blob/c22604cc20d618c432bd38507dfa68d849642261/app/routes.php#LL264C8-L264C40) 中是正确的请求。

并且现在你的返回已经是标准的 json 了，是已经经过`Controllers/WebAPI/NodeController.php` 处理过的返回了，这建议重新查看是配置文件的什么问题。

如果节点不存在 返回应该是  `ret {"ret":0,"data":null} `
如果Key错误之类的，才是这个返回
如果路由不存在，返回应该是404

**Comment by M1Screw** [comment]
> 根据 sspanel 的代码看，删除是出现在 [routes.php blame](https://github.com/Anankke/SSPanel-Uim/blame/c22604cc20d618c432bd38507dfa68d849642261/app/routes.php) 但是删除的只是 /nodes的请求，/mod_mu/nodes/%d/info 在现在的 [routes.php](https://github.com/Anankke/SSPanel-Uim/blob/c22604cc20d618c432bd38507dfa68d849642261/app/routes.php#LL264C8-L264C40) 中是正确的请求。

**Comment by M1Screw** [comment]
> 根据 sspanel 的代码看，删除是出现在 [routes.php blame](https://github.com/Anankke/SSPanel-Uim/blame/c22604cc20d618c432bd38507dfa68d849642261/app/routes.php) 但是删除的只是 /nodes的请求，/mod_mu/nodes/%d/info 在现在的 [routes.php](https://github.com/Anankke/SSPanel-Uim/blob/c22604cc20d618c432bd38507dfa68d849642261/app/routes.php#LL264C8-L264C40) 中是正确的请求。

這個其實不完全對，被刪除且會導致 XrayR 報錯的 WebAPI 路由是 POST /nodes/{id}/info，即舊版本中上報節點性能狀態的功能，而 XrayR 正常啓動需要讀取的是 GET /nodes/{id}/info 其返回資料中的 custom config。 

雖然這個報錯不會導致節點無法正常拉取資料（不像隔壁某付費後端），但還是希望 @pocketW 能儘快做一下適配，畢竟這個不涉及任何新的代碼，唯一要做的只是加個版本判斷和額外的錯誤處理避免直接報錯。

**Comment by thank243** [comment]
Could you provide any ret data?

**Comment by M1Screw** [comment]
> Could you provide any ret data?

Please find the list of departed WebAPI and its path in the [Wiki](https://wiki.sspanel.org/#/webapi?id=%e5%bc%83%e7%94%a8%e7%9a%84%e5%8a%9f%e8%83%bd), and no, there is no ret data, use those paths will result in either HTTP 404 or HTTP 405 error.

Here is an example of what the error log looks like in journalctl:

```
May 13 00:00:41 service XrayR[903]: 2023/05/13 00:00:41 request https://test.sspanel.org/mod_mu/nodes/49/info failed: <!DOCTYPE HTML>
May 13 00:00:41 service XrayR[903]: <html lang="zh">
May 13 00:00:41 service XrayR[903]: <head>
May 13 00:00:41 service XrayR[903]:     <meta charset="UTF-8">
May 13 00:00:41 service XrayR[903]:     <meta name="robots" content="noindex">
May 13 00:00:41 service XrayR[903]:     <title>Method Not Allowed - SSPanel</title>
May 13 00:00:41 service XrayR[903]:     <link rel="shortcut icon" href="/favicon.ico"/>
May 13 00:00:41 service XrayR[903]:     <link rel="bookmark" href="/favicon.ico" type="image/x-icon"/>
May 13 00:00:41 service XrayR[903]:     <link rel="stylesheet" href="/assets/css/error-pages.min.css"/>
May 13 00:00:41 service XrayR[903]: </head>
May 13 00:00:41 service XrayR[903]: <body>
May 13 00:00:41 service XrayR[903]: <div class="container">
May 13 00:00:41 service XrayR[903]:     <div class="copy-container center-xy">
May 13 00:00:41 service XrayR[903]:         <p>
May 13 00:00:41 service XrayR[903]:             405, Method Not Allowed.
May 13 00:00:41 service XrayR[903]:         </p>
May 13 00:00:41 service XrayR[903]:     </div>
May 13 00:00:41 service XrayR[903]: </div>
May 13 00:00:41 service XrayR[903]: </body>
May 13 00:00:41 service XrayR[903]: </html>
May 13 00:00:41 service XrayR[903]: , %!s(<nil>)
```

**Comment by M1Screw** [comment]
@thank243 You may want to tag a release with this fix included since 0.9.0 is the default version installed by your turnkey script, otherwise user will need to swap out the bin to be able to connect to the latest SSPanel-UIM release.
