### ISSUE TITLE
xtls-rprx-splice

### ISSUE THREAD

**Issue by jack338c** [XrayR-project/XrayR#349]
@thank243  hello Master
Dose following are all supported by panel ? currently I'm using 4 
and wihch one would be better ?
thank you

`
1 H2@reality
2 xtls-vision@reality
3 xtls-splice
4 xtls-direct
5 xtls-vision
6 tls
7 wss
8 quic
`

**Comment by thank243** [comment]
any tls over tls can be detect. Due to first packet feature.

**Comment by jack338c** [comment]
thank you !
