### ISSUE TITLE
[x509: certificate is valid for DOMAIN1, not DOMAIN2]

### ISSUE THREAD

**Issue by MrVb0** [XrayR-project/XrayR#350]
Hello good time . I hope you are well
Thanks for your hard work and effort for this valuable and powerful script
I have a problem with my xrayr servers
This error is repeated in the log many times every second and the connection is unstable (but it works).

`app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [x509: certificate is valid for (DOMAIN1), not (DOMAIN2)] > common/retry: all retry attempts failed`

I have this problem on all servers and I get this error .

In this server, I considered a normal **vless reality** configuration for outbound, and **_(DOMAIN2)_** is my **dest reality**
and Not sure what **_(DOMAIN1)_** was.

This configuration works , But I feel that this error is the main reason for the unstable connection .

**Comment by MrVb0** [comment]
Some errors are as follows:
`app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp SERVER-IP:443: operation was canceled] > common/retry: all retry attempts failed`

**Comment by MrVb0** [comment]
I am asking you dear dignitaries to guide and help me if possible.
@thank243 @pocketW

**Comment by thank243** [comment]
Fellow user guide.
