### ISSUE TITLE
能支持trojan-go嘛大佬!!!

### ISSUE THREAD

**Issue by sleeeeeeepa** [XrayR-project/XrayR#351]

**Comment by thank243** [comment]
Does trojan-go have some specail feat than xray-core provided?

**Comment by sakzri** [comment]
> Does trojan-go have some specail feat than xray-core provided?

目前xrayr支持trojan + ws协议吗，想在v2board使用，看了文档，没找到怎么使用的方法

**Comment by thank243** [comment]
> > Does trojan-go have some specail feat than xray-core provided?
> 
> 目前xrayr支持trojan + ws协议吗，想在v2board使用，看了文档，没找到怎么使用的方法

the panel is not supported does not mean that xr is not supported.
