### ISSUE TITLE
up：我替换了Actions最新编译，xtls-rprx-vision不被支持is not able to use xtls-rprx-vision

### ISSUE THREAD

**Issue by ckaak** [XrayR-project/XrayR#357]
xtls-rprx-vision流控不被支持，但Reality是可用，xtls-rprx-vision还是被xray内核支持

up日志报错：app/proxyman/inbound: connection ends > proxy/vless/inbound: xxxxxxxxxxxxxx is not able to use xtls-rprx-vision

**Comment by OPPO9008** [comment]
> XTLS Vision流控不被支持，但Reality是可用，XTLS Vision还是被xray内核支持，可以再加上吗？

是TLS Vision ，另外订阅下发要修改

**Comment by ckaak** [comment]
> > XTLS Vision流控不被支持，但Reality是可用，XTLS Vision还是被xray内核支持，可以再加上吗？
> 
> 是TLS Vision ，另外订阅下发要修改

手动改了，日志查看了是启动的vless，但是报错xtls-rprx-vision不存在还是不支持？？

**Comment by miyling** [comment]
问题在于新建VLESS用户时，当前是默认的Flow为

**Comment by miyling** [comment]
xray最新的代码已经不支持flow多项，所以现有VLESS用户的Flow`xtls-rprx-vision,none`导致了xtls-rprx-vision被xray拦截。是否应当根据下发的Flow来指定VLESS用户的Flow

https://github.com/XrayR-project/XrayR/blob/223589ba14b392294986dc6e96f9bea76cbe31d7/service/controller/userbuilder.go#LL50C34-L50C34

https://github.com/XTLS/Xray-core/blob/5f5ae375714abd67eb2f0a0f2e86410b6f29f7c2/proxy/vless/inbound/inbound.go#L457

**Comment by WayChan** [comment]
> xray最新的代码已经不支持flow多项，所以现有VLESS用户的Flow`xtls-rprx-vision,none`导致了xtls-rprx-vision被xray拦截。是否应当根据下发的Flow来指定VLESS用户的Flow
> 
> https://github.com/XrayR-project/XrayR/blob/223589ba14b392294986dc6e96f9bea76cbe31d7/service/controller/userbuilder.go#LL50C34-L50C34
> 
> https://github.com/XTLS/Xray-core/blob/5f5ae375714abd67eb2f0a0f2e86410b6f29f7c2/proxy/vless/inbound/inbound.go#L457

EnableXTLS: true 这个字段似乎被移除了，默认会使用TLS，即使基于最新的代码单独配置了xtls-rprx-vision也依然无法正常使用。

**Comment by miyling** [comment]
> > xray最新的代码已经不支持flow多项，所以现有VLESS用户的Flow`xtls-rprx-vision,none`导致了xtls-rprx-vision被xray拦截。是否应当根据下发的Flow来指定VLESS用户的Flow
> > https://github.com/XrayR-project/XrayR/blob/223589ba14b392294986dc6e96f9bea76cbe31d7/service/controller/userbuilder.go#LL50C34-L50C34
> > https://github.com/XTLS/Xray-core/blob/5f5ae375714abd67eb2f0a0f2e86410b6f29f7c2/proxy/vless/inbound/inbound.go#L457
> 
> 即使基于最新的代码单独配置了xtls-rprx-vision似乎也依然无法正常使用。不知道哪里可以看到xrayr 生成的最终json

作者昨天修改以后，我这边reality+xtls-rprx-vision已正常

**Comment by thank243** [comment]
> > > xray最新的代码已经不支持flow多项，所以现有VLESS用户的Flow`xtls-rprx-vision,none`导致了xtls-rprx-vision被xray拦截。是否应当根据下发的Flow来指定VLESS用户的Flow
> > > https://github.com/XrayR-project/XrayR/blob/223589ba14b392294986dc6e96f9bea76cbe31d7/service/controller/userbuilder.go#LL50C34-L50C34
> > > https://github.com/XTLS/Xray-core/blob/5f5ae375714abd67eb2f0a0f2e86410b6f29f7c2/proxy/vless/inbound/inbound.go#L457
> > 
> > 
> > 即使基于最新的代码单独配置了xtls-rprx-vision似乎也依然无法正常使用。不知道哪里可以看到xrayr 生成的最终json
> 
> 作者昨天修改以后，我这边reality+xtls-rprx-vision已正常，xrayr是通过程序直接内部调用的xray，并不存在配置xray的json

Have any bugs in the latest version?

**Comment by miyling** [comment]
> > > > xray最新的代码已经不支持flow多项，所以现有VLESS用户的Flow`xtls-rprx-vision,none`导致了xtls-rprx-vision被xray拦截。是否应当根据下发的Flow来指定VLESS用户的Flow
> > > > https://github.com/XrayR-project/XrayR/blob/223589ba14b392294986dc6e96f9bea76cbe31d7/service/controller/userbuilder.go#LL50C34-L50C34
> > > > https://github.com/XTLS/Xray-core/blob/5f5ae375714abd67eb2f0a0f2e86410b6f29f7c2/proxy/vless/inbound/inbound.go#L457
> > > 
> > > 
> > > 即使基于最新的代码单独配置了xtls-rprx-vision似乎也依然无法正常使用。不知道哪里可以看到xrayr 生成的最终json
> > 
> > 
> > 作者昨天修改以后，我这边reality+xtls-rprx-vision已正常，xrayr是通过程序直接内部调用的xray，并不存在配置xray的json
> 
> Have any bugs in the latest version?

0bec6c4fdfa19771d9980043e35a18005ca651a9
我目前使用的版本是基于上面提交构建的镜像，没有问题。最新版的还没更新，应当是没有问题的。我一会更新一下再来回复

**Comment by WayChan** [comment]
> > > > > xray最新的代码已经不支持flow多项，所以现有VLESS用户的Flow`xtls-rprx-vision,none`导致了xtls-rprx-vision被xray拦截。是否应当根据下发的Flow来指定VLESS用户的Flow
> > > > > https://github.com/XrayR-project/XrayR/blob/223589ba14b392294986dc6e96f9bea76cbe31d7/service/controller/userbuilder.go#LL50C34-L50C34
> > > > > https://github.com/XTLS/Xray-core/blob/5f5ae375714abd67eb2f0a0f2e86410b6f29f7c2/proxy/vless/inbound/inbound.go#L457
> > > > 
> > > > 
> > > > 即使基于最新的代码单独配置了xtls-rprx-vision似乎也依然无法正常使用。不知道哪里可以看到xrayr 生成的最终json
> > > 
> > > 
> > > 作者昨天修改以后，我这边reality+xtls-rprx-vision已正常，xrayr是通过程序直接内部调用的xray，并不存在配置xray的json
> > 
> > 
> > Have any bugs in the latest version?
> 
> [0bec6c4](https://github.com/XrayR-project/XrayR/commit/0bec6c4fdfa19771d9980043e35a18005ca651a9) 我目前使用的版本是基于上面提交构建的镜像，没有问题。最新版的还没更新，应当是没有问题的。我一会更新一下再来回复
> 
> append: 最新版存在问题，似乎配置文件内的VlessFlow没有被应用到api.NodeInfo中

看起来是确实是没有被应用

**Comment by thank243** [comment]
https://github.com/XrayR-project/XrayR/commit/4ab196ad298803810274a10d12ad4efacc4d4a1b
It should work.

**Comment by miyling** [comment]
> [4ab196a](https://github.com/XrayR-project/XrayR/commit/4ab196ad298803810274a10d12ad4efacc4d4a1b) It should work.

https://github.com/XrayR-project/XrayR/blob/4ab196ad298803810274a10d12ad4efacc4d4a1b/api/sspanel/sspanel.go#L721

当使用sspanel custom_json时，似乎未应用VlessFlow

**Comment by thank243** [comment]
> > [4ab196a](https://github.com/XrayR-project/XrayR/commit/4ab196ad298803810274a10d12ad4efacc4d4a1b) It should work.
> 
> https://github.com/XrayR-project/XrayR/blob/4ab196ad298803810274a10d12ad4efacc4d4a1b/api/sspanel/sspanel.go#L721
> 
> 当使用sspanel custom_json时，似乎未应用VlessFlow

https://github.com/XrayR-project/XrayR/commit/4f13aac094c4c69742e779b249e45379537466cf

**Comment by miyling** [comment]
最新代码已正常应用reality+xtls-rprx-vision
