### ISSUE TITLE
后台显示XrayR已正常连接，客户端vmess测试延迟-1

### ISSUE THREAD

**Issue by Simonaorg** [XrayR-project/XrayR#367]
XrayR 配置文件只修改了 ApiHost，ApiKey，NodeID（sspanel面板），IP和端口均未被屏蔽，用户账号在有效期内。

客户端提示代码：
[Warning] [2710284752] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: failed to find an available destination > common/retry: [transport/internet/websocket: failed to dial WebSocket > transport/internet/websocket: failed to dial to (wss://domain.com:23005/M5pb0ldOH):  > dial tcp IP:23005: connectex: No connection could be made because the target machine actively refused it.] > common/retry: all retry attempts failed

**Comment by thank243** [comment]
Ref: User guide doc.
