### ISSUE TITLE
Xrayr v2ray 报错

### ISSUE THREAD

**Issue by LouisTomson** [XrayR-project/XrayR#390]
请问xrayr v2ray plugin 下发配置报错是什么原因？这块该如何写？有文档可以参考吗？
json数据：
{"ret":1,"data":{"node_group":0,"node_class":0,"node_speedlimit":0,"traffic_rate":1,"mu_only":-1,"sort":13,"server":"23.95.234.125;10200;1;ws;tls;path=\/download|host=testrn.djj.me|server=testrn.djj.me;","type":"ss-panel-v3-mod_Uim"}}

报错如下
XrayR 0.9.0 (A Xray backend that supports many panels)
Jun 19 17:59:59 racknerd XrayR[104846]: 2023/06/19 17:59:59 Start the panel..
Jun 19 17:59:59 racknerd XrayR[104846]: 2023/06/19 17:59:59 Xray Core Version: 1.7.5
Jun 19 17:59:59 racknerd XrayR[104846]: 2023/06/19 17:59:59 [Debug] app/log: Logger started
Jun 19 17:59:59 racknerd XrayR[104846]: 2023/06/19 17:59:59 [Info] app/dns: DNS: created localhost client
Jun 19 17:59:59 racknerd XrayR[104846]: 2023/06/19 17:59:59 [Warning] core: Xray 1.7.5 started
Jun 19 17:59:59 racknerd XrayR[104846]: 2023/06/19 17:59:59 infra/conf: unknown cipher method:
Jun 19 17:59:59 racknerd XrayR[104846]: panic: infra/conf: unknown cipher method:
Jun 19 17:59:59 racknerd XrayR[104846]: goroutine 1 [running]:
Jun 19 17:59:59 racknerd XrayR[104846]: log.Panic({0xc000917d28?, 0xc000172d20?, 0xc000917d58?})
Jun 19 17:59:59 racknerd XrayR[104846]:         log/log.go:384 +0x65
Jun 19 17:59:59 racknerd XrayR[104846]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00091a600)
Jun 19 17:59:59 racknerd XrayR[104846]:         github.com/XrayR-project/XrayR/service/controller/controller.go:84 +0x27f
Jun 19 17:59:59 racknerd XrayR[104846]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00056f200)
Jun 19 17:59:59 racknerd XrayR[104846]:         github.com/XrayR-project/XrayR/panel/panel.go:209 +0x556
Jun 19 17:59:59 racknerd XrayR[104846]: main.main()
Jun 19 17:59:59 racknerd XrayR[104846]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x250
Jun 19 17:59:59 racknerd systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 19 17:59:59 racknerd systemd[1]: XrayR.service: Failed with result 'exit-code'.

请问什么问题呢

**Comment by thank243** [comment]
unknown cipher method
