### ISSUE TITLE
能否像Xray一样配置服务端机器流量出口规则呢?

### ISSUE THREAD

**Issue by tanpengsccd** [XrayR-project/XrayR#40]
比如我想:
奈非 走 IPv6.
动画疯走 另一台落地机.

**Comment by crackair** [comment]
@tanpengsccd 暂不支持

**Comment by tanpengsccd** [comment]
可以用自定义DNS实现解锁:
https://crackair.gitbook.io/xrayr-project/gong-neng-shuo-ming/dns

文档 建议加个注意点点 
```
5. DNSType 需要使用 UseIP,UseIPv4,UseIPv6才能使用自定义DNS
```
