### ISSUE TITLE
H2 not working

### ISSUE THREAD

**Issue by TheArshiyan** [XrayR-project/XrayR#400]
Hello there,
We are passing this config to XrayR for using Vless,H2,Reality.
But it's not working at all and we are getting EOF error.
Here is the json that we pass:
`{
    "server_port": 443,
    "network": "h2",
    "networkSettings": {
        "alpn": [
            "h2"
        ],
        "path": "/"
    },
    "tls": 1
}`
All configurations are correct on server side (reality sid,server name, panel connectivity and ...). also tcp reality is working fine.

Can you please take a look and help us? @thank243 

Best Regards,
A9

**Comment by thank243** [comment]
Can you use the same config on xray-core and get it works?

**Comment by TheArshiyan** [comment]
@thank243 
I'm sending this json config to XrayR with v2board.
in xray-core I use this config and it's working fine (https://github.com/chika0801/Xray-examples/blob/main/VLESS-H2-uTLS-REALITY/config_server.json)
The problem is that I don't know if I'm sending the correct json config from v2board to XrayR instance. (Using latest XrayR version that I compiled my self)
I've tried multiple ways :
changing network to h2,
removing alpn and ... 
but they didn't work.

**Comment by thank243** [comment]
Is v2board support h2 network type? I just see tcp/ws/grpc.

**Comment by TheArshiyan** [comment]
@thank243 
I've added custom protocols and modifications to v2board myself, the only problem that I have is that I'm sending H2 network type to XrayR but it doesn't work, maybe XrayR can't understand it? idk.
I've sent you the example json that I'm passing to XrayR for h2.
please tell me if I need to modify something in this scenario

**Comment by thank243** [comment]
We cannot add this feat if the official doesn't support it.

**Comment by theresaarcher** [comment]
encountered the related problem again
