### ISSUE TITLE
对接Shadowsocks - V2Ray-Plugin时，服务端报错

### ISSUE THREAD

**Issue by zhugelail1998** [XrayR-project/XrayR#407]
XrayR 0.9.0 (A Xray backend that supports many panels) 
2023/07/10 20:49:04 Start the panel..
2023/07/10 20:49:04 Xray Core Version: 1.7.5
2023/07/10 20:49:05 infra/conf: unknown cipher method: 
panic: infra/conf: unknown cipher method: 

goroutine 1 [running]:
log.Panic({0xc001257d28?, 0xc000172d20?, 0xc001257d58?})
	log/log.go:384 +0x65
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000daa400)
	github.com/XrayR-project/XrayR/service/controller/controller.go:84 +0x27f
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005b1280)
	github.com/XrayR-project/XrayR/panel/panel.go:209 +0x556
main.main()
	github.com/XrayR-project/XrayR/main/main.go:97 +0x250

**Comment by zhugelail1998** [comment]
加密是aes-256-gcm

**Comment by thank243** [comment]
Can u provide any panel json data which send to xr?

**Comment by zhugelail1998** [comment]
> 
      NodeType: Shadowsocks-Plugin # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 127.0.0.1 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by zhugelail1998** [comment]
> Can u provide any panel json data which send to xr?
Whether only support SSPanel Custom Config？

**Comment by zhugelail1998** [comment]
> Can u provide any panel json data which send to xr?

Two arguments(CypherMethod and ServerKey) are missing from the return of this method(ParseSSPluginNodeResponse),it Could be the cause of this error

**Comment by zhugelail1998** [comment]
close
