### ISSUE TITLE
希望一台机器的XrayR能绑多个域名

### ISSUE THREAD

**Issue by crazysvn** [XrayR-project/XrayR#419]
这样就能一个域名的直连，另外的可套CDN或者套IPLC啥的，这样让一台机器在平时能尽量快速，而在被封时戴了套的能立即顶上。当然，也可新开节点来达到目的，但是成本就要多一些了。

**Comment by thh1451** [comment]
Keyword: pan-domain certificate

**Comment by crazysvn** [comment]
> 

光证书可重复还不行的吧？xrayr配置里好像只支持填一个NodeID，而面板里每个域名应该是要对应不同的NodeID的

**Comment by crazysvn** [comment]
> Keyword: pan-domain certificate

@thh1451 

光证书可重复还不行的吧？xrayr配置里好像只支持填一个NodeID，而面板里每个域名应该是要对应不同的NodeID的

**Comment by crazysvn** [comment]
确实可以。是我孤陋了。。
