### ISSUE TITLE
v2board怎么审计

### ISSUE THREAD

**Issue by ymlsn** [XrayR-project/XrayR#42]
前端设置的审计规则没用

**Comment by RManLuo** [comment]
请确认客户端上传了域名，如果客户端本地解析域名，只上传IP，请用I添加P地址的正则表达式进行审计。

**Comment by thank243** [comment]
针对域名只有使用RuleListPath来本地做，geosite之类的只能做到RouteConfigPath里。RouteConfigPath包括了RuleListPath，RuleListPath只是相当于简化设置来用。
