### ISSUE TITLE
后端未知错误

### ISSUE THREAD

**Issue by zesty-zesty** [XrayR-project/XrayR#434]
**Brief：**控制台打印了一串信息后就没有任何反应了，log也没有任何输出。
**前端：**SSPanel UIM 2023.4
**后端：**XrayR 8/6或者8/7的某commit
**控制台打印的信息：**
2023/08/09 22:26:08 Start the panel..
2023/08/09 22:26:08 Xray Core Version: 1.8.3
2023/08/09 22:26:08 [https://my.philrech.com:667] V2ray(ID=2) Added 2 new users
2023/08/09 22:26:08 [https://my.philrech.com:667] V2ray(ID=2) Start node monitor periodic task
2023/08/09 22:26:08 [https://my.philrech.com:667] V2ray(ID=2) Start user monitor periodic task
REALITY remoteAddr: ----------------:11400
REALITY remoteAddr: ----------------:11400	hs.c.AuthKey[:16]: [114 149 157 228 218 7 26 73 237 127 71 22 54 170 152 113]	AEAD: *aes.gcmAsm
REALITY remoteAddr: ----------------:11400	hs.c.ClientVer: [1 8 1]
REALITY remoteAddr: ----------------:11400	hs.c.ClientTime: 2023-08-09 22:26:15 +0800 CST
REALITY remoteAddr: ----------------:11400	hs.c.ClientShortId: [107 168 81 121 227 13 79 194]
REALITY remoteAddr: ----------------:11400	hs.c.conn == conn: true
REALITY remoteAddr: ----------------:11400	len(s2cSaved): 4550	Server Hello: 127
REALITY remoteAddr: ----------------:11400	len(s2cSaved): 4423	Change Cipher Spec: 6
REALITY remoteAddr: ----------------:11400	len(s2cSaved): 4417	Encrypted Extensions: 41
REALITY remoteAddr: ----------------:11400	len(s2cSaved): 4376	Certificate: 4016
REALITY remoteAddr: ----------------:11400	len(s2cSaved): 360	Certificate Verify: 286
REALITY remoteAddr: ----------------:11400	len(s2cSaved): 74	Finished: 74
REALITY remoteAddr: ----------------:11400	hs.handshake() err: <nil>
REALITY remoteAddr: ----------------:11400	hs.readClientFinished() err: <nil>
REALITY remoteAddr: ----------------:11400	handled: true
**XrayR config**
Log:
  Level: debug # Log level: none, error, warning, info, debug 
  AccessPath:  /www/XrayR/XrayR/log/access.Log
  ErrorPath:  /www/XrayR/XrayR/log/error.log
DnsConfigPath:
RouteConfigPath: #/www/XrayR/XrayR/main/route.json
InboundConfigPath: #/www/XrayR/XrayR/main/inbound.json
OutboundConfigPath: #/www/XrayR/XrayR/main/outbound.json

ConnectionConfig:
  Handshake: 100 # Handshake time limit, Second
  ConnIdle: 300 # Connection idle time limit, Second
  UplinkOnly: 10 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 10 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 128 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "SSpanel" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: "----------------"
      ApiKey: "-----------------"
      NodeID: 2
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      VlessFlow: #"xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: #/www/XrayR/XrayR/main/rulelist #Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: true # Enable the global device limit of a user
        RedisAddr: 0.0.0.0:6379 # The redis server address
        RedisPassword: Zesty050615 # Redis password
        RedisDB: 1 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: www.yahoo.com # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: www.yahoo.com:443 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      EnableREALITY: true # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: proxy.evo.jpa.philrech.com:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: --------------
        PrivateKey: --------------
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 60000 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: 
         - 6ba85179e30d4fc2
      CertConfig:
        CertMode: http # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: --------------- # Domain to cert
        CertFile: #/www/XrayR/XrayR/cert/jpa.cert # Provided if the CertMode is file
        KeyFile: #/www/XrayR/XrayR/cert/jpa.key
        Provider: # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: -------------------
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: 
          ALICLOUD_SECRET_KEY: 
**协议**
Vless grpc reality

**Comment by malagebidi** [comment]
我的配置和你差不多没配置FallBack，前端是v2b，配置的是Vless+tcp+reality。我觉得在前端的节点配置里面，应该还要配置一些额外的内容比如publickey，fingerprint。期待楼下解释

**Comment by malagebidi** [comment]
xray-core配置grpc需要"network": "grpc"，但我在XrayR的配置文件里没看到这个选项，VLESS-reality-vision倒是可以成功。
