### ISSUE TITLE
can run XrayR nodes in Windows Server ?

### ISSUE THREAD

**Issue by alirezashahrokhi** [XrayR-project/XrayR#444]
hi all dears 
can run nodes in windows ?

**Comment by lipeng0820** [comment]
Yes,Run Powershell and drag XrayR.exe to Window,and Press Enter

**Comment by alirezashahrokhi** [comment]
> Yes,Run Powershell and drag XrayR.exe to Window,and Press Enter

thanks a lot 
its done
