### ISSUE TITLE
Xray-core v1.8.4

### ISSUE THREAD

**Issue by bahramini** [XrayR-project/XrayR#451]
Do we have update to new core release of [Xray-core v1.8.4]?
(https://github.com/XTLS/Xray-core/releases/tag/v1.8.4)

**Comment by thank243** [comment]
https://github.com/XrayR-project/XrayR/commit/f35a056cc612a26d098d70ab8b31d86027c40aa9

**Comment by bahramini** [comment]
i'm not professional programmer...should i compile source code and install it? or is there another way to update commits?

**Comment by thank243** [comment]
https://github.com/XrayR-project/XrayR/actions/runs/6157563141
