### ISSUE TITLE
shadowsocks error: failed to match an user > proxy/shadowsocks: Not Found

### ISSUE THREAD

**Issue by RobertHashMan** [XrayR-project/XrayR#459]
Hello,thanks for your project,but I encountered a serious problem,so I came to here:

Frontend:V2board  1.7.4;
Backend:XrayR  newest;

Problem details:
I added a user in v2board and configured many backend nodes,while I found that when I connect my proxies to some backend nodes ,some nodes  give me such error like this:  
```  
 proxy/shadowsocks: failed to match an user > proxy/shadowsocks: Not Found  
```   
some backend nodes can work normally while some not,the only difference is all of these working backend nodes are added lately compared to those not working nodes.  

and I noticed that the xrayr log reported all of these active user's number and it's correct,so I think the v2board front is working fine while xrayr gets these client infos but didn't apply them normally.  

is there any way to check all of these active clients infos in xrayr

**Comment by RobertHashMan** [comment]
Oh,I have found the problem，this error is my fault,sorry~

**Comment by Iessnice** [comment]
hi, i got the same problem with you, how did you fix it?

**Comment by poetrysun** [comment]
> 哦，我已经找到问题了，这个错误是我的错，抱歉~

"Hello, I've encountered the same issue. How did you solve it?"
