### ISSUE TITLE
自定义dns问题

### ISSUE THREAD

**Issue by jue0115** [XrayR-project/XrayR#46]
SendIP: "::"
EnableDNS: true
DNSType: UseIP
dns.json指定一个域名到V4的地址(比如google该域名有A和AAAA地址,xx.xx.xx.xx只会解析出来谷歌的A地址)
    "servers": [
        "1.1.1.1",
        {
        "address": "xx.xx.xx.xx",
        "domains": [
          "geosite:google"
          ]
        }
    ],
他会丢弃这个解析出来的IP然后使用系统dns去重新查询然后使用AAAA地址
反之：EnableDNS: true,DNSType: UseIP,会丢弃AAAA地址 重新去系统dns查询，获取的A和AAAA，会使用A地址。

**Comment by crackair** [comment]
@jue0115 在enabledns且dnstype为useip时，解析的ip优先级以出口ip为准，出口ip为0.0.0.0优先ipv4，: : 时优先ipv6。

**Comment by RManLuo** [comment]
如果设置优先v6，那解析出来v6地址就会优先使用v6，暂时无法支持不同域名设置不同解析策略。

**Comment by RManLuo** [comment]
fab095b22cd62a59bf49ae94eaf991fe9aa8beab
