### ISSUE TITLE
是否能让node标记tag

### ISSUE THREAD

**Issue by qiuzi** [XrayR-project/XrayR#464]
使用双栈warp对某些节点隐藏IP，但又存在多个节点的主机开如何配置？

**Comment by thank243** [comment]
https://xrayr-project.github.io/XrayR-doc/gong-neng-shuo-ming/zi-ding-yi-lu-you-gong-neng-shuo-ming.html

**Comment by qiuzi** [comment]
@thank243 听说获取配置后会自动生成一个tag，但具体如何知道？
