### ISSUE TITLE
Issue & Suggestion concerning global IP limit

### ISSUE THREAD

**Issue by frainzy1477** [XrayR-project/XrayR#47]
Looking at how the IP limit is implemented, it will cause same IP on other nodes to disconnect while using same device at the same time, I suggest IP limit should be based on current IPs connected, Connected IPs can be store in a struct and if found with user connection limit not exceeding still can connect. 

For example, a user with connection limit of 1 when connected to server A will not be able to connect to server B with same IP until current connection is disconnected , causing connection break if you try to switch between servers on same device and IP.

I suggest if this current setup is to be kept, maybe at a later time cam implement the IP option as well which can be selected set in  config.yml by the user.

**Comment by RManLuo** [comment]
Thanks for your suggestion. I have suggested the sspanel to send the original online IP address rather than a simple number of the online devices in this issue Anankke/SSPanel-Uim#1264. Maybe It is a good idea to create a pr for adding this feature to sspanel.

**Comment by RManLuo** [comment]
I have reverted the commit about global devices limitation 84fb16d9, which will be added back when sspanel or other panels are ready.

**Comment by frainzy1477** [comment]
> Thanks for your suggestion. I have suggested the sspanel to send the original online IP address rather than a simple number of the online devices in this issue [Anankke/SSPanel-Uim#1264](https://github.com/Anankke/SSPanel-Uim/issues/1264). Maybe It is a good idea to create a pr for adding this feature to sspanel.

That will be great, the IPs can be sent over webapi as hash and stored to protect users IPs.

**Comment by amfiyong** [comment]
此功能还需要等待sspanel 适配吗

**Comment by crackair** [comment]
@frainzy1477 I think ip hash will be a good solution for this!

**Comment by frainzy1477** [comment]
> @frainzy1477 I think ip hash will be a good solution for this!

After several test , the simple solution to fix the ip limit is to add ->distinct('ip')  to the panel backend, the distinct make sure same IP is counted as 1 no matter the server id connected to.  I chose to use online_ip_count

User.php Model
![image](https://user-images.githubusercontent.com/49537471/133256309-178f6bc1-f03a-4ee4-854a-ed08c0d19261.png)


and for the webapi just change Alive ip to the user onlineip count

![image](https://user-images.githubusercontent.com/49537471/133256538-bc348b22-f036-48a9-b40b-c3ed2c4f7215.png)

and made few changes to XrayR to allow only the exceeded ip limit drop connection and keep the ip within the count limit connected

https://github.com/frainzy1477/XrayR/commit/ea5b63dc45017378798728e95bc2b787f65bb3ec

**Comment by RManLuo** [comment]
@frainzy1477 Thanks for your suggestion, but I think the current implementation might not solve the problem. 

First, SSpanel has already changed the way of counting online IP in this commit Anankke/SSPanel-Uim@8796132f323734a643f1141866c4c17b1550a71d, which I believe is as same as your implementation but with better database performance.

Second, when the address of the current online IP is not sent to the XrayR, it is impossible for the backend to decide whether an IP address is a new address and allow it to connect or not.

Therefore, I think the only solution is to let the panel send online IP addresses to the XrayR or let XrayR use an additional database such as Redis to globally store online IP addresses for all users.

**Comment by frainzy1477** [comment]
> @frainzy1477 Thanks for your suggestion, but I think the current implementation might not solve the problem.
> 
> First, SSpanel has already changed the way of counting online IP in this commit [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d), which I believe is as same as your implementation but with better database performance.
> 
> Second, when the address of the current online IP is not sent to the XrayR, it is impossible for the backend to decide whether an IP address is a new address and allow it to connect or not.
> 
> Therefore, I think the only solution is to let the panel send online IP addresses to the XrayR or let XrayR use an additional database such as Redis to globally store online IP addresses for all users.

Tested and it works, https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d can just add distinct to it that will solve thw issue, 

And for not knowing the ip, sure it does in the GetUserBucket, this makes sure only the number of allowed connections are online, so if connection limit is 1 and connect to PC and Phone with different IPs is counted as 2 and one device will drop connection if both same IP is counted as 1 (eg; both connected to  same wifi) . Anyway it works for me.😊
![image](https://user-images.githubusercontent.com/49537471/133265882-a34ae3de-a067-47f3-898a-774c3d036c9a.png)

**Comment by RManLuo** [comment]
> > @frainzy1477 Thanks for your suggestion, but I think the current implementation might not solve the problem.
> > First, SSpanel has already changed the way of counting online IP in this commit [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d), which I believe is as same as your implementation but with better database performance.
> > Second, when the address of the current online IP is not sent to the XrayR, it is impossible for the backend to decide whether an IP address is a new address and allow it to connect or not.
> > Therefore, I think the only solution is to let the panel send online IP addresses to the XrayR or let XrayR use an additional database such as Redis to globally store online IP addresses for all users.
> 
> Tested and it works, [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d) can just add distinct to it that will solve thw issue,
> 
> And for not knowing the ip, sure it does in the GetUserBucket, this makes sure only the number of allowed connections are online, so if connection limit is 1 and connect to PC and Phone with different IPs is counted as 2 and one device will drop connection if both same IP is counted as 1 (eg; both connected to same wifi) . Anyway it works for me.😊
> ![image](https://user-images.githubusercontent.com/49537471/133265882-a34ae3de-a067-47f3-898a-774c3d036c9a.png)

This cannot address the situation you discussed here.
> For example, a user with connection limit of 1 when connected to server A will not be able to connect to server B with same IP > until current connection is disconnected , causing connection break if you try to switch between servers on same device and IP.

If a user with connection limit of 1, when it has connected to server A with IP address X, the backend in server A will send its IP address X to the panel, and the panel will spread the online_ip_count (which is 1) to all the other backend such as server B. At this moment, the user with IP address X cannot connect to any other server, since the IPLimit in server B is 0 (deviceLimit - user.OnlineIP). He can only connect to server B when he disconnect from the server A and let the panel clear the online IP address.

**Comment by frainzy1477** [comment]
> > > @frainzy1477 Thanks for your suggestion, but I think the current implementation might not solve the problem.
> > > First, SSpanel has already changed the way of counting online IP in this commit [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d), which I believe is as same as your implementation but with better database performance.
> > > Second, when the address of the current online IP is not sent to the XrayR, it is impossible for the backend to decide whether an IP address is a new address and allow it to connect or not.
> > > Therefore, I think the only solution is to let the panel send online IP addresses to the XrayR or let XrayR use an additional database such as Redis to globally store online IP addresses for all users.
> > 
> > 
> > Tested and it works, [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d) can just add distinct to it that will solve thw issue,
> > And for not knowing the ip, sure it does in the GetUserBucket, this makes sure only the number of allowed connections are online, so if connection limit is 1 and connect to PC and Phone with different IPs is counted as 2 and one device will drop connection if both same IP is counted as 1 (eg; both connected to same wifi) . Anyway it works for me.😊
> > ![image](https://user-images.githubusercontent.com/49537471/133265882-a34ae3de-a067-47f3-898a-774c3d036c9a.png)
> 
> This cannot address the situation you discussed here.
> 
> > For example, a user with connection limit of 1 when connected to server A will not be able to connect to server B with same IP > until current connection is disconnected , causing connection break if you try to switch between servers on same device and IP.
> 
> If a user with connection limit of 1, when it has connected to server A with IP address X, the backend in server A will send its IP address X to the panel, and the panel will spread the online_ip_count (which is 1) to all the other backend such as server B. At this moment, the user with IP address X cannot connect to any other server, since the IPLimit in server B is 0 (deviceLimit - user.OnlineIP). He can only connect to server B when he disconnect from the server A and let the panel clear the online IP address.

It can if ->distinct('ip') is added to the backend, if a user with limit 1 is connected to SERVER A with IP x (count 1), and same user connected to SERVER B with same IP  x (count 1), both will count as 1 since they are of the same ip   if ->distinct('ip') is added to GetAliveIP of the backend. but if connection to SERVER A and B have different IPs is counted as 2 with ->distinct('ip'), but since user limit is 1 , one device (ip) preferably  the new ip is delete by GetUserBucket, the only pros is 1 device stay online, and cons which device disconnected cannot be 100% sure, if phone and pc, mostly pc drop connecton

PC
![Screenshot_2](https://user-images.githubusercontent.com/49537471/133271223-83b001cd-d2a2-43b3-b18f-79013aacf53e.jpg)

Phone
![Screenshot_3](https://user-images.githubusercontent.com/49537471/133271459-d5db07c1-24ec-4e33-806e-af0559802992.jpg)

**Comment by RManLuo** [comment]
> > > > @frainzy1477 Thanks for your suggestion, but I think the current implementation might not solve the problem.
> > > > First, SSpanel has already changed the way of counting online IP in this commit [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d), which I believe is as same as your implementation but with better database performance.
> > > > Second, when the address of the current online IP is not sent to the XrayR, it is impossible for the backend to decide whether an IP address is a new address and allow it to connect or not.
> > > > Therefore, I think the only solution is to let the panel send online IP addresses to the XrayR or let XrayR use an additional database such as Redis to globally store online IP addresses for all users.
> > > 
> > > 
> > > Tested and it works, [Anankke/SSPanel-Uim@8796132](https://github.com/Anankke/SSPanel-Uim/commit/8796132f323734a643f1141866c4c17b1550a71d) can just add distinct to it that will solve thw issue,
> > > And for not knowing the ip, sure it does in the GetUserBucket, this makes sure only the number of allowed connections are online, so if connection limit is 1 and connect to PC and Phone with different IPs is counted as 2 and one device will drop connection if both same IP is counted as 1 (eg; both connected to same wifi) . Anyway it works for me.😊
> > > ![image](https://user-images.githubusercontent.com/49537471/133265882-a34ae3de-a067-47f3-898a-774c3d036c9a.png)
> > 
> > 
> > This cannot address the situation you discussed here.
> > > For example, a user with connection limit of 1 when connected to server A will not be able to connect to server B with same IP > until current connection is disconnected , causing connection break if you try to switch between servers on same device and IP.
> > 
> > 
> > If a user with connection limit of 1, when it has connected to server A with IP address X, the backend in server A will send its IP address X to the panel, and the panel will spread the online_ip_count (which is 1) to all the other backend such as server B. At this moment, the user with IP address X cannot connect to any other server, since the IPLimit in server B is 0 (deviceLimit - user.OnlineIP). He can only connect to server B when he disconnect from the server A and let the panel clear the online IP address.
> 
> It can if ->distinct('ip') is added to the backend, if a user with limit 1 is connected to SERVER A with IP x (count 1), and same user connected to SERVER B with same IP x (count 1), both will count as 1 since they are of the same ip if ->distinct('ip') is added to GetAliveIP of the backend. but if connection to SERVER A and B have different IPs is counted as 2 with ->distinct('ip'), but since user limit is 1 , one device (ip) preferably the new ip is delete by GetUserBucket, the only pros is 1 device stay online, and cons which device disconnected cannot be 100% sure, if phone and pc, mostly pc drop connecton
> 
> PC
> ![Screenshot_2](https://user-images.githubusercontent.com/49537471/133271223-83b001cd-d2a2-43b3-b18f-79013aacf53e.jpg)
> 
> Phone
> ![Screenshot_3](https://user-images.githubusercontent.com/49537471/133271459-d5db07c1-24ec-4e33-806e-af0559802992.jpg)

Hi, since your calculation of IPLimit is `localDeviceLimit = deviceLimit - user.OnlineIP`, the IPLimit in server B will become 0 after you connected to server A. At this moment, server B will not allow any IP connect to it since the  IPLimit is 0.

To test my assumption, maybe you could try the following steps:

1. Set a user with deviceLimit 1
2. Connect to server A with a PC device, and wait for at least 2 minutes (first minute for server A to report the online IP, and second minute for server B to update the IPLimit of current user).
3. Try to connect server B with the same PC device before server A reports the disconnection behavior.

I think the possible outcome is that you cannot connect to server B until server A reports 0 online device and server B updates its IPLimit which may take at least 2 minutes. 

Please tell me the result if you try this experiment, and help me fully understand your implementation.
