### ISSUE TITLE
xrayr最新版好像不支持v2board了

### ISSUE THREAD

**Issue by xddg1314** [XrayR-project/XrayR#477]
xrayr最新版好像不支持v2board了，配置完成，启动失败报错了

**Comment by thank243** [comment]
No logs? and what is the v2board version?

**Comment by hackerlengyue** [comment]
DisableLocalREALITYConfig: true就可以了。

**Comment by hackerlengyue** [comment]
我看日志这个报错搜配置文件一读有这个了

**Comment by thank243** [comment]
logs? and v2board version.
