### ISSUE TITLE
v2board本地屏蔽的规则会在安卓端v2rayng失效

### ISSUE THREAD

**Issue by kiliop** [XrayR-project/XrayR#48]
屏蔽的规则会在安卓端v2rayng失效，其他的客户端没发现问题。

**Comment by RManLuo** [comment]
确认是否启用本地dns解析，如果启用，请善用ip屏蔽用户访问ip地址。

**Comment by kiliop** [comment]
并没有启用该设置，软件默认设置。

**Comment by kiliop** [comment]
建议大大，适配一下v2board在线设置，以上问题在其他后端（soga）并没有出现。
