### ISSUE TITLE
XrayR v0.9.1 Latest 新更新的版本对接V2board报错不支持

### ISSUE THREAD

**Issue by JasonScofield** [XrayR-project/XrayR#480]
提示：Unsupport panel type: V2board

**Comment by thank243** [comment]
```
  - PanelType: "NewV2board" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel

**Comment by JefferyW1** [comment]
v2board 版本 >= [1.7.0](https://github.com/v2board/v2board/releases/tag/1.7.0) 请选择 PanelType: "NewV2board"。其他旧版本选择 PanelType: "V2board"，注意老版本API将于 2023.6.1后移除。

**Comment by dopaemon** [comment]
why remove support Old V2board ?

**Comment by thank243** [comment]
Old api not suport new feature

> why remove support Old V2board ?

**Comment by nsony** [comment]
0.91 显示报错 。0.90正常
XrayR.service: Failed with result 'exit-code'.

**Comment by Pumilk** [comment]
是的0.91对接V2board v1.7.4会出现XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
使用0.90可以正常使用
