### ISSUE TITLE
sspanel uim 2023.5对接最新0.9.1 bug

### ISSUE THREAD

**Issue by bxoooooo** [XrayR-project/XrayR#487]
初次对接报错
config. > infra/conf: invalid "privateKey": YOUR_PRIVATE_KEY
关闭   EnableREALITY:  false# Enable REALITY 后报错
panic: infra/conf: unknown cipher method:

**Comment by bxoooooo** [comment]
v2board关闭   EnableREALITY: true # Enable REALITY
能正常使用

**Comment by thank243** [comment]
Full logs. And `config.yml`, custom_config of panel

**Comment by bxoooooo** [comment]
Level: warning # Log level: none, error, warning, info, debug
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
Nodes:
  - PanelType: "SSpanel" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel
    ApiConfig:
      ApiHost: "https://xxxxx"
      ApiKey: "oooooo"
      NodeID: 10
      NodeType: Shadowsocks # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
      DisableCustomConfig: false # disable custom config for sspanel
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisAddr: 127.0.0.1:6379 # The redis server address
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      DisableLocalREALITYConfig: false  # disable local reality config
      EnableREALITY: false # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: www.smzdm.com:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - www.smzdm.com
        PrivateKey: YOUR_PRIVATE_KEY # Required, execute './xray x25519' to generate.
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
          - ""
          - 0123456789abcdef
      CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: /etc/XrayR/cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb

**Comment by bxoooooo** [comment]
4
Oct 17 19:43:24 root XrayR[1074082]: 2023/10/17 19:43:24 [Warning] core: Xray 1.8.4 started
Oct 17 19:43:24 root XrayR[1074082]: 2023/10/17 19:43:24 infra/conf: unknown cipher method:
Oct 17 19:43:24 root XrayR[1074082]: panic: infra/conf: unknown cipher method:
Oct 17 19:43:24 root XrayR[1074082]: goroutine 1 [running]:
Oct 17 19:43:24 root XrayR[1074082]: log.Panic({0xc000669c68?, 0xc000308200?, 0xc000669ce8?})
Oct 17 19:43:24 root XrayR[1074082]:         log/log.go:432 +0x5a
Oct 17 19:43:24 root XrayR[1074082]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000308f00)
Oct 17 19:43:24 root XrayR[1074082]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Oct 17 19:43:24 root XrayR[1074082]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00056df80)
Oct 17 19:43:24 root XrayR[1074082]:         github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
Oct 17 19:43:24 root XrayR[1074082]: main.main()
Oct 17 19:43:24 root XrayR[1074082]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Oct 17 19:43:24 root systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 17 19:43:24 root systemd[1]: XrayR.service: Failed with result 'exit-code'.
Oct 17 19:43:34 root systemd[1]: XrayR.service: Service RestartSec=10s expired,
scheduling restart.
Oct 17 19:43:34 root systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 103.
Oct 17 19:43:34 root systemd[1]: Stopped XrayR Service.
Oct 17 19:43:34 root systemd[1]: Started XrayR Service.
Oct 17 19:43:34 root XrayR[1074095]: XrayR 0.9.1 (A Xray backend that supports many panels)
Oct 17 19:43:34 root XrayR[1074095]: 2023/10/17 19:43:34 Start the panel..
Oct 17 19:43:34 root XrayR[1074095]: 2023/10/17 19:43:34 Xray Core Version: 1.8.4
Oct 17 19:43:34 root XrayR[1074095]: 2023/10/17 19:43:34 [Warning] core: Xray 1.8.4 started
Oct 17 19:43:34 root XrayR[1074095]: 2023/10/17 19:43:34 infra/conf: unknown cipher method:
Oct 17 19:43:34 root XrayR[1074095]: panic: infra/conf: unknown cipher method:
Oct 17 19:43:34 root XrayR[1074095]: goroutine 1 [running]:
Oct 17 19:43:34 root XrayR[1074095]: log.Panic({0xc00037dc68?, 0xc000a78400?, 0xc00037dce8?})
Oct 17 19:43:34 root XrayR[1074095]:         log/log.go:432 +0x5a
Oct 17 19:43:34 root XrayR[1074095]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00039cf00)
Oct 17 19:43:34 root XrayR[1074095]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Oct 17 19:43:34 root XrayR[1074095]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000032b80)
Oct 17 19:43:34 root XrayR[1074095]:         github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
Oct 17 19:43:34 root XrayR[1074095]: main.main()
Oct 17 19:43:34 root XrayR[1074095]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Oct 17 19:43:34 root systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 17 19:43:34 root systemd[1]: XrayR.service: Failed with result 'exit-code'.
Oct 17 19:43:45 root systemd[1]: XrayR.service: Service RestartSec=10s expired,
scheduling restart.
Oct 17 19:43:45 root systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 104.
Oct 17 19:43:45 root systemd[1]: Stopped XrayR Service.
Oct 17 19:43:45 root systemd[1]: Started XrayR Service.
Oct 17 19:43:45 root XrayR[1074183]: XrayR 0.9.1 (A Xray backend that supports many panels)
Oct 17 19:43:45 root XrayR[1074183]: 2023/10/17 19:43:45 Start the panel..
Oct 17 19:43:45 root XrayR[1074183]: 2023/10/17 19:43:45 Xray Core Version: 1.8.4
Oct 17 19:43:45 root XrayR[1074183]: 2023/10/17 19:43:45 [Warning] core: Xray 1.8.4 started
Oct 17 19:43:45 root XrayR[1074183]: 2023/10/17 19:43:45 infra/conf: unknown cipher method:
Oct 17 19:43:45 root XrayR[1074183]: panic: infra/conf: unknown cipher method:
Oct 17 19:43:45 root XrayR[1074183]: goroutine 1 [running]:
Oct 17 19:43:45 root XrayR[1074183]: log.Panic({0xc000b0fc68?, 0xc0006f4300?, 0xc000b0fce8?})
Oct 17 19:43:45 root XrayR[1074183]:         log/log.go:432 +0x5a
Oct 17 19:43:45 root XrayR[1074183]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000657d00)
Oct 17 19:43:45 root XrayR[1074183]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Oct 17 19:43:45 root XrayR[1074183]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005c6f80)
Oct 17 19:43:45 root XrayR[1074183]:         github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
Oct 17 19:43:45 root XrayR[1074183]: main.main()
Oct 17 19:43:45 root XrayR[1074183]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Oct 17 19:43:45 root systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 17 19:43:45 root systemd[1]: XrayR.service: Failed with result 'exit-code'.
Oct 17 19:43:55 root systemd[1]: XrayR.service: Service RestartSec=10s expired,
scheduling restart.
Oct 17 19:43:55 root systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 105.
Oct 17 19:43:55 root systemd[1]: Stopped XrayR Service.
Oct 17 19:43:55 root systemd[1]: Started XrayR Service.
Oct 17 19:43:55 root XrayR[1074195]: XrayR 0.9.1 (A Xray backend that supports many panels)
Oct 17 19:43:55 root XrayR[1074195]: 2023/10/17 19:43:55 Start the panel..
Oct 17 19:43:55 root XrayR[1074195]: 2023/10/17 19:43:55 Xray Core Version: 1.8.4
Oct 17 19:43:55 root XrayR[1074195]: 2023/10/17 19:43:55 [Warning] core: Xray 1.8.4 started
Oct 17 19:43:55 root XrayR[1074195]: 2023/10/17 19:43:55 infra/conf: unknown cipher method:
Oct 17 19:43:55 root XrayR[1074195]: panic: infra/conf: unknown cipher method:
Oct 17 19:43:55 root XrayR[1074195]: goroutine 1 [running]:
Oct 17 19:43:55 root XrayR[1074195]: log.Panic({0xc000acbc68?, 0xc0004f0800?, 0xc000acbce8?})
Oct 17 19:43:55 root XrayR[1074195]:         log/log.go:432 +0x5a
Oct 17 19:43:55 root XrayR[1074195]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000511f00)
Oct 17 19:43:55 root XrayR[1074195]:         github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
Oct 17 19:43:55 root XrayR[1074195]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000041780)
Oct 17 19:43:55 root XrayR[1074195]:         github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
Oct 17 19:43:55 root XrayR[1074195]: main.main()
Oct 17 19:43:55 root XrayR[1074195]:         github.com/XrayR-project/XrayR/main/main.go:97 +0x233
Oct 17 19:43:55 root systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 17 19:43:55 root systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by thank243** [comment]
Are you known how to set SSPanel Custom Config? If you konw, you can paste your cutom config to here.
https://aiastia.gitbook.io/xrayr/dui-jie-sspanel/sspanel/sspanel_custom_config

**Comment by bxoooooo** [comment]
{
  "offset_port_user": "32708",
  "offset_port_node": "33333",
  "server_user": "xxx.top",
  "mu_encryption": "aes-128-gcm"
}

**Comment by bxoooooo** [comment]
自定义配置在0.9.0是有效且正常运行的

**Comment by thank243** [comment]
try this config
```json
{
"offset_port_user": "32708",
"offset_port_node": "33333",
"server_user": "xxx.com",
"method": "aes-128-gcm"
}

**Comment by bxoooooo** [comment]
这个配置在0.9.1能用  感谢大佬
0.9.0只能用mu_encryption": "aes-128-gcm"
谢谢解惑

**Comment by Sam-Mey** [comment]
> Are you known how to set SSPanel Custom Config? If you konw, you can paste your cutom config to here.
> https://aiastia.gitbook.io/xrayr/dui-jie-sspanel/sspanel/sspanel_custom_config

Are you still using Stone Age documents?
