### ISSUE TITLE
docker 启动报错 panic: Panel Start fialed: users is null

### ISSUE THREAD

**Issue by love208-vip** [XrayR-project/XrayR#490]
XrayR 0.9.2 (A Xray backend that supports many panels) 
2023/10/19 02:51:55 Start the panel..
2023/10/19 02:51:55 Xray Core Version: 1.8.4
2023/10/19 02:51:55 [Warning] core: Xray 1.8.4 started
2023/10/19 02:51:56 Panel Start fialed: users is null
panic: Panel Start fialed: users is null

goroutine 1 [running]:
log.Panicf({0x3649f63?, 0x3aaa4c0?}, {0xc000a53ba0?, 0xc0006ff560?, 0x2e87580?})
        log/log.go:439 +0x65
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000520e40)
        github.com/XrayR-project/XrayR/panel/panel.go:210 +0x5fb
github.com/XrayR-project/XrayR/cmd.run()
        github.com/XrayR-project/XrayR/cmd/root.go:94 +0x233
github.com/XrayR-project/XrayR/cmd.glob..func1(0xc00014b100?, {0x3621918?, 0x4?, 0x362191c?})
        github.com/XrayR-project/XrayR/cmd/root.go:26 +0x13
github.com/spf13/cobra.(*Command).execute(0x5d2b900, {0xc000072940, 0x2, 0x2})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
github.com/spf13/cobra.(*Command).ExecuteC(0x5d2b900)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/XrayR-project/XrayR/cmd.Execute(...)
        github.com/XrayR-project/XrayR/cmd/root.go:108
main.main()
        github.com/XrayR-project/XrayR/main.go:10 +0x1a

**Comment by thank243** [comment]
Panel Start fialed: users is null

**Comment by love208-vip** [comment]
面板启动失败：用户为空

使用的v2b最版版本，xrayr docker运行的xrayr版本0.9.1，和master是报这异常，我退回到 0.9.0就正常启动

**Comment by love208-vip** [comment]
> Panel Start fialed: users is null

老板，麻烦帮忙看看呢这个问题，v2b新建的时候会添加一个默认管理元所以用户至少有一个人不会为空的
