### ISSUE TITLE
how install 0.9.0 version ?

### ISSUE THREAD

**Issue by Redshado0w** [XrayR-project/XrayR#493]
hi how can i install older version for v2board ?

**Comment by gzshasha** [comment]
docker-compose.yml

version: '3'
services:
  xrayr:
    image: ghcr.io/xrayr-project/xrayr:v0.9.0
    volumes:
      - ./config:/etc/XrayR/ # 映射配置文件夹
    restart: always
    network_mode: host

**Comment by Redshado0w** [comment]
> docker-compose.yml
> 
> version: '3' services: xrayr: image: ghcr.io/xrayr-project/xrayr:v0.9.0 volumes: - ./config:/etc/XrayR/ # 映射配置文件夹 restart: always network_mode: host

thanks a lot 
how i can run pem cert file in docker ? 
i move the pem file into config folder but docker cant access thats pem file

**Comment by Redshado0w** [comment]
2023/10/28 21:55:00 infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /root/XrayR-release/fullchain.pem: no such file or directory

**Comment by Redshado0w** [comment]
problem is solved thanks
