### ISSUE TITLE
SSPanel-UIM  2023.05 对接0.9.1  xrayr启动失败 bug

### ISSUE THREAD

**Issue by zhangyubushiyu** [XrayR-project/XrayR#498]
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: log.Panic({0xc0008b7c68?, 0xc0000f0d00?, 0xc0008b7ce8?})
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: log/log.go:432 +0x5a
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00016c200)
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0002d2bc0)
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: main.main()
10月 27 02:26:45 sweet-cat-3.localdomain XrayR[27410]: github.com/XrayR-project/XrayR/main/main.go:97 +0x233
10月 27 02:26:45 sweet-cat-3.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
10月 27 02:26:45 sweet-cat-3.localdomain systemd[1]: Unit XrayR.service entered failed state.
10月 27 02:26:45 sweet-cat-3.localdomain systemd[1]: XrayR.service failed.
10月 27 02:26:55 sweet-cat-3.localdomain systemd[1]: XrayR.service holdoff time over, scheduling restart.
10月 27 02:26:55 sweet-cat-3.localdomain systemd[1]: Stopped XrayR Service.
10月 27 02:26:55 sweet-cat-3.localdomain systemd[1]: Started XrayR Service.
10月 27 02:26:55 sweet-cat-3.localdomain XrayR[27496]: XrayR 0.9.1 (A Xray backend that supports many panels)
10月 27 02:26:55 sweet-cat-3.localdomain XrayR[27496]: 2023/10/27 02:26:55 Start the panel..
10月 27 02:26:55 sweet-cat-3.localdomain XrayR[27496]: 2023/10/27 02:26:55 Xray Core Version: 1.8.4
10月 27 02:26:55 sweet-cat-3.localdomain XrayR[27496]: 2023/10/27 02:26:55 [Warning] core: Xray 1.8.4 started
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: 2023/10/27 02:26:56 infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: panic: infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: goroutine 1 [running]:
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: log.Panic({0xc000a51c68?, 0xc0006ca600?, 0xc000a51ce8?})
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: log/log.go:432 +0x5a
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc00016c200)
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000385040)
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: main.main()
10月 27 02:26:56 sweet-cat-3.localdomain XrayR[27496]: github.com/XrayR-project/XrayR/main/main.go:97 +0x233
10月 27 02:26:56 sweet-cat-3.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
10月 27 02:26:56 sweet-cat-3.localdomain systemd[1]: Unit XrayR.service entered failed state.
10月 27 02:26:56 sweet-cat-3.localdomain systemd[1]: XrayR.service failed.
10月 27 02:27:06 sweet-cat-3.localdomain systemd[1]: XrayR.service holdoff time over, scheduling restart.
10月 27 02:27:06 sweet-cat-3.localdomain systemd[1]: Stopped XrayR Service.
10月 27 02:27:06 sweet-cat-3.localdomain systemd[1]: Started XrayR Service.
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: XrayR 0.9.1 (A Xray backend that supports many panels)
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: 2023/10/27 02:27:06 Start the panel..
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: 2023/10/27 02:27:06 Xray Core Version: 1.8.4
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: 2023/10/27 02:27:06 [Warning] core: Xray 1.8.4 started
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: 2023/10/27 02:27:06 infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: panic: infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: goroutine 1 [running]:
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: log.Panic({0xc000661c68?, 0xc0004acd00?, 0xc000661ce8?})
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: log/log.go:432 +0x5a
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000112200)
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000253000)
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: main.main()
10月 27 02:27:06 sweet-cat-3.localdomain XrayR[27524]: github.com/XrayR-project/XrayR/main/main.go:97 +0x233
10月 27 02:27:06 sweet-cat-3.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
10月 27 02:27:06 sweet-cat-3.localdomain systemd[1]: Unit XrayR.service entered failed state.
10月 27 02:27:06 sweet-cat-3.localdomain systemd[1]: XrayR.service failed.
10月 27 02:27:16 sweet-cat-3.localdomain systemd[1]: XrayR.service holdoff time over, scheduling restart.
10月 27 02:27:16 sweet-cat-3.localdomain systemd[1]: Stopped XrayR Service.
10月 27 02:27:16 sweet-cat-3.localdomain systemd[1]: Started XrayR Service.
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: XrayR 0.9.1 (A Xray backend that supports many panels)
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: 2023/10/27 02:27:16 Start the panel..
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: 2023/10/27 02:27:16 Xray Core Version: 1.8.4
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: 2023/10/27 02:27:16 [Warning] core: Xray 1.8.4 started
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: 2023/10/27 02:27:16 infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: panic: infra/conf: REALITY only supports TCP, H2, gRPC and DomainSocket for now.
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: goroutine 1 [running]:
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: log.Panic({0xc00057bc68?, 0xc000752400?, 0xc00057bce8?})
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: log/log.go:432 +0x5a
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc000752e00)
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: github.com/XrayR-project/XrayR/service/controller/controller.go:88 +0x26f
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0002038c0)
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: github.com/XrayR-project/XrayR/panel/panel.go:208 +0x596
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: main.main()
10月 27 02:27:16 sweet-cat-3.localdomain XrayR[27539]: github.com/XrayR-project/XrayR/main/main.go:97 +0x233
10月 27 02:27:16 sweet-cat-3.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
10月 27 02:27:16 sweet-cat-3.localdomain systemd[1]: Unit XrayR.service entered failed state.
10月 27 02:27:16 sweet-cat-3.localdomain systemd[1]: XrayR.service failed.

**Comment by thank243** [comment]
REALITY only supports TCP, H2, gRPC and DomainSocket for now.
