### ISSUE TITLE
v0.9.2-alpha notwork

### ISSUE THREAD

**Issue by gzshasha** [XrayR-project/XrayR#499]
V2board 1.7.4

PanelType: "NewV2board" # Panel type: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
ApiConfig:
  ApiHost: "https://123111.xxx"
  ApiKey: "XXXXXX"
  NodeID: 6
  NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin

root@debian:~/XrayR-release# docker-compose up
[+] Running 1/0
✔ Container xrayr-release-xrayr-1 Created 0.0s
Attaching to xrayr-release-xrayr-1
xrayr-release-xrayr-1 | XrayR 0.9.2 (A Xray backend that supports many panels)
xrayr-release-xrayr-1 | 2023/10/27 23:03:06 Start the panel..
xrayr-release-xrayr-1 | 2023/10/27 23:03:06 Xray Core Version: 1.8.4
xrayr-release-xrayr-1 | 2023/10/27 23:03:06 [Warning] core: Xray 1.8.4 started
xrayr-release-xrayr-1 | 2023/10/27 23:03:07 Panel Start fialed: users is null
xrayr-release-xrayr-1 | panic: Panel Start fialed: users is null
xrayr-release-xrayr-1 |
xrayr-release-xrayr-1 | goroutine 1 [running]:
xrayr-release-xrayr-1 | log.Panicf({0x364a223?, 0x3aaa820?}, {0xc0007abba0?, 0xc000217320?, 0x2e87620?})
xrayr-release-xrayr-1 | log/log.go:439 +0x65
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0004f3300)
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/panel/panel.go:210 +0x5fb
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/cmd.run()
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/cmd/root.go:94 +0x233
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/cmd.glob..func1(0xc00011f300?, {0x3621bd8?, 0x4?, 0x3621bdc?})
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/cmd/root.go:26 +0x13
xrayr-release-xrayr-1 | github.com/spf13/cobra.(*Command).execute(0x5d2b940, {0xc0000728e0, 0x2, 0x2})
xrayr-release-xrayr-1 | github.com/spf13/cobra@v1.7.0/command.go:944 +0x863
xrayr-release-xrayr-1 | github.com/spf13/cobra.(*Command).ExecuteC(0x5d2b940)
xrayr-release-xrayr-1 | github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
xrayr-release-xrayr-1 | github.com/spf13/cobra.(*Command).Execute(...)
xrayr-release-xrayr-1 | github.com/spf13/cobra@v1.7.0/command.go:992
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/cmd.Execute(...)
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/cmd/root.go:108
xrayr-release-xrayr-1 | main.main()
xrayr-release-xrayr-1 | github.com/XrayR-project/XrayR/main.go:10 +0x1a

**Comment by thank243** [comment]
users is null
