### ISSUE TITLE
Connection error or very slow connection on zalo app.

### ISSUE THREAD

**Issue by Jeffeditae** [XrayR-project/XrayR#50]
I'm having the problem that every time I go to Zalo by Zalo Group VNG, I can't text or send photos and videos. It's been so long since I have to turn off my VPN and everything I'm sending is being received, I'm wondering if this is a bug or a feature.
This App is made by Vietnam
Link on IOS: https://apps.apple.com/us/app/zalo/id579523206
Link on Android: https://play.google.com/store/apps/details?id=com.zing.zalo
I will be very grateful when you guys update and fix this bug.
![3DA59F9A-042E-482D-840D-4D95FAEA6783](https://user-images.githubusercontent.com/39546317/133786381-42c83f51-f4d4-41b9-924f-a9cfc57eed4b.jpeg)
![7BEE2DB3-C5FD-468A-8289-FDE54F377451](https://user-images.githubusercontent.com/39546317/133786390-34c7fa7b-c31a-466b-90dd-686255f6e739.jpeg)

**Comment by RManLuo** [comment]
I did not see any problems related to this project.

**Comment by crackair** [comment]
Disable the sniffing function can solve this issue fdf050f97d312c5ef2a3d3eeaad126b68dbadc1e

**Comment by himanhimao** [comment]
I know the reason for this problem, ha ha

**Comment by himanhimao** [comment]
please turn off sniffing. please refer to the relevant configuration
