### ISSUE TITLE
UDP-OVER-TCP

### ISSUE THREAD

**Issue by uby777881** [XrayR-project/XrayR#500]
Hello, How can i make shadowsocks server UDP-over-TCP turned on as default? Is t possible through xrayr?

**Comment by thank243** [comment]
Only ss2022 support UOT. The switch is depend on client, not server.

**Comment by uby777881** [comment]
I'm using V2board. i didn't find anyway to turn it on and there are no support option available from V2board developers. Do you know any way to turn on UOT

**Comment by thh1451** [comment]
> I'm using V2board. i didn't find anyway to turn it on and there are no support option available from V2board developers. Do you know any way to turn on UOT

it depends on the client!!!!!!

**Comment by uby777881** [comment]
ok
