### ISSUE TITLE
the node dont have log and the node situation is on" No one is using it or the server reports an exception."

### ISSUE THREAD

**Issue by rahavard01** [XrayR-project/XrayR#508]
i'm using websocket service on v2board and node situation is on " No one is using it or the server reports an exception."

how can i solve this problem?
the xrayr status is:
![Capture12](https://github.com/XrayR-project/XrayR/assets/136188179/1028e716-deef-497d-97a0-179b19c41842)

**Comment by thank243** [comment]
The OS's local DNS problem. Try to change it.

**Comment by rahavard01** [comment]
thanks . how can i change it?

**Comment by rahavard01** [comment]
also this server have the same situation.
and xrayr status is: 

![Uploading Capture13.JPG…]()

**Comment by rahavard01** [comment]
also this server have the same situation.
and xrayr status is:

![Capture13](https://github.com/XrayR-project/XrayR/assets/136188179/fb65441c-4791-4c41-98f8-0489c00aefeb)

**Comment by rahavard01** [comment]
> The OS's local DNS problem. Try to change it.

?
