### ISSUE TITLE
配置Trojan出现以下问题，配置SS和V2RAY都可以正常运行，前端配置没问题，怀疑是软件的问题

### ISSUE THREAD

**Issue by maxwellhouse102** [XrayR-project/XrayR#51]
XrayR 0.7.0 (A Xray backend that supports many panels) 
2021/09/20 01:02:51 Start the panel..
2021/09/20 01:02:51 Xray Core Version: 1.4.2
2021/09/20 01:02:51 [Debug] app/log: Logger started
2021/09/20 01:02:51 [Info] app/dns: DNS: created localhost client
2021/09/20 01:02:51 [Warning] core: Xray 1.4.2 started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x189cbc5]

goroutine 1 [running]:
github.com/XrayR-project/XrayR/service/controller.InboundBuilder(0xc0004c4b60, 0xc00036a1a0, 0xc00005cc00, 0x0, 0xc0005bfbb0)
        github.com/XrayR-project/XrayR/service/controller/inboundbuilder.go:153 +0x6a5
github.com/XrayR-project/XrayR/service/controller.(*Controller).addNewTag(0xc0004c3c20, 0xc00036a1a0, 0x0, 0x0)
        github.com/XrayR-project/XrayR/service/controller/controller.go:238 +0x65
github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0004c3c20, 0x0, 0x0)
        github.com/XrayR-project/XrayR/service/controller/controller.go:48 +0x105
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0004634c0)
        github.com/XrayR-project/XrayR/panel/panel.go:172 +0x63b
main.main()
        github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5

**Comment by crackair** [comment]
@maxwellhouse102 仔细检查节点配置

**Comment by maxwellhouse102** [comment]
> @maxwellhouse102 仔细检查节点配置
很简单的配置，对接的V2board，这应该没问题吧
![QQ截图20210920102711](https://user-images.githubusercontent.com/25824373/133951994-bf99d028-b1aa-49c3-902a-d35529a9518d.png)

**Comment by crackair** [comment]
@crackair 检查后端配置文件设置

**Comment by crackair** [comment]
@maxwellhouse102 检查后端配置文件设置

**Comment by flhs0606** [comment]
我也遇到同样报错，未发现问题所在。配置文件如下：
Log:
  Level: error
  AccessPath: /etc/XrayR/access.log
  ErrorPath: /etc/XrayR/error.log
DnsConfigPath: /etc/XrayR/dns.json
Nodes:
  -
    PanelType: "V2board"
    ApiConfig:
      ApiHost: "https://xxx.cc"
      ApiKey: "xxx"
      NodeID: 7
      NodeType: Trojan
      Timeout: 30
      EnableVless: false
      EnableXTLS: false
    ControllerConfig:
      ListenIP: 0.0.0.0
      UpdatePeriodic: 60
      EnableDNS: false
      EnableProxyProtocol: false
      EnableFallback: true
      FallBackConfigs:
        -
          SNI:
          Path:
          Dest: xxx.cc:8005
          ProxyProtocolVer: 0

    CertConfig:
        CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "xx.xxx.cc" # Domain to cert
        Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: xxx@qq.com
        DNSEnv: # DNS ENV option used by DNS provider
            CF_API_EMAIL: xxx@qq.com
            CF_API_KEY: xxx

**Comment by flhs0606** [comment]
> 我也遇到同样报错，未发现问题所在。配置文件如下：
> 
> ```
> Log:
>   Level: error
>   AccessPath: /etc/XrayR/access.log
>   ErrorPath: /etc/XrayR/error.log
> DnsConfigPath: /etc/XrayR/dns.json
> Nodes:
>   -
>     PanelType: "V2board"
>     ApiConfig:
>       ApiHost: "https://xxx.cc"
>       ApiKey: "xxx"
>       NodeID: 7
>       NodeType: Trojan
>       Timeout: 30
>       EnableVless: false
>       EnableXTLS: false
>     ControllerConfig:
>       ListenIP: 0.0.0.0
>       UpdatePeriodic: 60
>       EnableDNS: false
>       EnableProxyProtocol: false
>       EnableFallback: true
>       FallBackConfigs:
>         -
>           SNI:
>           Path:
>           Dest: xxx.cc:8005
>           ProxyProtocolVer: 0
> 
>     CertConfig:
>         CertMode: dns # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
>         CertDomain: "xx.xxx.cc" # Domain to cert
>         Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
>         Email: xxx@qq.com
>         DNSEnv: # DNS ENV option used by DNS provider
>             CF_API_EMAIL: xxx@qq.com
>             CF_API_KEY: xxx
> ```

初步排除发现是证书配置问题
