### ISSUE TITLE
sspanel reality

### ISSUE THREAD

**Issue by visense** [XrayR-project/XrayR#511]
老版的ssapenl 支持XrayR v0.9.1的reality吗？

如果支持reality参数比如lpubic-key怎么设置？

**Comment by thank243** [comment]
、、、json
"reality-opts": { "server_names": [ "abc.com", "cdf.com" ], "private_key": "keykeykey", "min_client_ver": "1.1.1", "max_client_ver": "2.2.2", "max_time_diff": 30, "short_ids": [ "321213123" ] }
