### ISSUE TITLE
create installer for 0.9.0 version

### ISSUE THREAD

**Issue by Redshado0w** [XrayR-project/XrayR#522]
Hello to all the fighters to remove the censorship
Can someone be kind and create a special installer file for version 0.9.0 so that other people who have the old version of v2board can install it directly without using Docker?

**Comment by thh1451** [comment]
It seems possible to install the version you need within the XrayR script?

**Comment by Redshado0w** [comment]
> It seems possible to install the version you need within the XrayR script?

thanks 
how i can do this ? 
i run this commands
wget -N https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh && bash install.sh
but this command install latest version

**Comment by thh1451** [comment]
> > It seems possible to install the version you need within the XrayR script?
> 
> thanks how i can do this ? i run this commands wget -N https://raw.githubusercontent.com/XrayR-project/XrayR-release/master/install.sh && bash install.sh but this command install latest version

https://github.com/XrayR-project/XrayR-release/blob/master/XrayR.sh#L394C30-L394C30
