### ISSUE TITLE
两台机器，都是很多这个报错，不知道怎么解决。

### ISSUE THREAD

**Issue by genics** [XrayR-project/XrayR#53]
请教下怎么回事？另外有一台机器gost始终中转失败，（clash测速超时）节点是蓝色，检查了监听端口也都是对的。相同的设置（反复比较过）另一台机器转发就正常。

此问题是证书还是什么原因造成？

忘了说了，节点是ws tls，和trojan。一台机器运行两个服务器端。

Sep 20 22:51:26 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:26 http2: server: error reading preface from client 112.10.208.135:7161: bogus greeting "e114675d499a93290c1caba0"
Sep 20 22:51:27 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:27 http2: server: error reading preface from client 127.0.0.1:47856: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:28 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:28 http2: server: error reading preface from client 127.0.0.1:47858: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:28 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:28 http2: server: error reading preface from client 127.0.0.1:47860: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:28 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:28 http2: server: error reading preface from client 127.0.0.1:47862: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:29 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:29 http2: server: error reading preface from client 127.0.0.1:47866: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:29 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:29 http2: server: error reading preface from client 127.0.0.1:47868: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:30 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:30 http2: server: error reading preface from client 127.0.0.1:47872: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:31 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:31 http2: server: error reading preface from client 127.0.0.1:47876: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:32 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:32 http2: server: error reading preface from client 112.195.4.133:2580: bogus greeting "52262101949b3e183f710827"
Sep 20 22:51:35 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:35 http2: server: error reading preface from client 127.0.0.1:47888: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:35 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:35 http2: server: error reading preface from client 127.0.0.1:47894: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:35 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:35 http2: server: error reading preface from client 127.0.0.1:47896: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:35 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:35 http2: server: error reading preface from client 127.0.0.1:47898: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:36 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:36 http2: server: error reading preface from client 127.0.0.1:47906: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:37 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:37 http2: server: error reading preface from client 127.0.0.1:47910: bogus greeting "e82441a149f9bd9b65328909"
Sep 20 22:51:41 ip-172-26-3-193.ap-southeast-1.compute.internal XrayR[5766]: 2021/09/20 22:51:41 http2: server: error reading preface from client 127.0.0.1:47918: bogus greeting "e82441a149f9bd9b65328909"

**Comment by RManLuo** [comment]
根据log节点协议似乎是tcp+http2，并非ws

**Comment by genics** [comment]
> 根据log节点协议似乎是tcp+http2，并非ws

v2ray部分节点肯定设置的是ws+tls， 是不是trojan部分是tcp+http2？ 那就是trojan部分的错误了？
对了前段面板是v2board
