### ISSUE TITLE
v2board的路由模式不支持通配符

### ISSUE THREAD

**Issue by Scyllaly** [XrayR-project/XrayR#540]
Dec 03 11:24:59 host XrayR[3036]: 2023/12/03 11:24:59 [Warning] core: Xray 1.8.4 started
Dec 03 11:25:00 host XrayR[3036]: 2023/12/03 11:25:00 [https://host.com] V2ray(ID=1) Added 1 new users
Dec 03 11:25:00 host XrayR[3036]: panic: regexp: Compile(`*.youtube.com`): error parsing regexp: missing argument to repetition operator: `*`
Dec 03 11:25:00 WEPC47254319061 XrayR[3036]: goroutine 1 [running]:

**Comment by thank243** [comment]
An array where each item is a domain match. There are several forms:

Plain string: If this string matches any part of the target domain, the rule takes effect. For example, "sina.com" can match "sina.com", "sina.com.cn", and "www.sina.com", but not "sina.cn".

Regular expression: Starts with "regexp:" followed by a regular expression. When this regular expression matches the target domain, the rule takes effect. For example, "regexp:\\.goo.*\\.com$" matches "www.google.com" or "fonts.googleapis.com", but not "google.com".

Subdomain (recommended): Starts with "domain:" followed by a domain. When this domain is the target domain or a subdomain of the target domain, the rule takes effect. For example, "domain:xray.com" matches "www.xray.com" and "xray.com", but not "wxray.com".

Exact match: Starts with "full:" followed by a domain. When this domain is an exact match for the target domain, the rule takes effect. For example, "full:xray.com" matches "xray.com" but not "www.xray.com".

Predefined domain list: Starts with "geosite:" followed by a name such as geosite:google or geosite:cn. The names and domain lists are listed in [Predefined Domain List](https://xtls.github.io/en/config/routing.html#predefined-domain-list).
Load domains from a file: Formatted as "ext:file:tag", where the file is stored in the [resource directory](https://xtls.github.io/en/config/features/env.html#resource-file-path) and has the same format as geosite.dat. The tag must exist in the file.
