### ISSUE TITLE
什么时候能实现hy2

### ISSUE THREAD

**Issue by smalllam** [XrayR-project/XrayR#547]

**Comment by sjhgd132213** [comment]
XrayR is a project built upon Xray-core. As of now, there are no immediate plans to work on the Hysteria2 protocol within the XrayR project. The development roadmap for XrayR is closely tied to the progress made in Xray-core.

Until the Hysteria2 protocol is implemented in Xray-core, any efforts to incorporate this protocol into XrayR would be premature. If you are interested in contributing to the implementation of the Hysteria2 protocol, I recommend directing your efforts towards Xray-core's repository. You can submit Pull Requests with relevant code changes to contribute to the development of Hysteria2 in Xray-core.

**Comment by Weoworks** [comment]
GPT!!!!
