### ISSUE TITLE
IP is invalid. Now, your IP address is xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by pingProMax** [XrayR-project/XrayR#55]
服务器ip并不是8.45.41.250

goroutine 1 [running]:
log.Panicf(0x1f5f5ab, 0x16, 0xc00070fea0, 0x1, 0x1)
        log/log.go:361 +0xc5
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0003fb6c0)
        github.com/XrayR-project/XrayR/panel/panel.go:137 +0x6f1
main.main()
        github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5
XrayR 0.6.1 (A Xray backend that supports many panels) 
2021/09/27 19:45:00 Start the panel..
2021/09/27 19:45:00 Xray Core Version: 1.4.2
2021/09/27 19:45:01 Panel Start fialed: Ret {"ret":0,"data":"IP is invalid. Now, your IP address is 8.45.41.250"} invalid
panic: Panel Start fialed: Ret {"ret":0,"data":"IP is invalid. Now, your IP address is 8.45.41.250"} invalid

goroutine 1 [running]:
log.Panicf(0x1f5f5ab, 0x16, 0xc00070fea0, 0x1, 0x1)
        log/log.go:361 +0xc5
github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0003fb6c0)
        github.com/XrayR-project/XrayR/panel/panel.go:137 +0x6f1
main.main()
        github.com/XrayR-project/XrayR/main/main.go:85 +0x1c5

**Comment by crackair** [comment]
@pingProMax 面板关闭IP验证

**Comment by pingProMax** [comment]
> @pingProMax 面板关闭IP验证

面板并没有开启ip验证，而且我没有这个ip的服务器
