### ISSUE TITLE
"sendThrough"无效

### ISSUE THREAD

**Issue by jwstaceyOvO** [XrayR-project/XrayR#56]
自定义路由和出口如下
outbound: 
   {
      "sendThrough": "本机ip",
      "protocol": "freedom",
      "settings": {}
    },
    {
      "tag": "google",
      "protocol": "freedom",
      "settings": {"domainStrategy": "UseIPv4"}
    },
route:
"domainStrategy": "AsIs",
"rules": [
      {
        "type": "field",
        "outboundTag": "google",
        "domain": ["geosite:google"]
      },
]
后端上使用了warp，当访问非谷歌系网站时仍显示warp的ip，而非本机ip，而使用Air-Universe后端时，访问非谷歌系网站以本机ip显示，访问谷歌系网站以warp的ip显示

**Comment by RManLuo** [comment]
缺少默认路由配置，此时只有访问谷歌系网站使用google outbound，此时应该为ipv4，其他网站默认走XrayR生成的出口，而不是你设置的第一一条，请自己查看文档解决。
