### ISSUE TITLE
How to enable TCP Fast Open for default inbound？

### ISSUE THREAD

**Issue by tearfulDalvik** [XrayR-project/XrayR#565]
Or, how to customize streamSettings for default inbound

Thank you

**Comment by MrVb0** [comment]
how can i use tcpnodelay / tcpfastopen / mptcp in xrayr?

**Comment by tearfulDalvik** [comment]
> how can i use tcpnodelay / tcpfastopen / mptcp in xrayr?

I checked the code. No way unless you build your own binary
