### ISSUE TITLE
不对接第三方面板如何使用

### ISSUE THREAD

**Issue by xhrm** [XrayR-project/XrayR#57]
是否支持例如
https://github.com/XTLS/Xray-examples/blob/main/Trojan-TCP-TLS%20(minimal)/config_server.json
这样的配置文件
实现不对接面板进行password进行校验使用，

**Comment by RManLuo** [comment]
暂未支持，不对接第三方为啥不直接使用xray-core（

**Comment by xhrm** [comment]
> 暂未支持，不对接第三方为啥不直接使用xray-core（

他那个不支持限速和限制IP
