### ISSUE TITLE
该版本目前存在重复统计上报流量问题

### ISSUE THREAD

**Issue by jiasu9527** [XrayR-project/XrayR#570]
目前对接V2Board无特定条件下会出现 重启后就恢复了 已经遇到好几次了

**Comment by themojie** [comment]
这个功能的初衷是好的，可以确保流量上报成功而不是直接丢弃。

但是很显然，没有考虑过如果网站系统或者网络出现问题，上报成功，但是没有返回成功，导致重复多次上报的情况。

我在 https://github.com/XrayR-project/XrayR/issues/106 反馈过一次，说是可能会考虑在后续版本增加一个可选开关。现在看是没有这个打算了。

但是在丢失流量统计数据和重复多次统计数据之间，我认为丢失是合理的。我可以为了防止丢失去优化系统，但是我不认为应该担心系统出问题时被xrayr灌入一堆数据。
