### ISSUE TITLE
0.7.2太占内存了。。。

### ISSUE THREAD

**Issue by pingProMax** [XrayR-project/XrayR#58]
1H1G 开两个带不动！

**Comment by pingProMax** [comment]
![image](https://user-images.githubusercontent.com/44503794/135040808-086ac0f3-05c1-45ca-b6d8-5fb10e7b306d.png)
开一个勉强能运行

**Comment by RManLuo** [comment]
请提供不同版本的下的内存占用对比。

**Comment by pingProMax** [comment]
老版本：
![image](https://user-images.githubusercontent.com/44503794/135073240-3111bbe7-eef1-462f-b135-ea73edefc18a.png)

新版本：
![image](https://user-images.githubusercontent.com/44503794/135073268-809123ed-55aa-460e-9aa0-4868ede23edb.png)

**Comment by pingProMax** [comment]
通常情况下 我都是   每个服务器开两个服务，自从用最新的版本后  开两个服务就内存溢出了

**Comment by NutterChen** [comment]
@pingProMax 没问题啊 32g内存带5万个客户 客户没有用的时候不占用内存

**Comment by RManLuo** [comment]
可能是更新版本，软件自动重启之后线程没有完全释放，尝试kill -9 进程之后再重新启动查看内存占用。

**Comment by pingProMax** [comment]
好吧  可能是我的问题。
