### ISSUE TITLE
流量由主 outbound 发出 没有作用

### ISSUE THREAD

**Issue by cdnov** [XrayR-project/XrayR#580]
[列表中的第一个元素作为主 outbound。当路由匹配不存在或没有匹配成功时，流量由主 outbound 发出。](https://xtls.github.io/config/outbound.html#outboundobject)

`OutboundConfigPath: /etc/XrayR/custom_outbound.json`

`[
  {
    "protocol": "blackhole",
    "settings": {}
  }
]
`

**Comment by nagaame** [comment]
协议应改成`freedom`，`blackhole`协议的作用是拦截所有数据

**Comment by gaowanliang** [comment]
xrayr必须搭配route.json使用，估计是bug

一个代理所有非国内域名的例子
```json
    {
      "type": "field",
      "outboundTag": "IPv4_out",
      "domain": ["geosite:geolocation-!cn"]
    },
 ```
