### ISSUE TITLE
配置了custom_outbound.json文件出站流量走代理不生效

### ISSUE THREAD

**Issue by lwjsgzs** [XrayR-project/XrayR#586]
[列表中的第一个元素作为主 outbound。当路由匹配不存在或没有匹配成功时，流量由主 outbound 发出。](https://xtls.github.io/config/outbound.html#outboundobject)
OutboundConfigPath: /etc/XrayR/custom_outbound.json
在config里面配置了出站流量路径后。
在custom_outbound.json里面填写了socks5的信息，重启xrayr程序也显示成功，但是使用后发现流量还是没有走出站配置文件里面的规则。socks5代理不生效，还是服务器原IP。

我想实现前端用户订阅后节点的全部出站流量都走socks5代理，但是按照文档教程配置好后不生效，请各位大佬看看是上面情况。log里面也没有报错信息。

**Comment by lwjsgzs** [comment]
看了一下前面有人问过类似的问题，但是我跟着评论里的设置了route文件后也不生效。
config：
RouteConfigPath: /etc/XrayR/route.json
route.json：
   {
      "type": "field",
      "outboundTag": "IPv4_out",
      "domain": ["geosite:geolocation-!cn"]
    }
同样是重启不报错正常运行，但是流量不走代理配置

**Comment by lwjsgzs** [comment]
[
        {
            "tag": "IPv4_out",
            "protocol": "socks",
            "settings": {
                "servers": [
                    {
                        "address": "ip",
                        "port": 端口,
                        "users": [
                            {
                                "user": "用户名",
                                "pass": "密码",
                                "level": 0
                            }
                        ]
                    }
                ]
            }
        },
        {
            "protocol": "blackhole",
            "tag": "block"
        }
    ]

**Comment by thank243** [comment]
Pls read the guide carefully. https://xrayr-project.github.io/XrayR-doc/gong-neng-shuo-ming/zi-ding-yi-chu-kou-gong-neng-shuo-ming.html
