### ISSUE TITLE
wss+cloudflare cdn节点打不开问题

### ISSUE THREAD

**Issue by morning624** [XrayR-project/XrayR#587]
v2board用的1.7.4
xrary用的0.9.0

节点搭建vmess+ws+tls 端口是443 节点套的couldflare cdn

xrayr后台运行正常，但是连接节点打不开网页，其他机器同样的配置可以打开。

想问下是机器架构问题还是需要升级xray内核啥的，求指教，谢谢。

这个是错误日志

<img width="816" alt="image" src="https://github.com/XrayR-project/XrayR/assets/10881883/eda51cfd-ef0e-4619-9d48-cee9f1fdfa7a">

**Comment by thank243** [comment]
Ask your IDC for helping.
