### ISSUE TITLE
关于tor浏览器不能使用的问题

### ISSUE THREAD

**Issue by weibaobao6688** [XrayR-project/XrayR#59]
环境是版本是0.7.2使用的面板是sspanel, v2ray 其他服务都一切正常,唯独tor浏览器无法使用,一直建立连接失败

**Comment by RManLuo** [comment]
请提供详细log

**Comment by weibaobao6688** [comment]
服务器日志access.Log
021/09/30 10:56:20 113.122.216.112:15172 accepted tcp:www.pslkuuf2jhxzojp4y.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:20 113.122.216.112:15171 accepted tcp:www.cpuo6gm5z7s4fey.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:22 113.122.216.112:15173 accepted tcp:www.6bqs.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:25 113.122.216.112:15179 accepted tcp:www.zpx2bbvbjszms54h.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:25 113.122.216.112:15180 accepted tcp:www.wjljvhvpv4swgu.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:27 113.122.216.112:15187 accepted tcp:www.xxji4vuww5x3aoy34nq.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:28 113.122.216.112:15188 accepted tcp:www.ojhmye5psmkgu4x.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:28 113.122.216.112:15189 accepted tcp:www.no4uhsxtdixrglz.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:29 113.122.216.112:15191 accepted tcp:www.nyf2mq3p6omlgcxwv5h.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:29 113.122.216.112:15192 accepted tcp:www.es4ygqacwwkuud4u2ysgb.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:30 113.122.216.112:15193 accepted tcp:www.7inrjib.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1
2021/09/30 10:56:31 113.122.216.112:15197 accepted tcp:www.ae7c3jg3cc5farxyrpebwg2.com:443 [V2ray_15252 >> V2ray_15252] email: V2ray_15252|admin@gmail.com|1


服务器日志error.log
2021/09/30 10:55:06 [Debug] app/log: Logger started
2021/09/30 10:55:06 [Info] app/dns: DNS: created localhost client
2021/09/30 10:55:06 [Warning] core: Xray 1.4.5 started
2021/09/30 10:55:06 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:15252
2021/09/30 10:55:06 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:15252
2021/09/30 10:55:07 [Debug] app/log: Logger closing
2021/09/30 10:55:07 [Debug] app/log: Logger started
2021/09/30 10:55:07 [Info] app/dns: DNS: created localhost client
2021/09/30 10:55:07 [Warning] core: Xray 1.4.5 started
2021/09/30 10:55:07 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:15252
2021/09/30 10:55:07 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:15252
2021/09/30 10:55:28 [Debug] app/log: Logger started
2021/09/30 10:55:28 [Info] app/dns: DNS: created localhost client
2021/09/30 10:55:28 [Warning] core: Xray 1.4.5 started
2021/09/30 10:55:28 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:15252
2021/09/30 10:55:28 [Info] transport/internet/websocket: listening TCP(for WS) on 0.0.0.0:15252
2021/09/30 10:56:20 [Warning] proxy/vmess/encoding: Critical Warning: potentially invalid user: a non VMessAEAD connection is received. From 2022 Jan 1st, this kind of connection will be rejected by default. You should update or replace your client software now. This message will not be shown for further violation on this inbound.
2021/09/30 10:56:20 [Info] [2991491898] proxy/vmess/inbound: received request for tcp:www.pslkuuf2jhxzojp4y.com:443
2021/09/30 10:56:20 [Debug] app/stats: create new counter user>>>V2ray_15252|admin@gmail.com|1>>>traffic>>>uplink
2021/09/30 10:56:20 [Debug] app/stats: create new counter user>>>V2ray_15252|admin@gmail.com|1>>>traffic>>>downlink
2021/09/30 10:56:20 [Info] [2991491898] rayR/app/mydispatcher: sniffed domain: www.pslkuuf2jhxzojp4y.com
2021/09/30 10:56:20 [Info] [2991491898] rayR/app/mydispatcher: default route for tcp:www.pslkuuf2jhxzojp4y.com:443
2021/09/30 10:56:20 [Info] [2991491898] proxy/freedom: opening connection to tcp:www.pslkuuf2jhxzojp4y.com:443
2021/09/30 10:56:20 [Info] [2991491898] transport/internet/tcp: dialing TCP to tcp:www.pslkuuf2jhxzojp4y.com:443
2021/09/30 10:56:20 [Debug] transport/internet: dialing to tcp:www.pslkuuf2jhxzojp4y.com:443
2021/09/30 10:56:20 [Info] [765710592] proxy/vmess/inbound: received request for tcp:www.cpuo6gm5z7s4fey.com:443
2021/09/30 10:56:20 [Info] [765710592] rayR/app/mydispatcher: sniffed domain: www.cpuo6gm5z7s4fey.com
2021/09/30 10:56:20 [Info] [765710592] rayR/app/mydispatcher: default route for tcp:www.cpuo6gm5z7s4fey.com:443
2021/09/30 10:56:20 [Info] [765710592] proxy/freedom: opening connection to tcp:www.cpuo6gm5z7s4fey.com:443
2021/09/30 10:56:20 [Info] [765710592] transport/internet/tcp: dialing TCP to tcp:www.cpuo6gm5z7s4fey.com:443
2021/09/30 10:56:20 [Debug] transport/internet: dialing to tcp:www.cpuo6gm5z7s4fey.com:443
2021/09/30 10:56:21 [Info] [765710592] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:21 [Info] [2991491898] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:22 [Info] [2695547827] proxy/vmess/inbound: received request for tcp:www.6bqs.com:443
2021/09/30 10:56:22 [Info] [2695547827] rayR/app/mydispatcher: sniffed domain: www.6bqs.com
2021/09/30 10:56:22 [Info] [2695547827] rayR/app/mydispatcher: default route for tcp:www.6bqs.com:443
2021/09/30 10:56:22 [Info] [2695547827] proxy/freedom: opening connection to tcp:www.6bqs.com:443
2021/09/30 10:56:22 [Info] [2695547827] transport/internet/tcp: dialing TCP to tcp:www.6bqs.com:443
2021/09/30 10:56:22 [Debug] transport/internet: dialing to tcp:www.6bqs.com:443
2021/09/30 10:56:24 [Info] [2695547827] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > proxy/vmess/inbound: failed to transfer request > websocket: close 1000 (normal)
2021/09/30 10:56:24 [Info] [2695547827] app/proxyman/inbound: failed to close connection > transport/internet/websocket: failed to close connection > transport/internet/websocket: websocket: close sent
2021/09/30 10:56:24 [Info] [2695547827] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:25 [Info] [2760343546] proxy/vmess/inbound: received request for tcp:www.zpx2bbvbjszms54h.com:443
2021/09/30 10:56:25 [Info] [2760343546] rayR/app/mydispatcher: sniffed domain: www.zpx2bbvbjszms54h.com
2021/09/30 10:56:25 [Info] [2760343546] rayR/app/mydispatcher: default route for tcp:www.zpx2bbvbjszms54h.com:443
2021/09/30 10:56:25 [Info] [2760343546] proxy/freedom: opening connection to tcp:www.zpx2bbvbjszms54h.com:443
2021/09/30 10:56:25 [Info] [2760343546] transport/internet/tcp: dialing TCP to tcp:www.zpx2bbvbjszms54h.com:443
2021/09/30 10:56:25 [Debug] transport/internet: dialing to tcp:www.zpx2bbvbjszms54h.com:443
2021/09/30 10:56:25 [Info] [2019761652] proxy/vmess/inbound: received request for tcp:www.wjljvhvpv4swgu.com:443
2021/09/30 10:56:25 [Info] [2019761652] rayR/app/mydispatcher: sniffed domain: www.wjljvhvpv4swgu.com
2021/09/30 10:56:25 [Info] [2019761652] rayR/app/mydispatcher: default route for tcp:www.wjljvhvpv4swgu.com:443
2021/09/30 10:56:25 [Info] [2019761652] proxy/freedom: opening connection to tcp:www.wjljvhvpv4swgu.com:443
2021/09/30 10:56:25 [Info] [2019761652] transport/internet/tcp: dialing TCP to tcp:www.wjljvhvpv4swgu.com:443
2021/09/30 10:56:25 [Debug] transport/internet: dialing to tcp:www.wjljvhvpv4swgu.com:443
2021/09/30 10:56:26 [Info] [2019761652] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > proxy/vmess/inbound: failed to transfer request > websocket: close 1000 (normal)
2021/09/30 10:56:26 [Info] [2019761652] app/proxyman/inbound: failed to close connection > transport/internet/websocket: failed to close connection > transport/internet/websocket: websocket: close sent
2021/09/30 10:56:26 [Info] [2019761652] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:27 [Info] [3110842019] proxy/vmess/inbound: received request for tcp:www.xxji4vuww5x3aoy34nq.com:443
2021/09/30 10:56:27 [Info] [3110842019] rayR/app/mydispatcher: sniffed domain: www.xxji4vuww5x3aoy34nq.com
2021/09/30 10:56:27 [Info] [3110842019] rayR/app/mydispatcher: default route for tcp:www.xxji4vuww5x3aoy34nq.com:443
2021/09/30 10:56:27 [Info] [3110842019] proxy/freedom: opening connection to tcp:www.xxji4vuww5x3aoy34nq.com:443
2021/09/30 10:56:27 [Info] [3110842019] transport/internet/tcp: dialing TCP to tcp:www.xxji4vuww5x3aoy34nq.com:443
2021/09/30 10:56:27 [Debug] transport/internet: dialing to tcp:www.xxji4vuww5x3aoy34nq.com:443
2021/09/30 10:56:28 [Info] [4234485433] proxy/vmess/inbound: received request for tcp:www.ojhmye5psmkgu4x.com:443
2021/09/30 10:56:28 [Info] [4234485433] rayR/app/mydispatcher: sniffed domain: www.ojhmye5psmkgu4x.com
2021/09/30 10:56:28 [Info] [4234485433] rayR/app/mydispatcher: default route for tcp:www.ojhmye5psmkgu4x.com:443
2021/09/30 10:56:28 [Info] [4234485433] proxy/freedom: opening connection to tcp:www.ojhmye5psmkgu4x.com:443
2021/09/30 10:56:28 [Info] [4234485433] transport/internet/tcp: dialing TCP to tcp:www.ojhmye5psmkgu4x.com:443
2021/09/30 10:56:28 [Debug] transport/internet: dialing to tcp:www.ojhmye5psmkgu4x.com:443
2021/09/30 10:56:28 [Info] [717256243] proxy/vmess/inbound: received request for tcp:www.no4uhsxtdixrglz.com:443
2021/09/30 10:56:28 [Info] [717256243] rayR/app/mydispatcher: sniffed domain: www.no4uhsxtdixrglz.com
2021/09/30 10:56:28 [Info] [717256243] rayR/app/mydispatcher: default route for tcp:www.no4uhsxtdixrglz.com:443
2021/09/30 10:56:28 [Info] [717256243] proxy/freedom: opening connection to tcp:www.no4uhsxtdixrglz.com:443
2021/09/30 10:56:28 [Info] [717256243] transport/internet/tcp: dialing TCP to tcp:www.no4uhsxtdixrglz.com:443
2021/09/30 10:56:28 [Debug] transport/internet: dialing to tcp:www.no4uhsxtdixrglz.com:443
2021/09/30 10:56:28 [Info] [2760343546] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled
2021/09/30 10:56:28 [Info] [2760343546] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:28 [Info] [3110842019] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:28 [Info] [4234485433] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:29 [Info] [717256243] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:29 [Info] [2574451110] proxy/vmess/inbound: received request for tcp:www.nyf2mq3p6omlgcxwv5h.com:443
2021/09/30 10:56:29 [Info] [2574451110] rayR/app/mydispatcher: sniffed domain: www.nyf2mq3p6omlgcxwv5h.com
2021/09/30 10:56:29 [Info] [2574451110] rayR/app/mydispatcher: default route for tcp:www.nyf2mq3p6omlgcxwv5h.com:443
2021/09/30 10:56:29 [Info] [2574451110] proxy/freedom: opening connection to tcp:www.nyf2mq3p6omlgcxwv5h.com:443
2021/09/30 10:56:29 [Info] [2574451110] transport/internet/tcp: dialing TCP to tcp:www.nyf2mq3p6omlgcxwv5h.com:443
2021/09/30 10:56:29 [Debug] transport/internet: dialing to tcp:www.nyf2mq3p6omlgcxwv5h.com:443
2021/09/30 10:56:29 [Info] [2572206712] proxy/vmess/inbound: received request for tcp:www.es4ygqacwwkuud4u2ysgb.com:443
2021/09/30 10:56:29 [Info] [2572206712] rayR/app/mydispatcher: sniffed domain: www.es4ygqacwwkuud4u2ysgb.com
2021/09/30 10:56:29 [Info] [2572206712] rayR/app/mydispatcher: default route for tcp:www.es4ygqacwwkuud4u2ysgb.com:443
2021/09/30 10:56:29 [Info] [2572206712] proxy/freedom: opening connection to tcp:www.es4ygqacwwkuud4u2ysgb.com:443
2021/09/30 10:56:29 [Info] [2572206712] transport/internet/tcp: dialing TCP to tcp:www.es4ygqacwwkuud4u2ysgb.com:443
2021/09/30 10:56:29 [Debug] transport/internet: dialing to tcp:www.es4ygqacwwkuud4u2ysgb.com:443
2021/09/30 10:56:30 [Info] [217718231] proxy/vmess/inbound: received request for tcp:www.7inrjib.com:443
2021/09/30 10:56:30 [Info] [217718231] rayR/app/mydispatcher: sniffed domain: www.7inrjib.com
2021/09/30 10:56:30 [Info] [217718231] rayR/app/mydispatcher: default route for tcp:www.7inrjib.com:443
2021/09/30 10:56:30 [Info] [217718231] proxy/freedom: opening connection to tcp:www.7inrjib.com:443
2021/09/30 10:56:30 [Info] [217718231] transport/internet/tcp: dialing TCP to tcp:www.7inrjib.com:443
2021/09/30 10:56:30 [Debug] transport/internet: dialing to tcp:www.7inrjib.com:443
2021/09/30 10:56:30 [Info] [2574451110] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > proxy/vmess/inbound: failed to transfer request > websocket: close 1000 (normal)
2021/09/30 10:56:30 [Info] [2574451110] app/proxyman/inbound: failed to close connection > transport/internet/websocket: failed to close connection > transport/internet/websocket: websocket: close sent
2021/09/30 10:56:30 [Info] [2574451110] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:31 [Info] [2931725433] proxy/vmess/inbound: received request for tcp:www.ae7c3jg3cc5farxyrpebwg2.com:443
2021/09/30 10:56:31 [Info] [2931725433] rayR/app/mydispatcher: sniffed domain: www.ae7c3jg3cc5farxyrpebwg2.com
2021/09/30 10:56:31 [Info] [2931725433] rayR/app/mydispatcher: default route for tcp:www.ae7c3jg3cc5farxyrpebwg2.com:443
2021/09/30 10:56:31 [Info] [2931725433] proxy/freedom: opening connection to tcp:www.ae7c3jg3cc5farxyrpebwg2.com:443
2021/09/30 10:56:31 [Info] [2931725433] transport/internet/tcp: dialing TCP to tcp:www.ae7c3jg3cc5farxyrpebwg2.com:443
2021/09/30 10:56:31 [Debug] transport/internet: dialing to tcp:www.ae7c3jg3cc5farxyrpebwg2.com:443
2021/09/30 10:56:31 [Info] [217718231] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:31 [Info] [2572206712] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:39 [Info] [2931725433] app/proxyman/outbound: failed to process outbound traffic > proxy/freedom: connection ends > context canceled
2021/09/30 10:56:39 [Info] [2931725433] app/proxyman/inbound: connection ends > proxy/vmess/inbound: connection ends > context canceled


Windows下的tor客户端日志如下
9/30/21, 14:56:18.795 [NOTICE] New control connection opened from 127.0.0.1.
9/30/21, 14:56:18.820 [NOTICE] New control connection opened from 127.0.0.1.
9/30/21, 14:56:18.882 [NOTICE] New control connection opened from 127.0.0.1.
9/30/21, 14:56:20.496 [NOTICE] Opening Socks listener on 127.0.0.1:9150
9/30/21, 14:56:20.496 [NOTICE] Opened Socks listener connection (ready) on 127.0.0.1:9150
9/30/21, 14:56:20.496 [NOTICE] Bootstrapped 3% (conn_proxy): Connecting to proxy
9/30/21, 14:56:20.498 [NOTICE] Bootstrapped 4% (conn_done_proxy): Connected to proxy
9/30/21, 14:56:20.499 [NOTICE] Bootstrapped 10% (conn_done): Connected to a relay
9/30/21, 14:56:21.461 [NOTICE] Bootstrapped 14% (handshake): Handshaking with a relay
9/30/21, 14:56:32.212 [WARN] Problem bootstrapping. Stuck at 14% (handshake): Handshaking with a relay. (DONE; DONE; count 10; recommendation warn; host E7EF73B4722CFAF0E8AA2151D3AA78701DE5F19B at 178.254.22.21:443)
9/30/21, 14:56:32.212 [WARN] 10 connections have failed:
9/30/21, 14:56:32.213 [WARN] 10 connections died in state handshaking (Tor, v3 handshake) with SSL state SSL negotiation finished successfully in CLOSED
9/30/21, 14:56:32.278 [NOTICE] Closing no-longer-configured Socks listener on 127.0.0.1:9150
9/30/21, 14:56:32.278 [NOTICE] DisableNetwork is set. Tor will not make or accept non-control network connections. Shutting down all existing connections.
9/30/21, 14:56:32.278 [WARN] Problem bootstrapping. Stuck at 14% (handshake): Handshaking with a relay. (DONE; DONE; count 11; recommendation warn; host DF7AA16E1A6037C5FCBB4DED4F3A6CD262CA3799 at 195.154.253.226:443)
9/30/21, 14:56:32.278 [WARN] 11 connections have failed:
9/30/21, 14:56:32.278 [WARN] 10 connections died in state handshaking (Tor, v3 handshake) with SSL state SSL negotiation finished successfully in CLOSED
9/30/21, 14:56:32.278 [WARN] 1 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
9/30/21, 14:56:32.287 [WARN] Problem bootstrapping. Stuck at 14% (handshake): Handshaking with a relay. (DONE; DONE; count 12; recommendation warn; host 6C333B5BDBA3DFE7A782E40CB970C271ABFED119 at 85.17.127.129:443)
9/30/21, 14:56:32.287 [WARN] 12 connections have failed:
9/30/21, 14:56:32.287 [WARN] 10 connections died in state handshaking (Tor, v3 handshake) with SSL state SSL negotiation finished successfully in CLOSED
9/30/21, 14:56:32.287 [WARN] 1 connections died in state handshaking (Tor, v3 handshake) with SSL state SSL negotiation finished successfully in OPEN
9/30/21, 14:56:32.287 [WARN] 1 connections died in state handshaking (TLS) with SSL state SSLv3/TLS write client hello in HANDSHAKE
9/30/21, 14:56:32.763 [NOTICE] Delaying directory fetches: DisableNetwork is set.

windwos下的v2rayn客户端Verror.log日志
2021/09/30 22:47:26 [Warning] v2ray.com/core: V2Ray 4.31.0 started

Vaccess.log
2021/09/30 22:47:26 127.0.0.1:63236 accepted tcp:127.0.0.1:0 [api] 
2021/09/30 22:56:20 127.0.0.1:53718 accepted //51.89.143.152:443 [proxy] 
2021/09/30 22:56:20 127.0.0.1:53717 accepted //193.182.61.9:443 [proxy] 
2021/09/30 22:56:20 127.0.0.1:53721 accepted //195.154.241.145:443 [proxy] 
2021/09/30 22:56:25 127.0.0.1:53727 accepted //94.130.183.13:443 [proxy] 
2021/09/30 22:56:25 127.0.0.1:53728 accepted //54.36.237.163:443 [proxy] 
2021/09/30 22:56:26 127.0.0.1:51245 accepted //62.210.205.228:443 [proxy] 
2021/09/30 22:56:27 127.0.0.1:51247 accepted //172.106.12.246:443 [proxy] 
2021/09/30 22:56:28 127.0.0.1:51249 accepted //54.86.185.91:443 [proxy] 
2021/09/30 22:56:29 127.0.0.1:53296 accepted //85.17.127.129:443 [proxy] 
2021/09/30 22:56:29 127.0.0.1:53295 accepted //51.75.129.204:443 [proxy] 
2021/09/30 22:56:30 127.0.0.1:53299 accepted //178.254.22.21:443 [proxy] 
2021/09/30 22:56:31 127.0.0.1:53301 accepted //195.154.253.226:443 [proxy]

**Comment by weibaobao6688** [comment]
大佬,这个怎么解决

**Comment by RManLuo** [comment]
应该是由于服务端开起了sniffing功能导致，tor连接失败。后续会增加关闭开关。

**Comment by crackair** [comment]
fdf050f
