### ISSUE TITLE
报错：Parse config file %!s(*string=0xc00049a8f0) failed: 1 error(s) decoding:

### ISSUE THREAD

**Issue by Code-CJ** [XrayR-project/XrayR#60]
Sep 28 08:28:40 VM35703 systemd[1]: Started XrayR Service.
Sep 28 08:28:40 VM35703 XrayR[16833]: XrayR 0.8.4 (A Xray backend that supports many panels)
Sep 28 08:28:40 VM35703 XrayR[16833]: 2022/09/28 08:28:40 Parse config file %!s(*string=0xc00049a8f0) failed: 1 error(s) decoding:
Sep 28 08:28:40 VM35703 XrayR[16833]: * 'Nodes[0].ControllerConfig.CertConfig.DNSEnv' expected a map, got 'string'
Sep 28 08:28:40 VM35703 XrayR[16833]: panic: Parse config file %!s(*string=0xc00049a8f0) failed: 1 error(s) decoding:
Sep 28 08:28:40 VM35703 XrayR[16833]: * 'Nodes[0].ControllerConfig.CertConfig.DNSEnv' expected a map, got 'string'
Sep 28 08:28:40 VM35703 XrayR[16833]: goroutine 1 [running]:
Sep 28 08:28:40 VM35703 XrayR[16833]: log.Panicf({0x21843b5?, 0x1b48c20?}, {0xc00053ff18?, 0x0?, 0x0?})
Sep 28 08:28:40 VM35703 XrayR[16833]:         log/log.go:395 +0x67
Sep 28 08:28:40 VM35703 XrayR[16833]: main.main()
Sep 28 08:28:40 VM35703 XrayR[16833]:         github.com/XrayR-project/XrayR/main/main.go:77 +0x130
Sep 28 08:28:40 VM35703 systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 28 08:28:40 VM35703 systemd[1]: XrayR.service: Failed with result 'exit-code'.

试了centos7+debian10 都更新了系统
还是出现这个问题

**Comment by JoshuaCylinder** [comment]
DNSEnv配错了，贴下配置吧，敏感信息打码
