### ISSUE TITLE
我怎么对接Xboard 一直提示token错误

### ISSUE THREAD

**Issue by bbhxwl** [XrayR-project/XrayR#603]
支持这个面板么？我输入的apikey就是面板里面的【通讯密钥】呢，一直错误，不知道怎么设置、

**Comment by JobberRT** [comment]
I have already start an example issue in `XBoard` repo, check that out.
https://github.com/cedar2025/Xboard/issues/73

And with no log, no config file, no any useful information, I suggest this issue should be closed.
