### ISSUE TITLE
对接sspenal-metron的shadowsocks，XrayR报错.找不到单端口多用户？已经创建承载端口和承载用户。

### ISSUE THREAD

**Issue by WaldenTwo** [XrayR-project/XrayR#615]
emd[1]: Unit XrayR.service entered failed state.
emd[1]: XrayR.service failed.
emd[1]: XrayR.service holdoff time over, scheduling restart.
emd[1]: Stopped XrayR Service.
emd[1]: Started XrayR Service.
R[25788]: XrayR 0.9.0 (A Xray backend that supports many panels)
R[25788]: 2024/03/17 00:20:24 Start the panel..
R[25788]: 2024/03/17 00:20:24 Xray Core Version: 1.7.5
R[25788]: 2024/03/17 00: 20: 24 [Warning] core: Xray 1.7.5 started
R(25788): 2024/03/17 00:20:25 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":1, 'node _speedlimit":0, "traffic_rate":1, "mu_only":1, "sort
","type": "ss-panel-v3-mod_Uim","custom_config":null,"version":"},
R[25788]: Error: cant find the single port multi user
R[25788]: panic: Panel Start fialed: Parse node info failed: ("node group":0, node class":1, node speedlinit":0,"traffic rate":1, "mu oly":l, "sort:0,server":
panel-v3-mod_Uim","custom_config": null,"version":"],
R[25788]: Error: cant find the single port multi user
R[25788]: goroutine 1 [running]:
R[25788]: log.Panicf({0x3283dcd?, 0x3706700?}, {Oxc000b09e80?, Oxc0002ce680?, 0x2b3a6c0?})
R[25788]: log/log.go:391 +0x67
R[25788]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0005c50c0)
R[25788]: github.com/XrayR-project/XrayR/panel/panel.go:211 +0x59b
R[25788]: main.main()
R[25788]: github.com/XrayR-project/XrayR/main/main.go:97 +0x250

**Comment by 369713387** [comment]
请问找到解决方案了吗

**Comment by WaldenTwo** [comment]
> 求找到解决方案了吗

还没有
