### ISSUE TITLE
用户为同一C段下的动态IP, DeviceLimit存在误判情况

### ISSUE THREAD

**Issue by laughtale233** [XrayR-project/XrayR#63]
如图, 同个C段下的动态IP, 每次网络请求, 用户的IP都不同, 此时会频繁触发Device reach the limit,  但确实是同个用户.
判断CIDR x.x.x.0/24为同一用户会不会更合理.
![CleanShot 2021-10-11 at 09 46 10@2x](https://user-images.githubusercontent.com/90945633/136722644-b5dc85f2-082f-4278-a950-d17e0de34806.png)

**Comment by crackair** [comment]
@laughtale233 我觉得针对动态ip行为，采取不限制设备，只限制流量的举措可能更加合适。
