### ISSUE TITLE
当前commit版本与sspanel-uim（next-panel）不兼容

### ISSUE THREAD

**Issue by zesty-zesty** [XrayR-project/XrayR#642]

**Comment by RyanRaw** [comment]
是不兼容的原因？我也升级到了next panel，节点起不来
`Recreating xrayrrelease_xrayr_1 ... done
Attaching to xrayrrelease_xrayr_1
xrayr_1  | XrayR 0.9.2 (A Xray backend that supports many panels) 
xrayr_1  | time="2024-06-03T10:06:39+08:00" level=info msg="Start the panel.."
xrayr_1  | 2024/06/03 10:06:39 [Warning] core: Xray 1.8.10 started
xrayr_1  | time="2024-06-03T10:06:39+08:00" level=info msg="The panel version is expired, it is recommended to update immediately"
xrayr_1  | panic: runtime error: index out of range [1] with length 1
xrayr_1  | 
xrayr_1  | goroutine 1 [running]:
xrayr_1  | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).ParseV2rayNodeResponse(0xc0018f62c0, 0xc000d6ca80)
xrayr_1  |      github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:421 +0x885
xrayr_1  | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).GetNodeInfo(0xc0018f62c0)
xrayr_1  |      github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:199 +0x936
xrayr_1  | github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0018d0d80)
xrayr_1  |      github.com/XrayR-project/XrayR/service/controller/controller.go:82 +0xe2
xrayr_1  | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00186d340)
xrayr_1  |      github.com/XrayR-project/XrayR/panel/panel.go:209 +0x5ca
xrayr_1  | github.com/XrayR-project/XrayR/cmd.run()
xrayr_1  |      github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5
xrayr_1  | github.com/XrayR-project/XrayR/cmd.init.func1(0xc0018aa400?, {0x4438a46?, 0x4?, 0x4438936?})
xrayr_1  |      github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13
xrayr_1  | github.com/spf13/cobra.(*Command).execute(0x77e6d60, {0xc000072970, 0x2, 0x2})
xrayr_1  |      github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
xrayr_1  | github.com/spf13/cobra.(*Command).ExecuteC(0x77e6d60)
xrayr_1  |      github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
xrayr_1  | github.com/spf13/cobra.(*Command).Execute(...)
xrayr_1  |      github.com/spf13/cobra@v1.8.0/command.go:1039
xrayr_1  | github.com/XrayR-project/XrayR/cmd.Execute(...)
xrayr_1  |      github.com/XrayR-project/XrayR/cmd/root.go:120
xrayr_1  | main.main()
xrayr_1  |      github.com/XrayR-project/XrayR/main.go:10 +0x1a
xrayrrelease_xrayr_1 exited with code 2`

**Comment by zesty-zesty** [comment]
> 是不兼容的原因？我也升级到了next panel，节点起不来 Recreating xrayrrelease_xrayr_1 ... done Attaching to xrayrrelease_xrayr_1 xrayr_1 | XrayR 0.9.2 (A Xray backend that supports many panels) xrayr_1 | time="2024-06-03T10:06:39+08:00" level=info msg="Start the panel.." xrayr_1 | 2024/06/03 10:06:39 [Warning] core: Xray 1.8.10 started xrayr_1 | time="2024-06-03T10:06:39+08:00" level=info msg="The panel version is expired, it is recommended to update immediately" xrayr_1 | panic: runtime error: index out of range [1] with length 1 xrayr_1 | xrayr_1 | goroutine 1 [running]: xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).ParseV2rayNodeResponse(0xc0018f62c0, 0xc000d6ca80) xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:421 +0x885 xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).GetNodeInfo(0xc0018f62c0) xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:199 +0x936 xrayr_1 | github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0018d0d80) xrayr_1 | github.com/XrayR-project/XrayR/service/controller/controller.go:82 +0xe2 xrayr_1 | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00186d340) xrayr_1 | github.com/XrayR-project/XrayR/panel/panel.go:209 +0x5ca xrayr_1 | github.com/XrayR-project/XrayR/cmd.run() xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5 xrayr_1 | github.com/XrayR-project/XrayR/cmd.init.func1(0xc0018aa400?, {0x4438a46?, 0x4?, 0x4438936?}) xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13 xrayr_1 | github.com/spf13/cobra.(*Command).execute(0x77e6d60, {0xc000072970, 0x2, 0x2}) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1 xrayr_1 | github.com/spf13/cobra.(*Command).ExecuteC(0x77e6d60) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff xrayr_1 | github.com/spf13/cobra.(*Command).Execute(...) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:1039 xrayr_1 | github.com/XrayR-project/XrayR/cmd.Execute(...) xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:120 xrayr_1 | main.main() xrayr_1 | github.com/XrayR-project/XrayR/main.go:10 +0x1a xrayrrelease_xrayr_1 exited with code 2

我和你的报错一摸一样 我使用vless reality vision 无论如何配置都不对 报错：
`panic: runtime error: index out of range [1] with length 1`

**Comment by RyanRaw** [comment]
> > 是不兼容的原因？我也升级到了next panel，节点起不来 Recreating xrayrrelease_xrayr_1 ... done Attaching to xrayrrelease_xrayr_1 xrayr_1 | XrayR 0.9.2 (A Xray backend that supports many panels) xrayr_1 | time="2024-06-03T10:06:39+08:00" level=info msg="Start the panel.." xrayr_1 | 2024/06/03 10:06:39 [Warning] core: Xray 1.8.10 started xrayr_1 | time="2024-06-03T10:06:39+08:00" level=info msg="The panel version is expired, it is recommended to update immediately" xrayr_1 | panic: runtime error: index out of range [1] with length 1 xrayr_1 | xrayr_1 | goroutine 1 [running]: xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).ParseV2rayNodeResponse(0xc0018f62c0, 0xc000d6ca80) xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:421 +0x885 xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).GetNodeInfo(0xc0018f62c0) xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:199 +0x936 xrayr_1 | github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0018d0d80) xrayr_1 | github.com/XrayR-project/XrayR/service/controller/controller.go:82 +0xe2 xrayr_1 | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00186d340) xrayr_1 | github.com/XrayR-project/XrayR/panel/panel.go:209 +0x5ca xrayr_1 | github.com/XrayR-project/XrayR/cmd.run() xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5 xrayr_1 | github.com/XrayR-project/XrayR/cmd.init.func1(0xc0018aa400?, {0x4438a46?, 0x4?, 0x4438936?}) xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13 xrayr_1 | github.com/spf13/cobra.(*Command).execute(0x77e6d60, {0xc000072970, 0x2, 0x2}) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1 xrayr_1 | github.com/spf13/cobra.(*Command).ExecuteC(0x77e6d60) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff xrayr_1 | github.com/spf13/cobra.(*Command).Execute(...) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:1039 xrayr_1 | github.com/XrayR-project/XrayR/cmd.Execute(...) xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:120 xrayr_1 | main.main() xrayr_1 | github.com/XrayR-project/XrayR/main.go:10 +0x1a xrayrrelease_xrayr_1 exited with code 2
> 
> 我和你的报错一摸一样 我使用vless reality vision 无论如何配置都不对 报错： `panic: runtime error: index out of range [1] with length 1`

我用的是vmss+ws+tls，现在退回2024.1正式版了正常使用了，要用reality 的话要改代码。

**Comment by zesty-zesty** [comment]
> > > 是不兼容的原因？我也升级到了next panel，节点起不来 Recreating xrayrrelease_xrayr_1 ... done Attaching to xrayrrelease_xrayr_1 xrayr_1 | XrayR 0.9.2 (A Xray backend that supports many panels) xrayr_1 | time="2024-06-03T10:06:39+08:00" level=info msg="Start the panel.." xrayr_1 | 2024/06/03 10:06:39 [Warning] core: Xray 1.8.10 started xrayr_1 | time="2024-06-03T10:06:39+08:00" level=info msg="The panel version is expired, it is recommended to update immediately" xrayr_1 | panic: runtime error: index out of range [1] with length 1 xrayr_1 | xrayr_1 | goroutine 1 [running]: xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).ParseV2rayNodeResponse(0xc0018f62c0, 0xc000d6ca80) xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:421 +0x885 xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).GetNodeInfo(0xc0018f62c0) xrayr_1 | github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:199 +0x936 xrayr_1 | github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0018d0d80) xrayr_1 | github.com/XrayR-project/XrayR/service/controller/controller.go:82 +0xe2 xrayr_1 | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00186d340) xrayr_1 | github.com/XrayR-project/XrayR/panel/panel.go:209 +0x5ca xrayr_1 | github.com/XrayR-project/XrayR/cmd.run() xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5 xrayr_1 | github.com/XrayR-project/XrayR/cmd.init.func1(0xc0018aa400?, {0x4438a46?, 0x4?, 0x4438936?}) xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13 xrayr_1 | github.com/spf13/cobra.(*Command).execute(0x77e6d60, {0xc000072970, 0x2, 0x2}) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1 xrayr_1 | github.com/spf13/cobra.(*Command).ExecuteC(0x77e6d60) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff xrayr_1 | github.com/spf13/cobra.(*Command).Execute(...) xrayr_1 | github.com/spf13/cobra@v1.8.0/command.go:1039 xrayr_1 | github.com/XrayR-project/XrayR/cmd.Execute(...) xrayr_1 | github.com/XrayR-project/XrayR/cmd/root.go:120 xrayr_1 | main.main() xrayr_1 | github.com/XrayR-project/XrayR/main.go:10 +0x1a xrayrrelease_xrayr_1 exited with code 2
> > 
> > 
> > 我和你的报错一摸一样 我使用vless reality vision 无论如何配置都不对 报错： `panic: runtime error: index out of range [1] with length 1`
> 
> 我用的是vmss+ws+tls，现在退回2024.1正式版了正常使用了，要用reality 的话要改代码。

是的，sspanel那边在引入httpupgrade的那个commit后毫无征兆的删除了reality相关的代码。
我刚检查了源码，建议你检查一下前端custom_config中“tls”、“udp”、“allow_insecure”等配置的数值类型，有些是bool，有些是string。

**Comment by RyanRaw** [comment]
> custom_config中“tls”、“udp”、“allow_insecure”等配置

不会看啊，现在能用就不管了。

**Comment by AutisticShark** [comment]
> @AutisticShark

You may want to wait for the next panel's new node API to be completed and add that as a new node type, WebAPI will be phased out completely soon. Current XrayR compatibility is only maintained in the uim version 2024.1(the last uim version), and not in the next panel.
