### ISSUE TITLE
搭配 xboard面板，配置vless-vision-REALITY节点，异常报错

### ISSUE THREAD

**Issue by meichuanneiku** [XrayR-project/XrayR#644]
1、安装最新版但xray内核怎么是1.8.4呢，看代码中是1.8.10，请问这是为什么？
2、打印日志中报错：Panel Start fialed: request http://127.0.0.1:7001/api/v1/server/UniProxy/config failed: {"status":"fail","message":"server is not exist!","data":null,"error":null}, <nil>
Jun 04 14:10:38 LC02P20 XrayR[424834]: panic: Panel Start fialed: request http://127.0.0.1:7001/api/v1/server/UniProxy/config failed: {"status":"fail","message":"server is not exist!","data":null,"error":null}, <nil>
以下是我的配置文件其中红色框内是我自定义的配置请问是哪有有错误才导致报错的吗？

![image](https://github.com/XrayR-project/XrayR/assets/8164375/d9432185-93ef-4cca-af4a-0beccf3ef9a2)

**Comment by JobberRT** [comment]
If you had searched the issues for similar  problem ,you will find my answer 

https://github.com/XrayR-project/XrayR/issues/598

**Comment by JobberRT** [comment]
never mind, xrayr has released `v0.9.3` and it fixed this bug

**Comment by mengxin239** [comment]
我写完代码忘记发release了,这些问题在v0.9.3里都修复了
