### ISSUE TITLE
v0.9.3版本 docker部署报错

### ISSUE THREAD

**Issue by Gogoworks** [XrayR-project/XrayR#647]
Attaching to xrayr-release_xrayr_1
xrayr_1  | XrayR 0.9.3 (A Xray backend that supports many panels) 
xrayr_1  | time="2024-06-23T23:25:51+08:00" level=info msg="Start the panel.."
xrayr_1  | 2024/06/23 23:25:51 [Warning] core: Xray 1.8.13 started
xrayr_1  | time="2024-06-23T23:25:52+08:00" level=panic msg="Panel Start failed: users is null"
xrayr_1  | panic: (*logrus.Entry) 0xc000e9fdc0
xrayr_1  | 
xrayr_1  | goroutine 1 [running]:
xrayr_1  | github.com/sirupsen/logrus.(*Entry).log(0xc001995880, 0x0, {0xc0000d6ea0, 0x21})
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
xrayr_1  | github.com/sirupsen/logrus.(*Entry).Log(0xc001995880, 0x0, {0xc001ba3a00?, 0x1?, 0x1?})
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
xrayr_1  | github.com/sirupsen/logrus.(*Entry).Logf(0xc001995880, 0x0, {0x447dd00?, 0x1d?}, {0xc001ba3af0?, 0x5?, 0xc001992570?})
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
xrayr_1  | github.com/sirupsen/logrus.(*Logger).Logf(0x77ea080, 0x0, {0x447dd00, 0x16}, {0xc001ba3af0, 0x1, 0x1})
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/logger.go:154 +0x7c
xrayr_1  | github.com/sirupsen/logrus.(*Logger).Panicf(...)
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/logger.go:195
xrayr_1  | github.com/sirupsen/logrus.Panicf(...)
xrayr_1  |      github.com/sirupsen/logrus@v1.9.3/exported.go:219
xrayr_1  | github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00194da40)
xrayr_1  |      github.com/XrayR-project/XrayR/panel/panel.go:211 +0x619
xrayr_1  | github.com/XrayR-project/XrayR/cmd.run()
xrayr_1  |      github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5
xrayr_1  | github.com/XrayR-project/XrayR/cmd.init.func1(0xc0019a2700?, {0x4449209?, 0x4?, 0x44490f9?})
xrayr_1  |      github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13
xrayr_1  | github.com/spf13/cobra.(*Command).execute(0x7805600, {0xc0001042b0, 0x2, 0x2})
xrayr_1  |      github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
xrayr_1  | github.com/spf13/cobra.(*Command).ExecuteC(0x7805600)
xrayr_1  |      github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
xrayr_1  | github.com/spf13/cobra.(*Command).Execute(...)
xrayr_1  |      github.com/spf13/cobra@v1.8.0/command.go:1039
xrayr_1  | github.com/XrayR-project/XrayR/cmd.Execute(...)
xrayr_1  |      github.com/XrayR-project/XrayR/cmd/root.go:120
xrayr_1  | main.main()
xrayr_1  |      github.com/XrayR-project/XrayR/main.go:10 +0x1a
xrayr_1  | XrayR 0.9.3 (A Xray backend that supports many panels) 
xrayr_1  | time="2024-06-23T23:25:53+08:00" level=info msg="Start the panel.."
xrayr_1  | 2024/06/23 23:25:53 [Warning] core: Xray 1.8.13 started

image: ghcr.io/xrayr-project/xrayr:latest
sudo docker-compose up -d  启动后,查看以上日志.

希望得到帮助!

**Comment by Gogoworks** [comment]
config.yml

![Snipaste_2024-06-23_23-30-13](https://github.com/XrayR-project/XrayR/assets/127202447/7eaefa01-aaba-4c72-9017-e0ebb398bda9)

**Comment by ScalaFirst** [comment]
我也是报这个错，对接的最新版Xboard
