### ISSUE TITLE
XrayR 套 cloudflare CDN 无法正常使用

### ISSUE THREAD

**Issue by greatbody** [XrayR-project/XrayR#654]
此前使用 x-ui 配置的时候，套 cloudflare cdn 正常使用。

但是在 XrayR 配置的时候遇到问题。似乎 XrayR 需要去生成证书？可是 cloudflare 套 cdn 后自身会创建证书啊，不需要我们再生成证书才对啊。奇怪。

**Comment by theresaarcher** [comment]
Hello,

Thank you for issue. Cloudflare provides several SSL options, and we need detailed configuration information to diagnose and solve your issue effectively.

Here are the SSL options that Cloudflare offers:

Flexible SSL: Encrypts traffic between your browser and Cloudflare, but not between Cloudflare and your server.
Full SSL: Encrypts traffic between your browser and Cloudflare, and between Cloudflare and your server, but does not verify the authenticity of the SSL certificate on your server.
Full SSL (Strict): Encrypts traffic between your browser and Cloudflare, and between Cloudflare and your server, and verifies the authenticity of the SSL certificate on your server.
Please provide the following information:

The SSL option you have selected in your Cloudflare settings.
**When you select Full SSL or Full SSL (Strict), you must deploy a certificate in the XrayR node.**
Any error messages or logs related to the SSL configuration.
With this information, we can better understand your setup and assist you in resolving the issue.

**Comment by greatbody** [comment]
> Hello,
> 
> Thank you for issue. Cloudflare provides several SSL options, and we need detailed configuration information to diagnose and solve your issue effectively.
> 
> Here are the SSL options that Cloudflare offers:
> 
> Flexible SSL: Encrypts traffic between your browser and Cloudflare, but not between Cloudflare and your server. Full SSL: Encrypts traffic between your browser and Cloudflare, and between Cloudflare and your server, but does not verify the authenticity of the SSL certificate on your server. Full SSL (Strict): Encrypts traffic between your browser and Cloudflare, and between Cloudflare and your server, and verifies the authenticity of the SSL certificate on your server. Please provide the following information:
> 
> The SSL option you have selected in your Cloudflare settings. **When you select Full SSL or Full SSL (Strict), you must deploy a certificate in the XrayR node.** Any error messages or logs related to the SSL configuration. With this information, we can better understand your setup and assist you in resolving the issue.

Thanks, I have resolved this issue on my own.
