### ISSUE TITLE
question about XrayR

### ISSUE THREAD

**Issue by CHNfastertech** [XrayR-project/XrayR#676]
My XrayR is not working properly，Here's the error message：

Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: panic: (*logrus.Entry) 0xc0010de620
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: goroutine 1 [running]:
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/sirupsen/logrus.(*Entry).log(0xc00175ccb0, 0x0, {0xc00169c000, 0x3eb2})
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/sirupsen/logrus@v1.9.3/entry.go:260 +0x491
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/sirupsen/logrus.(*Entry).Log(0xc00175ccb0, 0x0, {0xc001a9fa00?, 0x1?, 0x1?})
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x48
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/sirupsen/logrus.(*Entry).Logf(0xc00175ccb0, 0x0, {0x4488769?, 0x16?}, {0xc001a9faf0?, 0x5?, 0xc001ac46c0?})
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/sirupsen/logrus@v1.9.3/entry.go:349 +0x7c
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/sirupsen/logrus.(*Logger).Logf(0x77f1160, 0x0, {0x4488769, 0x16}, {0xc001a9faf0, 0x1, 0x1})
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/sirupsen/logrus@v1.9.3/logger.go:154 +0x7c
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/sirupsen/logrus.(*Logger).Panicf(...)
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/sirupsen/logrus@v1.9.3/logger.go:195
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/sirupsen/logrus.Panicf(...)
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/sirupsen/logrus@v1.9.3/exported.go:219
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc0016f5840)
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/XrayR-project/XrayR/panel/panel.go:211 +0x619
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/XrayR-project/XrayR/cmd.run()
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/XrayR-project/XrayR/cmd/root.go:106 +0x1c5
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/XrayR-project/XrayR/cmd.init.func1(0xc001653600?, {0x445389d?, 0x4?, 0x445378d?})
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/XrayR-project/XrayR/cmd/root.go:27 +0x13
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/spf13/cobra.(*Command).execute(0x780c840, {0xc000072910, 0x2, 0x2})
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/spf13/cobra.(*Command).ExecuteC(0x780c840)
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/spf13/cobra.(*Command).Execute(...)
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/spf13/cobra@v1.8.0/command.go:1039
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: github.com/XrayR-project/XrayR/cmd.Execute(...)
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/XrayR-project/XrayR/cmd/root.go:120
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]: main.main()
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ XrayR[1486]:         github.com/XrayR-project/XrayR/main.go:10 +0x1a
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 02 18:44:44 iZj6c6ymmy8u2cc999mzwuZ systemd[1]: XrayR.service: Failed with result 'exit-code'.

**Comment by theresaarcher** [comment]
Thank you for reaching out and reporting this issue. To better assist you and provide a more accurate solution, could you please provide the following details:

Detailed Steps to Reproduce: Can you describe the exact steps you followed before encountering the issue? This will help us replicate the problem on our end.

Error Messages or Logs: If there are any error messages, logs, or screenshots related to the issue, please share them. They can provide valuable insights into the root cause of the problem.

Expected vs. Actual Behavior: What was the expected outcome, and how does it differ from what actually occurred?

Any Additional Information: If there is anything else you think might be relevant to the issue, please include it.

**Comment by CHNfastertech** [comment]
Thank you very much for your help, I've solved this problem. The troubleshooting ideas are as follows

With the same configuration (config.yml), other centos 7 servers can start XrayR correctly, but this debian 12 server just can't start XrayR correctly. The error log at that time was as follows:(An attachment)
[error log.txt](https://github.com/user-attachments/files/16570081/error.log.txt)

After looking at the error log, we noticed an error like this:

Aug 02 18:36:02 iZj6c6ymmy8u2cc999mzwuZ XrayR[28104]: time="2024-08-02T18:36:02+08:00" level=panic msg="Panel Start failed: request https://www.example.com/api/v1/server/UniProxy/config failed: <!DOCTYPE html><html lang=\"en-US\"><head><title>Just a moment...</title><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"><meta

Aug 02 18:36:02 iZj6c6ymmy8u2cc999mzwuZ XrayR[28104]: <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"></head><body>

So we ran a test API connection test. From the API test results, my request was intercepted by Cloudflare and returned an HTTP 403 error because of Cloudflare's security settings.So we adjusted the Cloudflare settings so that my server API requests were allowed. Subsequently, XrayR is running correctly.

Thank you very much again for your help
