### ISSUE TITLE
Help needed to tunnelling v2ray

### ISSUE THREAD

**Issue by EbadiDev** [XrayR-project/XrayR#69]
Hi, Thanks for your excellent Xray backend framework 
So in IRAN, Internet is f******d and only way to connect is buying Iranian VPS and connect them to outside, and it's connecting only with VLESS/VMESS + WebSocket Transport Protocol 

here terminology:

* Upstream Server: A server that has free access to the Internet.
* Bridge Server: A server that is available to clients and has access to the upstream server.
* Client: A user side application with access to the bridge server.

I have v2board panel and I am failing all time and I can't make right config to work.
Is there any example for such a case ?
here is my config but not working:

Bridge Server conf:
```
"outbounds": [
    {
      "tag": "proxy",
      "protocol": "vmess",
      "settings": {
        "vnext": [
          {
            "address": "<UPSTREAM-IP>",
            "port": 1310,
            "users": [
              {
                "id": "<UPSTREAM-UUID>",
                "alterId": 0,
                "security": "none"
              }
            ]
          }
        ]
      },
      "streamSettings": {
        "network": "ws"
      },
```

**Comment by XemonDev** [comment]
salam
be natije residi?
man moshkelam ine xray client misazam dasti tunnel mishe ama ba v2board nemishe
