### ISSUE TITLE
xrayr版本大于0.9.2时，进行中转节点时clash 无法识别带ws协议的节点

### ISSUE THREAD

**Issue by chibinyong** [XrayR-project/XrayR#691]
目前的用的是sspanel ，xrayr0.9.4
正常情况下搭建vmess+ws+tls，v2ray和clash verge都可以正常识别。
但是用中转机reaml TCP协议进行中转后v2ray可以正常识别，但是clash verge不能够使用，包括手机端。
查看xrayr日志发现似乎clash verge根本就没连接上xrayr，因为没用任何的连接痕迹。
而后尝试使用 vmess+ws也是一样的 v2ray可以正常使用，而clash不行。
尝试更换其他的中转协议iptables 也是一样的效果。
这种现在存在与0.9.3和0.9.4。回滚到0.9.2版本就没问题了。
希望能够解决下这个问题 谢谢

**Comment by chibinyong** [comment]
补充下配置 
ssp：
{
  "offset_port_user": "15226",
  "offset_port_node": "15226",
  "server_sub": "hkone.xxxxxx.xyz",
  "host": "hkone.xxxxxx.xyz",
  "alter_id": "0",
  "network": "ws",
  "security": "tls",
  "ws-opts": {
    "path": "/2215"
  },
  "path": "/2215"
}
xrayr :
  - PanelType: "SSpanel" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel, BunPanel
    ApiConfig:
      ApiHost: "https://xxxxx"
      ApiKey: "123456"
      NodeID: 26
      NodeType: V2ray # Node type: V2ray, Vmess, Vless, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
      DisableCustomConfig: false # disable custom config for sspanel
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      AutoSpeedLimitConfig:
        Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
        WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
        LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
        LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
      GlobalDeviceLimitConfig:
        Enable: false # Enable the global device limit of a user
        RedisNetwork: tcp # Redis protocol, tcp or unix
        RedisAddr: 127.0.0.1:6379 # Redis server address, or unix socket path
        RedisUsername: # Redis username
        RedisPassword: YOUR PASSWORD # Redis password
        RedisDB: 0 # Redis DB
        Timeout: 5 # Timeout for redis request
        Expiry: 60 # Expiry time (second)
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        - SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
      DisableLocalREALITYConfig: false  # disable local reality config
      EnableREALITY: false # Enable REALITY
      REALITYConfigs:
        Show: true # Show REALITY debug
        Dest: www.amazon.com:443 # Required, Same as fallback
        ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for disable
        ServerNames: # Required, list of available serverNames for the client, * wildcard is not supported at the moment.
          - www.amazon.com
        PrivateKey: YOUR_PRIVATE_KEY # Required, execute './XrayR x25519' to generate.
        MinClientVer: # Optional, minimum version of Xray client, format is x.y.z.
        MaxClientVer: # Optional, maximum version of Xray client, format is x.y.z.
        MaxTimeDiff: 0 # Optional, maximum allowed time difference, unit is in milliseconds.
        ShortIds: # Required, list of available shortIds for the client, can be used to differentiate between different clients.
          - ""
          - 0123456789abcdef
      CertConfig:
        CertMode: http # Option about how to get certificate: none, file, http, tls, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "xxxx" # Domain to cert
        CertFile: /etc/XrayR/cert/xxxx# Provided if the CertMode is file
        KeyFile: /etc/XrayR/cert/xxxx
        Provider: cloudflare # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: xxxxx@qq.com
        DNSEnv: # DNS ENV option used by DNS provider
          CLOUDFLARE_EMAIL: xxxxx@qq.com
          CLOUDFLARE_API_KEY: xxxxxx

**Comment by LestreZhao** [comment]
你好 解决了么 我也遇到这个问题

**Comment by chibinyong** [comment]
> 你好 解决了么 我也遇到这个问题

解决了 用0.9.2 =。=

**Comment by LestreZhao** [comment]
用0.9.2有遇到延迟很高或者不通的情况不
