### ISSUE TITLE
连接成功，但是无法科学上网

### ISSUE THREAD

**Issue by asd51731** [XrayR-project/XrayR#693]
我前端用的v2board，后端用的xrayr（两者部署在不同机器上），android用的Clash，看着能连接成功，但是不能科学上网，config.yml日志也配置了debug（没有看到什么debug信息，也么有发现什么报错日志，），但是依然无法看到相关的日志。我只改了config.yml，没有改其他的，希望能指点一下吗 ，谢谢~~
版本用的0.9.4，
日志配置部分：
`Log:  
  Level: debug # Log level: none, error, warning, info, debug  

  AccessPath: /etc/XrayR/access.log  

  ErrorPath: /etc/XrayR/error.log`
配置信息如下（ApiHost和ApiKey都代写了）：
`Nodes:
  - PanelType: "NewV2board" # Panel type: SSpanel, NewV2board, PMpanel, Proxypanel, V2RaySocks, GoV2Panel, BunPanel
    ApiConfig:
      ApiHost: "https://123"
      ApiKey: "123"
      NodeID: 1
      NodeType: Vmess # Node type: V2ray, Vmess, Vless, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      VlessFlow: "xtls-rprx-vision" # Only support vless
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
      DisableCustomConfig: false # disable custom config for sspanel`

CertMode用的none

**Comment by RookieToExpert** [comment]
我也有相同问题，请问你解决了吗
