### ISSUE TITLE
fallback到某个域名怎么设置？

### ISSUE THREAD

**Issue by lowprofileusername** [XrayR-project/XrayR#72]
EnableFallback: true # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Alpn: # Alpn, Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: demo.cloudreve.org:443 # Required, Destination of fallback, check https://xtls.github.io/config/features/fallback.html for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable

比如我这样设置后网页访问显示
ERR_HTTP2_PROTOCOL_ERROR
请问怎么设置？

**Comment by unknwon0054** [comment]
需要 h2c  nginx listen ${port} http2

**Comment by lowprofileusername** [comment]
> 需要 h2c nginx listen ${port} http2

那不是本机了吗？然后nginx再反代外面的网站？我想直接fallback到某一个外部网站不可行是吧。

**Comment by unknwon0054** [comment]
> > 需要 h2c nginx listen ${port} http2
> 
> 那不是本机了吗？然后nginx再反代外面的网站？我想直接fallback到某一个外部网站不可行是吧。

alpn 设置http/1.1 但是 xrayr 配置没有提供这个设置选项

**Comment by thank243** [comment]
Read: https://xrayr-project.github.io/transport.md#tlsobject
