### ISSUE TITLE
关于性能优化与配置文件？

### ISSUE THREAD

**Issue by moranno** [XrayR-project/XrayR#75]
目前在文档中看到 “Nginx+Trojan暂时滴神” 配置案例，请问下，案例中的配置文件 没有开启xtls，
1.如果 trojan 开启 xtls 是否生效，是否对性能提升有帮助？面板/客户端是否也需要做相应配置？
2.如果想启用gRPC，v2b面板下的trojan节点似乎并没有相关配置，是否可以启用？启用gRPC是否对性能提升有帮助？
3.配置中说到如果nginx有一个网站是h2，则巨坑，请问巨坑是什么？

**Comment by RManLuo** [comment]
1. nginx不支持xtls
2. 可以设置，请自行研究
3. 一个站设置为h2会导致全部站点都只支持h2，可能会导致回落失败。

**Comment by moranno** [comment]
> 1. nginx不支持xtls

这里看到一个nginx的配置，似乎可以支持xtls:
https://blog.xmgspace.me/archives/nginx-sni-dispatcher.html

> 让Nginx的stream模块再充当一次和XTLS交流的媒人，再XTLS前面用stream模块做一层转发，将Proxy protocol这层外衣给去掉，传递给XTLS的还是最原始的TCP流。

**Comment by RManLuo** [comment]
> > 1. nginx不支持xtls
> 
> 这里看到一个nginx的配置，似乎可以支持xtls: https://blog.xmgspace.me/archives/nginx-sni-dispatcher.html
> 
> > 让Nginx的stream模块再充当一次和XTLS交流的媒人，再XTLS前面用stream模块做一层转发，将Proxy protocol这层外衣给去掉，传递给XTLS的还是最原始的TCP流。

采用nginx处理tls的原因是为了隐藏go处理tls时产生的特征。采用stream分流仍然会使用xray处理tls，无法达到隐藏特征的效果。
