### ISSUE TITLE
关于iptables中转获取不到真实IP

### ISSUE THREAD

**Issue by olperson** [XrayR-project/XrayR#79]
您好， 使用sspanel面板，ws，后端上报的使用IP始终为前端地址中server字段后的中转IP，测试节点类型为v2ray或v2ray中转，后端配置文件中启用enableproxyproctol后节点连通性不通过

**Comment by olperson** [comment]
> 您好， 使用sspanel面板，ws，后端上报的使用IP始终为前端地址中server字段后的中转IP，测试节点类型为v2ray或v2ray中转，后端配置文件中启用enableproxyproctol后节点连通性不通过

**Comment by NutterChen** [comment]
@olperson https://eqblog.com/iptables-nat-keep-source-ip.html
