### ISSUE TITLE
回落到trojan提示“tls: first record does not look like a TLS handshake”

### ISSUE THREAD

**Issue by oocco** [XrayR-project/XrayR#80]
错误提示：

> `
> 2022/11/05 17:35:25 *************:38824 rejected  proxy/trojan: not trojan protocol
> 
> 2022/11/05 17:35:25 http: TLS handshake error from 127.0.0.1:57726: tls: first record does not look like a TLS handshake
> 
> 2022/11/05 17:35:25 [Info] [3589224691] proxy/trojan: firstLen = 189
> 
> 2022/11/05 17:35:25 [Info] [3589224691] proxy/trojan: fallback starts > proxy/trojan: not trojan protocol
> 
> 2022/11/05 17:35:25 [Info] [3589224691] proxy/trojan: realName = *************
> 
> 2022/11/05 17:35:25 [Info] [3589224691] proxy/trojan: realAlpn = http/1.1
> 
> 2022/11/05 17:35:25 [Info] [3589224691] proxy/trojan: realPath = /****
> 
> 2022/11/05 17:35:25 *************:38852 rejected  proxy/trojan: not trojan protocol
> 
> 2022/11/05 17:35:25 http: TLS handshake error from 127.0.0.1:57742: tls: first record does not look like a TLS handshake
> 
> 2022/11/05 17:35:25 [Info] [2532349702] proxy/trojan: firstLen = 189
> 
> 2022/11/05 17:35:25 [Info] [2532349702] proxy/trojan: fallback starts > proxy/trojan: not trojan protocol
> 
> 2022/11/05 17:35:25 [Info] [2532349702] proxy/trojan: realName = *************
> 
> 2022/11/05 17:35:25 [Info] [2532349702] proxy/trojan: realAlpn = http/1.1
> 
> 2022/11/05 17:35:25 [Info] [2532349702] proxy/trojan: realPath = /****
> 
> 2022/11/05 17:35:25 [Info] [400680815] proxy/trojan: firstLen = 189
> 
> 2022/11/05 17:35:25 [Info] [400680815] proxy/trojan: fallback starts > proxy/trojan: not trojan protocol
> `

尝试过vmess+trojan，vless+trojan，trojan+vless等各种组合，均无法正常回落到8443端口，
回落到80 http可以正常访问。

xrayr配置：

> PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
>       ApiConfig:
>         ApiHost: "****"
>         ApiKey: "****"
>         NodeID: 80
>         NodeType: Trojan # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
>         Timeout: 30 # Timeout for the api request
>         EnableVless: false # Enable Vless for V2ray Type
>         EnableXTLS: true # Enable XTLS for V2ray and Trojan
>         SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
>         DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
>         RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
>       ControllerConfig:
>         ListenIP: 0.0.0.0 # IP address you want to listen
>         SendIP: 0.0.0.0 # IP address you want to send pacakage
>         UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
>         EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
>         DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
>         EnableProxyProtocol: false # Only works for WebSocket and TCP
>         EnableFallback: true # Only support for Trojan and Vless
>         AutoSpeedLimitConfig:
>           Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
>           WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
>           LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
>           LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
>         FallBackConfigs:  # Support multiple fallbacks
>           -
>             Dest: "enp2.owall.icu:80" # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
>             ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
>           -
>             SNI: # TLS SNI(Server Name Indication), Empty for any
>             Alpn: # Alpn, Empty for any
>             Path: "/wsl" # HTTP PATH, Empty for any
>             Dest: 8443 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
>             ProxyProtocolVer: 1 # Send PROXY protocol version, 0 for dsable
>         CertConfig:
>         . . .
> 
>     - #Trojan
>       PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
>       ApiConfig:
>         ApiHost: "****"
>         ApiKey: "****"
>         NodeID: 81
>         NodeType: Trojan # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
>         Timeout: 30 # Timeout for the api request
>         EnableVless: false # Enable Vless for V2ray Type
>         EnableXTLS: false # Enable XTLS for V2ray and Trojan
>         SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
>         DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
>         RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
>       ControllerConfig:
>         ListenIP: 0.0.0.0 # IP address you want to listen
>         SendIP: 0.0.0.0 # IP address you want to send pacakage
>         UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
>         EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
>         DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
>         EnableProxyProtocol: false # Only works for WebSocket and TCP
>         EnableFallback: true # Only support for Trojan and Vless
>         AutoSpeedLimitConfig:
>           Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
>           WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
>           LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
>           LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
>         FallBackConfigs:  # Support multiple fallbacks
>           -
>             Dest: "80" # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
>             ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
>   
>         CertConfig:
>         . . .

sspanel 配置：
443端口
`
{
  "offset_port_node": "443",
  "server_sub": "****",
  "host": "****",
  "enable_xtls": "1",
  "decryption": "none"
}
`
8443端口
`
{
  "offset_port_node": "8443",
  "server_sub": "****",
  "host": "****",
  "network": "ws",
  "path": "/****",
  "tcpSettings": {
    "acceptProxyProtocol": "true"
  }
}
`

**Comment by thank243** [comment]
Firstly, use https://yourserveraddress:port on browser to test fallback.

**Comment by oocco** [comment]
> Firstly, use https://yourserveraddress:port on browser to test fallback.

 use https://***:443 on browser -> fallback to  127.0.0.1:80

xrayr log:
`2022/11/06 16:38:50 [Info] [2364832679] proxy/trojan: firstLen = 76
2022/11/06 16:38:50 [Info] [2364832679] proxy/trojan: fallback starts > proxy/trojan: not trojan protocol
2022/11/06 16:38:50 [Info] [2364832679] proxy/trojan: realName = ***.**
2022/11/06 16:38:50 [Info] [2364832679] proxy/trojan: realAlpn = h2
2022/11/06 16:38:50 222.109.142.54:35482 rejected  proxy/trojan: not trojan protocol`



use  https://***:8443 on browser -> HTTP ERROR 404
xrayr log:
`2022/11/06 16:46:48 [Info] [1801544402] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > read tcp <serverip>:443->***:53802: i/o timeout`

**Comment by thank243** [comment]
You can only fallback to https with https, not fallback to http.

**Comment by oocco** [comment]
> You can only fallback to https with https, not fallback to http.
yes, I know it now
but
I want to use 443 port connect vless and trojan ws  at the same time.
like https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json

when 443 port  fallback to 8443 port, it's disuccess.  output “tls: first record does not look like a TLS handshake”

**Comment by thank243** [comment]
try out `"acceptProxyProtocol": "false"`

**Comment by oocco** [comment]
how to set "acceptProxyProtocol": "false", in sspanel config?
now my configure

xrayr:

> Log:
>     Level: debug # Log level: none, error, warning, info, debug 
>     AccessPath: # /etc/XrayR/access.Log
>     ErrorPath: # /etc/XrayR/error.log
>   DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/dns.html for help
>   RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/routing.html for help
>   InboundConfigPath: # /etc/XrayR/custom_inbound.json # Path to custom inbound config, check https://xtls.github.io/config/inbound.html for help
>   OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/outbound.html for help
>   ConnetionConfig:
>     Handshake: 4 # Handshake time limit, Second
>     ConnIdle: 30 # Connection idle time limit, Second
>     UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
>     DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
>     BufferSize: 64 # The internal cache size of each connection, kB 
>   Nodes:
>     - #xtls
>       PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
>       ApiConfig:
>         ApiHost: "***"
>         ApiKey: "***"
>         NodeID: 1
>         NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
>         Timeout: 30 # Timeout for the api request
>         EnableVless: true # Enable Vless for V2ray Type
>         EnableXTLS: true # Enable XTLS for V2ray and Trojan
>         SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
>         DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
>         RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
>       ControllerConfig:
>         ListenIP: 0.0.0.0 # IP address you want to listen
>         SendIP: 0.0.0.0 # IP address you want to send pacakage
>         UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
>         EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
>         DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
>         EnableProxyProtocol: false # Only works for WebSocket and TCP
>         EnableFallback: true # Only support for Trojan and Vless
>         AutoSpeedLimitConfig:
>           Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
>           WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
>           LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
>           LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
>         FallBackConfigs:  # Support multiple fallbacks
>           -
>             Dest: "8443" # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
>             ProxyProtocolVer: 1 # Send PROXY protocol version, 0 for dsable
>         CertConfig:
>             <***>
>   
>     - #Trojan
>       PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, Proxypanel, V2RaySocks
>       ApiConfig:
>         ApiHost: "***"
>         ApiKey: "***"
>         NodeID: 2
>         NodeType: Trojan # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
>         Timeout: 30 # Timeout for the api request
>         EnableVless: false # Enable Vless for V2ray Type
>         EnableXTLS: false # Enable XTLS for V2ray and Trojan
>         SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
>         DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
>         RuleListPath: # /etc/XrayR/rulelist Path to local rulelist file
>       ControllerConfig:
>         ListenIP: 0.0.0.0 # IP address you want to listen
>         SendIP: 0.0.0.0 # IP address you want to send pacakage
>         UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
>         EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
>         DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
>         EnableProxyProtocol: false # Only works for WebSocket and TCP
>         EnableFallback: true # Only support for Trojan and Vless
>         AutoSpeedLimitConfig:
>           Limit: 0 # Warned speed. Set to 0 to disable AutoSpeedLimit (mbps)
>           WarnTimes: 0 # After (WarnTimes) consecutive warnings, the user will be limited. Set to 0 to punish overspeed user immediately.
>           LimitSpeed: 0 # The speedlimit of a limited user (unit: mbps)
>           LimitDuration: 0 # How many minutes will the limiting last (unit: minute)
>         FallBackConfigs:  # Support multiple fallbacks
>           -
>             SNI: # TLS SNI(Server Name Indication), Empty for any
>             Alpn: # Alpn, Empty for any
>             Dest: "80" # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
>             ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
>   
>         CertConfig:
>            <***>

sspanel:

> {
>   "offset_port_node": "443",
>   "server_sub": "***",
>   "host": "***",
>   "alter_id": "0",
>   "network": "tcp",
>   "security": "xtls",
>   "enable_vless": "1",
>   "decryption": "none",
>   "accept_proxy_protocol": "false",
>   "tcpSettings": {
>     "acceptProxyProtocol": "false"
>   }
> }

> {
>   "offset_port_node": "8443",
>   "server_sub": "***",
>   "host": "***",
>   "acceptProxyProtocol": "false",
>   "accept_proxy_protocol": "false",
>   "tcpSettings": {
>     "acceptProxyProtocol": "false"
>   }
> }

use https://***:443 on browser -> fallback to 8443
ERR_CONNECTION_CLOSED

xrayr log:

> 2022/11/07 08:45:00 [Info] [2669992690] proxy/vless/inbound: firstLen = 76
> 2022/11/07 08:45:00 [Info] [2669992690] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
> 2022/11/07 08:45:00 [Info] [2669992690] proxy/vless/inbound: realName = ***
> 2022/11/07 08:45:00 [Info] [2669992690] proxy/vless/inbound: realAlpn = h2
> 2022/11/07 08:45:00 [Info] [2386201168] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > tls: first record does not look like a TLS handshake
> 2022/11/07 08:45:00 [Info] [2669992690] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to deliver response payload > read tcp 127.0.0.1:40262->127.0.0.1:8443: read: connection reset by peer

use https://***:8443 on browser -> fallback to 80 (nginx)
it's ok

xray log

> 2022/11/07 08:46:12 [Info] [49330190] proxy/trojan: firstLen = 76
> 2022/11/07 08:46:12 [Info] [49330190] proxy/trojan: fallback starts > proxy/trojan: not trojan protocol
> 2022/11/07 08:46:12 [Info] [49330190] proxy/trojan: realName = ***
> 2022/11/07 08:46:12 [Info] [49330190] proxy/trojan: realAlpn = h2
> 2022/11/07 08:46:12 59.6.66.102:39590 rejected  proxy/trojan: not trojan protocol
> 2022/11/07 08:46:12 [Info] [49330190] app/proxyman/inbound: connection ends > proxy/trojan: fallback ends > proxy/trojan: failed to fallback request payload > read tcp <serverip>:8443-><clientip>:39590: use of closed network connection

use 443 on xray client (vless) -> vless server
it's ok

use 443 on xray client (trojan) -> 8443 trojan server
can't connect

xrayr log 

> 2022/11/07 08:51:03 [Info] [34867211] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > context canceled
> 2022/11/07 08:51:04 [Info] [3666057976] proxy/vless/inbound: firstLen = 596
> 2022/11/07 08:51:04 [Info] [3666057976] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
> 2022/11/07 08:51:04 [Info] [3666057976] proxy/vless/inbound: realName = ***
> 2022/11/07 08:51:04 [Info] [3666057976] proxy/vless/inbound: realAlpn = http/1.1
> 2022/11/07 08:51:04 [Info] [2260709468] app/proxyman/inbound: connection ends > proxy/trojan: failed to read first request > tls: first record does not look like a TLS handshake
> 2022/11/07 08:51:04 [Info] [3666057976] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to deliver response payload > read tcp 127.0.0.1:37576->127.0.0.1:8443: read: connection reset by peer
