### ISSUE TITLE
路由Routing的Rules里面的attrs属性无法工作

### ISSUE THREAD

**Issue by bunnyzi** [XrayR-project/XrayR#81]
如题，在尝试使用attrs规则的时候，发现attrs后面的规则不生效
例如下面的规则Rule:
{
  "type": "field",
  "domain": ["sample.com"],
  "attrs": "attrs[':method'] == 'GET'",
  "outboundTag": "block",
}

假如说要禁止sample.com这个域名下的GET请求，按理说应该如上书写routing规则，
不过反复尝试，发现attrs这个规则始终无法工作

也尝试过其他的attrs规则，也是无法匹配上，如例子里面的：
检测 HTTP Path："attrs[':path'].startswith('/test')"
检测 Content Type："attrs['accept'].index('text/html') >= 0"
这些也尝试过，都匹配不上

请问这个是Bug还是说这个规则有特殊的写法？

参考：https://xtls.github.io/config/routing.html#ruleobject 里面的attrs

**Comment by thank243** [comment]
inbound是什么协议

**Comment by RManLuo** [comment]
是否仍然存在此问题？

**Comment by RManLuo** [comment]
只有http入站支持此属性

attrs: string

一段脚本，用于检测流量的属性值。当此脚本返回真值时，此规则生效。

脚本语言为 Starlark，它的语法是 Python 的子集。脚本接受一个全局变量 attrs，其中包含了流量相关的属性。

**目前只有 http 入站代理会设置这一属性。**

示例：

检测 HTTP GET："attrs[':method'] == 'GET'"
检测 HTTP Path："attrs[':path'].startswith('/test')"
检测 Content Type："attrs['accept'].index('text/html') >= 0"

**Comment by bunnyzi** [comment]
谢谢大佬们迅速热情而又一针见血的回复

是我自己反复看文档 都没有看到HTTP入站才有这个说明，是我自己的问题

再次感激！
