### ISSUE TITLE
xrayr x509 certificate signed by unknown authority

### ISSUE THREAD

**Issue by damengmeng** [XrayR-project/XrayR#81]
节点启动时，报这个错误。找了一些办法，没有成功。是什么问题呢，大家有遇到么，怎么解决的。谢谢。

**Comment by leung4158** [comment]
我遇到了，我是lets encrpt的证书报错。然后换成http就行了，这是个暂时的不是很好的解决办法

**Comment by miladrajabi2002** [comment]
I have the same problem and it cannot be fixed in any way

x509: certificate signed by unknown authority

**Comment by thank243** [comment]
Update to the latest version. And try again.
