### ISSUE TITLE
LIMITER限制, 逻辑存在问题

### ISSUE THREAD

**Issue by himanhimao** [XrayR-project/XrayR#82]
![image](https://user-images.githubusercontent.com/1930666/145966789-6d14967a-a074-4e33-bbb7-a9e31b829267.png)

If this ip is a new device ，this will only return false
已知：
1. 这里是一个嵌套的MAP,  {email : {ip: uid}},
2. email为用户邮箱 ，ip 为用户IP ，uid为用户ID(  其中email.和用户ID为常量)，只有IP是变量

这里逻辑似乎有问题 
1._, ok :=  ipMap.LoadOrStore(ip, uid) , ok的值永远等于false 
2. ipMap的range结果 counter永远是1 
3. uid 如果等于用户ID ,这个好像判断不出设备ID, 只能做IP限制，但是IP限制应该再第一层去range  {email:ip} 统计IP的数量
4. email作用等同于uid. 都是用户唯一标识

**Comment by RManLuo** [comment]
_, ok := ipMap.LoadOrStore(ip, uid) 在当前ip已经被记录时，ok值为true。由于协议原因，本身就是只能限制ip。具体内容请查看文档。

**Comment by himanhimao** [comment]
> _, ok := ipMap.LoadOrStore(ip, uid) 在当前ip已经被记录时，ok值为true。由于协议原因，只能限制ip。具体内容请查看文档。

是啊，如果是IP限制这个MAP 应该是{email: []ip},不应该是嵌套map. 计算counter那里的逻辑是不是存在问题呢，因为uid是常量 , counter的值 只可能是1

**Comment by RManLuo** [comment]
此处代码为历史遗留问题，一开始email字段是没有记录用户uid，所以需要嵌套ip：uid的字典，当email和uid唯一对应时等价于email: ip[]。counter处统计的是ipmap中独立ip数量，并非uid数量。
