### ISSUE TITLE
DeviceLimt and SpeedLimit not working on ProxyPanel?

### ISSUE THREAD

**Issue by long2k3pro** [XrayR-project/XrayR#83]
I have set device limit to 1 and speed limit to 10 Mbps on panel but 2 devices still can connect to the same node at the same time with the same uuid and speed is higher 10Mbps (30-40Mbps). I tried editing speedlimit and devicelimit in XrayR config file but only speedlimit worked

**Comment by RManLuo** [comment]
Please check if the two devices have distinct IP addresses?

**Comment by long2k3pro** [comment]
Two devices have different IPs
