### ISSUE TITLE
本地审计自动屏蔽facebook

### ISSUE THREAD

**Issue by wdm1732418365** [XrayR-project/XrayR#84]
描述：config.yml中只要设置了RuleListPath就会无法访问facebook，即使本地的rulelist文件没有任何审计规则也是如此。xrayr log中即显示Report 1 illegal behaviors，为触发审计规则。且所有vps皆有此问题。

环境：前端v2b稳定版。后端xrayr最新版，均使用一键脚本安装的，全默认位置。RuleListPath为/etc/XrayR/rulelist。
问题：当设置为RuleListPath: /etc/XrayR/rulelist时就会屏蔽facebook（rulelist文件中不管填不填规则都会如此），但是当注释掉（即不设置本地审计文件的时候），RuleListPath: #/etc/XrayR/rulelist，则会正常显示facebook.com页面。
如果需要可以进一步提供别的log文件

**Comment by thank243** [comment]
来个debug日志，最好把v2b下发的配置一起贴出来。

**Comment by wdm1732418365** [comment]
部分error.log： https://raw.githubusercontent.com/wdm1732418365/rulelist/main/error.log
部分access.log： https://raw.githubusercontent.com/wdm1732418365/rulelist/main/access.log
rulelist文件： https://raw.githubusercontent.com/wdm1732418365/rulelist/main/rulelist

**Comment by wdm1732418365** [comment]
问题已解决。。。原因是v2b的服务端中的V2ray全局域名过滤器未删除干净。将其删除即可解决该问题

**Comment by thank243** [comment]
你去检查下v2b呢。或者自定义个outbound freedom然后route到这个tag。
