### ISSUE TITLE
xrayr 是否支持Unix domain socket

### ISSUE THREAD

**Issue by OPPO9008** [XrayR-project/XrayR#88]
xtls是支持Unix domain socket的
但我看到
    ControllerConfig:
        ListenIP: 0.0.0.0 # IP address you want to listen
是监听ip的

**Comment by RManLuo** [comment]
> 监听地址，IP 地址或 Unix domain socket，默认值为 "0.0.0.0"，表示接收所有网卡上的连接.
可以指定一个系统可用的 IP 地址。
支持填写 Unix domain socket，格式为绝对路径，形如 "/dev/shm/domain.socket"，可在开头加 @ 代表 abstract，@@ 则代表带 padding 的 abstract。
填写 Unix domain socket 时，port 和 allocate 将被忽略，协议目前可选 VLESS、VMess、Trojan，传输方式可选 TCP、WebSocket、HTTP/2、gRPC。

理论上可行，可以尝试一下。

**Comment by RManLuo** [comment]
经过测试，listenIP和fallback均可以使用Domain Socket。
