### ISSUE TITLE
sspanel未配置自定义custom_config时出现配置拉取错误

### ISSUE THREAD

**Issue by RainThings** [XrayR-project/XrayR#89]
日志报告无法识别拉取的配置，
以下是日志片段（已脱敏）
upports many panels)
Dec 25 13:03:33 hostname XrayR[73972]: 2021/12/25 13:03:33 Start the panel..
Dec 25 13:03:33 hostname XrayR[73972]: 2021/12/25 13:03:33 Xray Core Version: 1.5.1
Dec 25 13:03:34 hostname XrayR[73972]: 2021/12/25 13:03:34 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#ip地址#;10009;0;ws;tls;path=/1|server=#域名#|host=#域名#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Dec 25 13:03:34 hostname XrayR[73972]: Error: strconv.Atoi: parsing "": invalid syntax
Dec 25 13:03:34 hostname XrayR[73972]: panic: Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP地址#;10009;0;ws;tls;path=/1|server=#域名#|host=#域名#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Dec 25 13:03:34 hostname XrayR[73972]: Error: strconv.Atoi: parsing "": invalid syntax
Dec 25 13:03:34 hostname XrayR[73972]: goroutine 1 [running]:
Dec 25 13:03:34 hostname XrayR[73972]: log.Panicf({0x203d52f, 0xc0005f6380}, {0xc00085dea0, 0xc0005bc620, 0xc00063fe88})
Dec 25 13:03:34 hostname XrayR[73972]:         log/log.go:361 +0x67
Dec 25 13:03:34 hostname XrayR[73972]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000517040)
Dec 25 13:03:34 hostname XrayR[73972]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Dec 25 13:03:34 hostname XrayR[73972]: main.main()
Dec 25 13:03:34  XrayR[73972]:
该问题自0.7.3开始出现，回滚至0.7.2后恢复正常

**Comment by crackair** [comment]
@RainThings 支持了sspanel最新的结点custom_config功能，此设置会在sspanel >= 2021.11的版本中自动启用。请参考文档，正确填写结点配置：https://wiki.sspanel.org/#/setup-custom-config。

**Comment by RainThings** [comment]
> @RainThings 支持了sspanel最新的结点custom_config功能，此设置会在sspanel >= 2021.11的版本中自动启用。请参考文档，正确填写结点配置：[https://wiki.sspanel.org/#/setup-custom-config。](https://wiki.sspanel.org/#/setup-custom-config%E3%80%82)

此页面已不存在，且未配置custom_config！

**Comment by crackair** [comment]
@RainThings ....最后那个句号看不见？

**Comment by thank243** [comment]
这个页面需要国外IP才能打开。

**Comment by RSSYLY** [comment]
我在 xrayr 配置中将 ApiConfig中的 DisableCustomConfig 设为 true ，但仍提示以上的报错。

**Comment by crackair** [comment]
@RSSYLY 支持此设置的版本暂未release

**Comment by RainThings** [comment]
新版本仍然报错，配置上已经禁用掉了，还是跟原来一样，我板子上是空的没有设置的
