### ISSUE TITLE
use 443 trojan and website as same time

### ISSUE THREAD

**Issue by miladrajabi2002** [XrayR-project/XrayR#91]
hi 
i wnat use 443 port for v2board and trojan but i can not find way to solve it can you explain me how to revers proxy in nginx to handle trojan with 443 and v2board with 443

**Comment by thank243** [comment]
its dangerous.

**Comment by unknowedNp** [comment]
> its dangerous.

reverse proxy is dangerous or use same port of it ?

**Comment by thank243** [comment]
No three hundred taels of silver buried here.

**Comment by miladrajabi2002** [comment]
i do it with nginx
