### ISSUE TITLE
大佬能不能支持一下日志切割？

### ISSUE THREAD

**Issue by silentdspeedup** [XrayR-project/XrayR#92]
就好比docker 使用 --log-opt max-size 和 --log-opt max-file 来控制单个日志大小和日志数量一样，限制AccessPath和ErrorPath的日志大小？

**Comment by thank243** [comment]
journal 不会自动切割吗？

**Comment by silentdspeedup** [comment]
没有自动切割，最起码1G的日志没有切割。我写了个logrotate的配置文件正在测试，没问题我会放出来

**Comment by thank243** [comment]
journal默认是按当前磁盘的10%切割。

**Comment by silentdspeedup** [comment]
在/etc/logrotate.d下新建一个文件，写入
`/etc/XrayR/access.log
/etc/XrayR/error.log
{
	compress
	copytruncate
	create
	dateext
	notifempty
	noolddir
	missingok
	rotate 5
}`

每天3:50切割并压缩日志，保存5份
