### ISSUE TITLE
使用redis全局限制设备后节点延迟飙升？

### ISSUE THREAD

**Issue by KunG0100** [XrayR-project/XrayR#93]
测试机器是Azure的hk
redis服务器在us

两台同样的机器 
一台开启全局设备限制  延迟300+
一台关闭全局设备限制  延迟30+

请问大佬有办法优化吗？

**Comment by thank243** [comment]
Use a slave redis on hk

**Comment by KunG0100** [comment]
感谢回复
但是反过来 
如果us的节点使用hk的redis服务器
延迟同样会很高

**Comment by KunG0100** [comment]
> Use a slave redis on hk

感谢回复
但是反过来
如果us的节点使用hk的redis服务器
延迟同样会很高

**Comment by thank243** [comment]
> > Use a slave redis on hk
> 
> 感谢回复
> 但是反过来
> 如果us的节点使用hk的redis服务器
> 延迟同样会很高

lol, are u kidding me？

**Comment by unknwon0054** [comment]
为什么上报 用户IP到redis要影响到 节点延迟
