### ISSUE TITLE
VMess MD5 认证信息 淘汰机制 不知道如何解决~

### ISSUE THREAD

**Issue by kailin98** [XrayR-project/XrayR#93]
以下是服务器debug模式下的日志：
2022/01/01 10:05:44 117.177.110.37:6288 rejected common/drain: common/drain: unable to drain connection > websocket: close 1000 (normal) > proxy/vmess/encoding: invalid user: VMessAEAD is enforced and a non VMessAEAD connection is received. You can still disable this security feature with environment variable v2ray.vmess.aead.forced = false . You will not be able to enable legacy header workaround in the future.
相似问题请见[这里](https://github.com/Jrohy/multi-v2ray/issues/561)

**Comment by thank243** [comment]
1.编辑XrayR.service
vi /etc/systemd/system/XrayR.service

[Service]里添加一行：
Environment="XRAY_VMESS_AEAD_FORCED=false"

2.更新systemd服务
systemctl daemon-reload

3.重启XrayR
systemctl restart XrayR

**Comment by kailin98** [comment]
按照此方法成功解决，感谢
