### ISSUE TITLE
limit user not work in v2board

### ISSUE THREAD

**Issue by miladrajabi2002** [XrayR-project/XrayR#94]
in v2board just can set limit device in config.yml and can not set in v2board panel

**Comment by thank243** [comment]
go to v2board for help.

**Comment by miladrajabi2002** [comment]
can i set limit device in v2board panel?
i set in v2board but not apply

**Comment by thank243** [comment]
v2board have this feature? Upload a screen print.

**Comment by miladrajabi2002** [comment]
![image](https://user-images.githubusercontent.com/51949453/201550371-9d65440c-867e-4145-9b4c-08df871230c1.png)
Add subscription

**Comment by thank243** [comment]
v2b haven't this feat. Or you can provode the api for me？
