### ISSUE TITLE
开启支持TLS XrayR报错

### ISSUE THREAD

**Issue by Teeis** [XrayR-project/XrayR#95]
2022/01/07 23:32:27 Xray Core Version: 1.5.1
2022/01/07 23:32:28 infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /etc/XrayR/证书名字.crt: no such file or directory
panic: infra/conf: Failed to build TLS config. > infra/conf: failed to parse certificate > open /etc/XrayR/证书名字.crt: no such file or directory
acme.sh 手动申请 模式为：file | 路径为：/etc/XrayR | 运行方式为docker ：
docker pull crackair/xrayr:latest && docker run --restart=always --name xrayr -d -v /etc/XrayR/config.yml:/etc/XrayR/config.yml --network=host crackair/xrayr:latest

**Comment by crackair** [comment]
Learn how to use docker before asking the question.

**Comment by Teeis** [comment]
thinks.
