### ISSUE TITLE
custom_config问题

### ISSUE THREAD

**Issue by RainThings** [XrayR-project/XrayR#96]
新版本仍然报错，配置上已经禁用掉了，还是跟原来一样，我板子上是空的没有设置的
这是最新版本0.7.5上发生的，但日志输出完全一致。
希望这些信息可以帮助排查原因。

_Originally posted by @RainThings in https://github.com/XrayR-project/XrayR/issues/89#issuecomment-1007569435_

**Comment by RainThings** [comment]
![IMG_20220108_010636_1](https://user-images.githubusercontent.com/61218971/148580142-211eac7c-e982-4c9a-802a-148215b0cf40.jpg)
![Screenshot_2022-01-08-01-05-36-006_com android chrome](https://user-images.githubusercontent.com/61218971/148580156-4ee9b5a2-44eb-44a1-ba99-b1f0348b3f9a.jpg)
![IMG_20220108_010402_1](https://user-images.githubusercontent.com/61218971/148580161-43d2a16b-188b-4b66-b3b8-77a976e775c9.jpg)

**Comment by RainThings** [comment]
Log:
  Level: none # Log level: none, error, warning, info, debug 
  AccessPath: # /etc/XrayR/access.Log
  ErrorPath: # /etc/XrayR/error.log
DnsConfigPath: # /etc/XrayR/dns.json # Path to dns config, check https://xtls.github.io/config/base/dns/ for help
RouteConfigPath: # /etc/XrayR/route.json # Path to route config, check https://xtls.github.io/config/base/route/ for help
OutboundConfigPath: # /etc/XrayR/custom_outbound.json # Path to custom outbound config, check https://xtls.github.io/config/base/outbound/ for help
ConnetionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB 
Nodes:
  -
    PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, , Proxypanel
    ApiConfig:
      ApiHost: ""
      ApiKey: ""
      NodeID: 10
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # ./rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
      DisableCustomConfig: true
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb
  -
    PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, , Proxypanel
    ApiConfig:
      ApiHost: ""
      ApiKey: ""
      NodeID: 13
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # ./rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb
  -
    PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, , Proxypanel
    ApiConfig:
      ApiHost: ""
      ApiKey: ""
      NodeID: 15
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # ./rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bb
  -
    PanelType: "SSpanel" # Panel type: SSpanel, V2board, PMpanel, , Proxypanel
    ApiConfig:
      ApiHost: ""
      ApiKey: ""
      NodeID: 16
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30 # Timeout for the api request
      EnableVless: true # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # ./rulelist Path to local rulelist file
    ControllerConfig:
      ListenIP: 0.0.0.0 # IP address you want to listen
      SendIP: 0.0.0.0 # IP address you want to send pacakage
      UpdatePeriodic: 60 # Time to update the nodeinfo, how many sec.
      EnableDNS: false # Use custom DNS config, Please ensure that you set the dns.json well
      DNSType: AsIs # AsIs, UseIP, UseIPv4, UseIPv6, DNS strategy
      EnableProxyProtocol: false # Only works for WebSocket and TCP
      EnableFallback: false # Only support for Trojan and Vless
      FallBackConfigs:  # Support multiple fallbacks
        -
          SNI: # TLS SNI(Server Name Indication), Empty for any
          Path: # HTTP PATH, Empty for any
          Dest: 80 # Required, Destination of fallback, check https://xtls.github.io/config/fallback/ for details.
          ProxyProtocolVer: 0 # Send PROXY protocol version, 0 for dsable
      CertConfig:
        CertMode: none # Option about how to get certificate: none, file, http, dns. Choose "none" will forcedly disable the tls config.
        CertDomain: "node1.test.com" # Domain to cert
        CertFile: ./cert/node1.test.com.cert # Provided if the CertMode is file
        KeyFile: ./cert/node1.test.com.key
        Provider: alidns # DNS cert provider, Get the full support list here: https://go-acme.github.io/lego/dns/
        Email: test@me.com
        DNSEnv: # DNS ENV option used by DNS provider
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bb
已删去敏感信息，并非填写错误。

**Comment by RainThings** [comment]
日志导出 通过ssh客户端 已脱敏处理


Last login: Fri Jan  7 11:35:48 2022 from 
[ggcuser@#hostname#~]$ sudo -i
[root@#hostname#~]# xrayr

  XrayR 后端管理脚本，不适用于docker
--- https://github.com/XrayR-project/XrayR ---
  0. 修改配置
————————————————
  1. 安装 XrayR
  2. 更新 XrayR
  3. 卸载 XrayR
————————————————
  4. 启动 XrayR
  5. 停止 XrayR
  6. 重启 XrayR
  7. 查看 XrayR 状态
  8. 查看 XrayR 日志
————————————————
  9. 设置 XrayR 开机自启
 10. 取消 XrayR 开机自启
————————————————
 11. 一键安装 bbr (最新内核)
 12. 查看 XrayR 版本
 13. 升级维护脚本

XrayR状态: 未运行
是否开机自启: 是

请输入选择 [0-13]: 8
-- Logs begin at Thu 2021-12-30 11:15:24 EST. --
Jan 07 12:09:01 #hostname#XrayR[1026044]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:01 #hostname#XrayR[1026044]: goroutine 1 [running]:
Jan 07 12:09:01 #hostname#XrayR[1026044]: log.Panicf({0x203e517, 0xc0005c98f0}, {0xc00085dea0, 0xc0005c8850, 0xc00063fe88})
Jan 07 12:09:01 #hostname#XrayR[1026044]:         log/log.go:361 +0x67
Jan 07 12:09:01 #hostname#XrayR[1026044]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000519200)
Jan 07 12:09:01 #hostname#XrayR[1026044]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Jan 07 12:09:01 #hostname#XrayR[1026044]: main.main()
Jan 07 12:09:01 #hostname#XrayR[1026044]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jan 07 12:09:01 #hostname#systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 07 12:09:01 #hostname#systemd[1]: XrayR.service: Failed with result 'exit-code'.
Jan 07 12:09:11 #hostname#systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Jan 07 12:09:11 #hostname#systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 217.
Jan 07 12:09:11 #hostname#systemd[1]: Stopped XrayR Service.
Jan 07 12:09:11 #hostname#systemd[1]: Started XrayR Service.
Jan 07 12:09:11 #hostname#XrayR[1026060]: XrayR 0.7.5 (A Xray backend that supports many panels)
Jan 07 12:09:11 #hostname#XrayR[1026060]: 2022/01/07 12:09:11 Start the panel..
Jan 07 12:09:11 #hostname#XrayR[1026060]: 2022/01/07 12:09:11 Xray Core Version: 1.5.1
Jan 07 12:09:12 #hostname#XrayR[1026060]: 2022/01/07 12:09:12 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:12 #hostname#XrayR[1026060]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:12 #hostname#XrayR[1026060]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:12 #hostname#XrayR[1026060]: panic: Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:12 #hostname#XrayR[1026060]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:12 #hostname#XrayR[1026060]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:12 #hostname#XrayR[1026060]: goroutine 1 [running]:
Jan 07 12:09:12 #hostname#XrayR[1026060]: log.Panicf({0x203e517, 0xc0005c9880}, {0xc00085dea0, 0xc0005c88c0, 0xc00063fe88})
Jan 07 12:09:12 #hostname#XrayR[1026060]:         log/log.go:361 +0x67
Jan 07 12:09:12 #hostname#XrayR[1026060]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000517200)
Jan 07 12:09:12 #hostname#XrayR[1026060]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Jan 07 12:09:12 #hostname#XrayR[1026060]: main.main()
Jan 07 12:09:12 #hostname#XrayR[1026060]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jan 07 12:09:12 #hostname#systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 07 12:09:12 #hostname#systemd[1]: XrayR.service: Failed with result 'exit-code'.
Jan 07 12:09:22 #hostname#systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Jan 07 12:09:22 #hostname#systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 218.
Jan 07 12:09:22 #hostname#systemd[1]: Stopped XrayR Service.
Jan 07 12:09:22 #hostname#systemd[1]: Started XrayR Service.
Jan 07 12:09:22 #hostname#XrayR[1026076]: XrayR 0.7.5 (A Xray backend that supports many panels)
Jan 07 12:09:22 #hostname#XrayR[1026076]: 2022/01/07 12:09:22 Start the panel..
Jan 07 12:09:22 #hostname#XrayR[1026076]: 2022/01/07 12:09:22 Xray Core Version: 1.5.1
Jan 07 12:09:23 #hostname#XrayR[1026076]: 2022/01/07 12:09:23 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:23 #hostname#XrayR[1026076]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:23 #hostname#XrayR[1026076]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:23 #hostname#XrayR[1026076]: panic: Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:23 #hostname#XrayR[1026076]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:23 #hostname#XrayR[1026076]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:23 #hostname#XrayR[1026076]: goroutine 1 [running]:
Jan 07 12:09:23 #hostname#XrayR[1026076]: log.Panicf({0x203e517, 0xc0005c97a0}, {0xc00085dea0, 0xc0005c87e0, 0xc00063fe88})
Jan 07 12:09:23 #hostname#XrayR[1026076]:         log/log.go:361 +0x67
Jan 07 12:09:23 #hostname#XrayR[1026076]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000519200)
Jan 07 12:09:23 #hostname#XrayR[1026076]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Jan 07 12:09:23 #hostname#XrayR[1026076]: main.main()
Jan 07 12:09:23 #hostname#XrayR[1026076]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jan 07 12:09:23 #hostname#systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 07 12:09:23 #hostname#systemd[1]: XrayR.service: Failed with result 'exit-code'.
Jan 07 12:09:33 #hostname#systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Jan 07 12:09:33 #hostname#systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 219.
Jan 07 12:09:33 #hostname#systemd[1]: Stopped XrayR Service.
Jan 07 12:09:33 #hostname#systemd[1]: Started XrayR Service.
Jan 07 12:09:33 #hostname#XrayR[1026091]: XrayR 0.7.5 (A Xray backend that supports many panels)
Jan 07 12:09:33 #hostname#XrayR[1026091]: 2022/01/07 12:09:33 Start the panel..
Jan 07 12:09:33 #hostname#XrayR[1026091]: 2022/01/07 12:09:33 Xray Core Version: 1.5.1
Jan 07 12:09:33 #hostname#XrayR[1026091]: 2022/01/07 12:09:33 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:33 #hostname#XrayR[1026091]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:33 #hostname#XrayR[1026091]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:33 #hostname#XrayR[1026091]: panic: Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:33 #hostname#XrayR[1026091]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:33 #hostname#XrayR[1026091]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:33 #hostname#XrayR[1026091]: goroutine 1 [running]:
Jan 07 12:09:33 #hostname#XrayR[1026091]: log.Panicf({0x203e517, 0xc0001682a0}, {0xc00085dea0, 0xc000167030, 0xc00063fe88})
Jan 07 12:09:33 #hostname#XrayR[1026091]:         log/log.go:361 +0x67
Jan 07 12:09:33 #hostname#XrayR[1026091]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000513200)
Jan 07 12:09:33 #hostname#XrayR[1026091]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Jan 07 12:09:33 #hostname#XrayR[1026091]: main.main()
Jan 07 12:09:33 #hostname#XrayR[1026091]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jan 07 12:09:34 #hostname#systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 07 12:09:34 #hostname#systemd[1]: XrayR.service: Failed with result 'exit-code'.
Jan 07 12:09:44 #hostname#systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Jan 07 12:09:44 #hostname#systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 220.
Jan 07 12:09:44 #hostname#systemd[1]: Stopped XrayR Service.
Jan 07 12:09:44 #hostname#systemd[1]: Started XrayR Service.
Jan 07 12:09:44 #hostname#XrayR[1026106]: XrayR 0.7.5 (A Xray backend that supports many panels)
Jan 07 12:09:44 #hostname#XrayR[1026106]: 2022/01/07 12:09:44 Start the panel..
Jan 07 12:09:44 #hostname#XrayR[1026106]: 2022/01/07 12:09:44 Xray Core Version: 1.5.1
Jan 07 12:09:44 #hostname#XrayR[1026106]: 2022/01/07 12:09:44 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:44 #hostname#XrayR[1026106]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:44 #hostname#XrayR[1026106]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:44 #hostname#XrayR[1026106]: panic: Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":2,"node_speedlimit":0,"traffic_rate":2.5,"mu_only":1,"sort":11,"server":"#IP#;10009;0;ws;tls;path=/1|server=#host#|host=#host#|outside_port=443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 07 12:09:44 #hostname#XrayR[1026106]: Error: strconv.Atoi: parsing "": invalid syntax,
Jan 07 12:09:44 #hostname#XrayR[1026106]: Please check the doc of custom_config for help: https://crackair.gitbook.io/xrayr-project/dui-jie-sspanel/sspanel/sspanel_custom_config
Jan 07 12:09:44 #hostname#XrayR[1026106]: goroutine 1 [running]:
Jan 07 12:09:44 #hostname#XrayR[1026106]: log.Panicf({0x203e517, 0xc0005c9880}, {0xc00085dea0, 0xc0005c8850, 0xc00063fe88})
Jan 07 12:09:44 #hostname#XrayR[1026106]:         log/log.go:361 +0x67
Jan 07 12:09:44 #hostname#XrayR[1026106]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000519200)
Jan 07 12:09:44 #hostname#XrayR[1026106]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Jan 07 12:09:44 #hostname#XrayR[1026106]: main.main()
Jan 07 12:09:44 #hostname#XrayR[1026106]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jan 07 12:09:44 #hostname#systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 07 12:09:44 #hostname#systemd[1]: XrayR.service: Failed with result 'exit-code'.
Jan 07 12:09:55 #hostname#systemd[1]: XrayR.service: Service RestartSec=10s expired, scheduling restart.
Jan 07 12:09:55 #hostname#systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 221.
Jan 07 12:09:55 #hostname#systemd[1]: Stopped XrayR Service.
'.

**Comment by RainThings** [comment]
数据库导出 
[
{"type":"header","version":"5.1.0","comment":"Export to JSON plugin for PHPMyAdmin"},
{"type":"database","name":""},
{"type":"table","name":"node","database":"","data":
[
{"id":"10","name":"","type":"1","server":";10009;0;ws;tls;path=\/1|server=|host=|outside_port=443","info":"无描述","status":"可用","sort":"11","traffic_rate":"2.5","node_class":"2","node_speedlimit":"0.00","node_connector":"0","node_bandwidth":"769983854","node_bandwidth_limit":"536870912000","bandwidthlimit_resetday":"1","node_heartbeat":"1641572873","node_ip":"","node_group":"0","mu_only":"1","online":"0","gfw_block":"0","custom_config":"0x7b7d"}
]
}
]

**Comment by RManLuo** [comment]
ApiConfig下增加DisableCustomConfig。
配置参考：
```
ApiConfig:
      ApiHost: "http://127.0.0.1:9898"
      ApiKey: "123"
      NodeID: 1
      NodeType: V2ray # Node type: V2ray, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 40 # Timeout for the api request
      EnableVless: false # Enable Vless for V2ray Type
      EnableXTLS: false # Enable XTLS for V2ray and Trojan
      SpeedLimit: 0 # Mbps, Local settings will replace remote settings, 0 means disable
      DeviceLimit: 0 # Local settings will replace remote settings, 0 means disable
      RuleListPath: # ./rulelist # Path to local rulelist file
      DisableCustomConfig: true
```

**Comment by RainThings** [comment]
即使是正确的custom_config也会报错，只能禁用才能恢复正常

**Comment by tanpengsccd** [comment]
一样的问题

```

Jan 25 16:01:27 hhse systemd[1]: XrayR.service: Scheduled restart job, restart counter is at 351.
Jan 25 16:01:27 hhse systemd[1]: Stopped XrayR Service.
Jan 25 16:01:27 hhse systemd[1]: Started XrayR Service.
Jan 25 16:01:27 hhse XrayR[148445]: XrayR 0.7.5 (A Xray backend that supports many panels)
Jan 25 16:01:27 hhse XrayR[148445]: 2022/01/25 16:01:27 Start the panel..
Jan 25 16:01:27 hhse XrayR[148445]: 2022/01/25 16:01:27 Xray Core Version: 1.5.1
Jan 25 16:01:28 hhse XrayR[148445]: 2022/01/25 16:01:28 Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":0,"node_speedlimit":0,"traffic_rate":1,"mu_only":-1,"sort":11,"server":"node1.baidu.com;port=10443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 25 16:01:28 hhse XrayR[148445]: Error: strconv.Atoi: parsing "port=10443": invalid syntax
Jan 25 16:01:28 hhse XrayR[148445]: panic: Panel Start fialed: Parse node info failed: {"node_group":0,"node_class":0,"node_speedlimit":0,"traffic_rate":1,"mu_only":-1,"sort":11,"server":"node1.baidu.com;port=10443","type":"SSPanel-UIM","custom_config":[],"version":"2021.11"},
Jan 25 16:01:28 hhse XrayR[148445]: Error: strconv.Atoi: parsing "port=10443": invalid syntax
Jan 25 16:01:28 hhse XrayR[148445]: goroutine 1 [running]:
Jan 25 16:01:28 hhse XrayR[148445]: log.Panicf({0x203e517, 0x0}, {0xc000c65ea0, 0xc0005ba620, 0xc00063fe88})
Jan 25 16:01:28 hhse XrayR[148445]:         log/log.go:361 +0x67
Jan 25 16:01:28 hhse XrayR[148445]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc00051ec80)
Jan 25 16:01:28 hhse XrayR[148445]:         github.com/XrayR-project/XrayR/panel/panel.go:174 +0x588
Jan 25 16:01:28 hhse XrayR[148445]: main.main()
Jan 25 16:01:28 hhse XrayR[148445]:         github.com/XrayR-project/XrayR/main/main.go:92 +0x1ed
Jan 25 16:01:28 hhse systemd[1]: XrayR.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 25 16:01:28 hhse systemd[1]: XrayR.service: Failed with result 'exit-code'.
```

**Comment by thank243** [comment]
把port=10443改成10433呢

**Comment by tanpengsccd** [comment]
DisableCustomConfig 只要设置为 false 时 开启 新特性时,即便面板完全抄示例 的也会 报错.
和楼主错误一样
```
 Error: strconv.Atoi: parsing "": invalid syntax,
```
